### ISSUE TITLE
[ROUTE] - EXAMPLE_ROUTE

### ISSUE THREAD

**Issue by gosimulate** [gosimulate/gosimulator#1]
# FIND CUSTOM ROUTES UNDER [MILESTONE ROUTE](https://github.com/gosimulate/gosimulator/milestone/2?closed=1) ROUTE POSTS ARE CLOSED TO PREVENT CLUTTER

###CUSTOM ROUTES###
Keep files like: 

city_place or landmark_country.txt
IN FILE:
X COORD, Y COORD
X COORD, Y COORD
X COORD, Y COORD
X COORD, Y COORD
etc...

EXAMPLE
[Tokyo_Imperial.Palace.East.Gardens_Japan.txt](https://github.com/gosimulate/gosimulator/files/417163/tmp_13904-Tokyo_Imperial.Palace.East.Gardens_Japan576351924.txt)

# **MAKE SURE THERE ARE NO EMPTY SPACES IN FILE OR SIMULATOR WILL CRASH ON START**

__________________________________________
FOR THOSE WHO DON'T KNOW HOW TO READ README.MD

Please follow these steps. Yes, you actually have to make a complete route. You cannot just post in xda thread asking for one. It takes time and patience to make a good route.

Go to http://www.findlatitudeandlongitude.com/click-lat-lng-list/

Find your starting point and zoom in super close. Note that the map legend shows you how long 5 meters is.

Next you will keep clicking steps as you make a long path through the area. Each click needs to be 5-15 meters apart.

NOTE-Your goal is to click each step (coordinate) on the web page. It needs to be between 5-15 meters for each click (coordinate). Click a nice route through a city, including plenty of rare spawns and Pokestops.
Create a text file title using the naming convention City_UniqueLandmark_State_Country.txt and dump your paths long list of coordinates.

Save file on sd card and use it through Custom route.

Open issue here with name [ROUTE] - NAME_OF_ROUTE and post txt file in. This helps other users use the same route

**Comment by dees040** [comment]
Maybe something for the TODO list: Custom route import. I guess that will cost you (as developer) less time, eventually.

**Comment by gr33nd3v1l** [comment]
Keep files like: 

city_place or landmark_country.txt
IN FILE:
 [ROUTE] CITY_LANDMARK_COUNTRY
X COORD, Y COORD
etc...

**Comment by minibiizz** [comment]
Hello from Thailand. We have over a million are playing PokemonGO here.
Thank you for an awesome application. Hope this city will appear on next update soon

[Bangkok_SiamParagon_Thailand.txt](https://github.com/gosimulate/gosimulator/files/416733/Bangkok_SiamParagon_Thailand.txt)

**Comment by gr33nd3v1l** [comment]
Do not include anything except coordinates for custom routes. I will edit all routes tonight.

**Comment by nonamedeadpool** [comment]
can someone kik me and tell me how to create a route please @sunsunny1 kik me saying pokemon go
