### ISSUE TITLE
[ROUTE] - Durban Ushaka Marine World (Incomplete)

### ISSUE THREAD

**Issue by Morkai-bde** [gosimulate/gosimulator#10]
This is an incomplete route that needs refining
This route passes by a bunch of pokestops that are usually lured at night (6PM-2AM CEST)
The 3 Base starter pokemon spawn usually at a rate of 2-5 per hour
Dratini's, Kabuto's and Omanite's also spawn as well as Ghastly's with a few more common pokemon as well

Visual Route:
![durban_ushaka marine world_za](https://cloud.githubusercontent.com/assets/20994840/17629424/93a83e8c-60ba-11e6-95ef-1b42636d0945.png)
Txt:
[Durban_Ushaka Marine World_ZA.txt](https://github.com/gosimulate/gosimulator/files/415735/Durban_Ushaka.Marine.World_ZA.txt)

**Comment by gosimulate** [comment]
Please rename issue to [ROUTE] - Name of route !
