### ISSUE TITLE
[Bug] Looting Pokestops "Awarded Items:" text isn't working properly

### ISSUE THREAD

**Issue by PoGoHelp** [gosimulate/gosimulator#100]
When I start up the bot and it hits up a pokestop it will tell me what I got for example. 

"Loot Pokestop (Pokestop name). Awarded Items: Pokeball, Great Ball, Revive"  

However when it gets to other pokestops all it tells me is this.

"Loot Pokestop (pokestop name). Awarded Items: "
It remains blank. I have to note that this doesn't happen to each pokestop. I'd say around 40% of pokestops do this. I'm not sure if it's a bot bug or what. 

Here's a screenshot: http://i.imgur.com/0EGm3e1.png

**Comment by gr33nd3v1l** [comment]
Your bag is full

**Comment by PoGoHelp** [comment]
Is there a way I can sign into my account without triggering a softban? I'll need to clean out my bag but I don't want to risk getting banned

**Comment by gr33nd3v1l** [comment]
Disable Location and you can log in to do management without triggering GPS
