### ISSUE TITLE
Transferring Pokemon, Viewing Bag/Deleting Items

### ISSUE THREAD

**Issue by BadSly** [gosimulate/gosimulator#106]
i set the settings to "Transfer Below IV: 85" but not all pokemon below IV 85 is transferred.
can you add a feature where we can view all our pokemon with details(pokemon image, name, cp, iv(100% 15/15/15) ) and we can mark the ones we like to transfer.
and a feature where we can view and delete items. :+1:

**Comment by gr33nd3v1l** [comment]
Being worked on #23
