### ISSUE TITLE
[ADD] New feature next release

### ISSUE THREAD

**Issue by insider111** [gosimulate/gosimulator#108]
Add the latest features such as the use of ultraball over cp and great ball above cp, and also features rare pokemon sniping from the nearest place is on the map. and a section to enter an account on the move at the beginning open the app and add the button to exit the account. 😂 👍

**Comment by djfaizp** [comment]
As it can remember where did we leave at last location it shoulf start from there as after restart it shows at  Slovenia so we need to zoom in at that location every time and map screen look little bit small 

Thanx for 1.9 it's amazing

**Comment by gr33nd3v1l** [comment]
#23
