### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by AkmlSteklov** [gosimulate/gosimulator#109]
this app doesn't work for me. tried the 1.8 and 1.9 version. the last time it works for me was 1.4.1 then after that it doesn't work. it just sits there saying successfully logged in and catch a few pokemon but when it encountered first pokestop the message stop showing. oh and it always says i have to disable adblock meanwhile i dont have adblock. can someone guide me to solve my problem or at least paste a link to version 1.4.1. thank you for the help. my bot setting was speed at medium. that's all. i have lucky patcher and link2sd. using xiaomi redmi note 3g and rooted. tried to run as system app and third party. it's the same.

**Comment by roofyoreppin** [comment]
Can you try with all antivirus/adblocking/screen lock software removed? Reboot your phone before trying to bot.

**Comment by djfaizp** [comment]
I have one solution as i was also faced go to Lucky patcher >Toolbox (At bottom left side)>Blockadds> click unblock add and click clear the local hosts file  >done? > unintsall app reboot and intall it again Now start i must be ok if you have no av or adblocker then it must run

**Comment by AkmlSteklov** [comment]
nope. not working too. so i'll probably just stick to the old plain moving around searching pokemon

**Comment by gr33nd3v1l** [comment]
The simulator itself has a built in detection of adblockers so until you remove the other, simulator won't work
