### ISSUE TITLE
Ad addresses

### ISSUE THREAD

**Issue by Apo19** [gosimulate/gosimulator#110]
Can you give the ad addresses, will add to the whitelist

**Comment by VernMcC** [comment]
I tried this by adding every address in a tcpdump during a play session to my white list.  I then turned adblockers back on with those entries in the white list. (my intent was to then scale back one at a time,  I was guessing Google ad services).  However,  even though I then got the ads in the app,  the app detected the ad blocker and failed to move the avatar.  I cannot run the device without ad blocker,  so I had to choose to remove the app for now.  If you get it to work,  report back. I have a rooted test device with adaway running including custom host file.

**Comment by gosimulate** [comment]
Just close add blocker !

**Comment by biztastic** [comment]
was there ever a solution to this? Some of us like to run this in the background while we do other stuff that doesn't require ads. Especially those of us who paid for the ad-free version.

**Comment by gr33nd3v1l** [comment]
The ads used are Google Ads targeted at mobile phones, if that helps you

**Comment by biztastic** [comment]
Why does the ad-free version have the AdBlock checker?
