### ISSUE TITLE
[ROUTE] Melbourne, Lillydale Lake, Australia (Reworked)

### ISSUE THREAD

**Issue by gr33nd3v1l** [gosimulate/gosimulator#112]
Improved Lillydale route

BALANCED
MASSIVE EEVEE NESTS
HUGE XP/H
HIGH speed

![capture](https://cloud.githubusercontent.com/assets/3631381/17662833/b3c717ee-62e8-11e6-8589-3b705ff3f738.PNG)
[Melbourne_Lillydale Lake_Australia.txt](https://github.com/gosimulate/gosimulator/files/417929/Melbourne_Lillydale.Lake_Australia.txt)

**Comment by gr33nd3v1l** [comment]
Will leave open for a few hours

**Comment by djfaizp** [comment]
Is there any way to get coordinates lag/long from .gpx file it is showing me time lag lat and speed to many stamps as i only need lag/lat

**Comment by gr33nd3v1l** [comment]
Try googling it
