### ISSUE TITLE
[Most Critical Issue] Must Take Notice

### ISSUE THREAD

**Issue by djfaizp** [gosimulate/gosimulator#113]
As I have Seen To Many sites And Googling Anf shows Many Video on Youtube.For Alternative App as Go Sim .But There Is only This app.Nor Any Thing is Created Like this App Ever .There are To many People's are Placing(Uploading) Your App on Their Website's and Blog's and YouTube channel. As It Sounds Good But Those Are  Claiming That This App Is Created By Them As Some of Them My Salling Your App And Getting Donations As They are Not Eligible ForThat ...So It Is hardly Recommended To Dev That Take Action And Do As You can So Ppl Who are Using This App They Can Notice Who Empowered This App As It Is Awesome App @gosimulate

**Comment by gr33nd3v1l** [comment]
Since most of them don't really know about this github and steal it from his Twitter. I'd simply release a .zip password protected, and release the password on here

@gosimulate

**Comment by djfaizp** [comment]
Zip protection !!! As They will Also Get Pass From Here You should Implement In App Like Credit And Other Things Like Donation Option And Highly Encryption needed As They Will Change Its Values By editing Menifiest.xml

**Comment by gosimulate** [comment]
May i see any of those sites ?

**Comment by gr33nd3v1l** [comment]
https://support.google.com/youtube/answer/2807622

For this video: https://www.youtube.com/watch?v=TmjW1UDHIfE
He claims he made it

**Comment by nonamedeadpool** [comment]
people are so desperate for money passes me off

**Comment by djfaizp** [comment]
I have done my job so closing this issue
