### ISSUE TITLE
pokestop loot problem

### ISSUE THREAD

**Issue by eran34** [gosimulate/gosimulator#114]
It does not collect anything from the pokestop but marks of having been there

**Comment by VernMcC** [comment]
Is your bag full?

**Comment by eran34** [comment]
Yes

**Comment by eran34** [comment]
No now it's not full but still don't collect anything

**Comment by gr33nd3v1l** [comment]
Did your app go out of system memory

**Comment by ManusiaDariBumi** [comment]
well maybe pokestop is already cleared
