### ISSUE TITLE
[ISSUE]How to avoid permaban? 

### ISSUE THREAD

**Issue by Glasses08** [gosimulate/gosimulator#116]
I've been using GoSim for about 3 days now. 
On the first day, I've botted on a level 20 acc which I spent like 7 days grinding pokemans manually (been using the joystick spoof). Greedy as I was, I botted for a day using the app. Slow rate and a nearby route. Using the app I levled up successfully. 
On the second day, I ran the bot again and left it running the whole afternoon (4 hours).  Then later I checked,  my lvl 21 acc was banned. I received an error saying "Failed to get game data from server" then after countless restarts I was greeted by the "servers are down"  screen. :( So sad. I got mad at first but who's to blame but me? Cheaters can't be pickers. I then moved on. I created another account that same day. And gave the bot another chance.
Used slow speed, used a route right near me, and left it botting the whole night. When I checked the account the next morning,  from level 1 it got to level 12. Not bad. Botted for like 5 hours. I felt like everything would be fine. But I was wrong. Later that afternoon my 2nd account got permabanned.  *cries.
Question is: How do you guys do it?  How do you bot properly? How to avoid bein permabanned?

**Comment by Glasses08** [comment]
Update: Using my 2nd account,  I ran the bot and it logged in and it was doing its job. Caught pokemon and looted pokestops. But whenever I try to login using the PokeGo app, I get the servers are down screen.

**Comment by gr33nd3v1l** [comment]
I guess you'll just have to be more careful.. Niantic watches everything so I don't plan on giving away my super secret methods. :p

**Comment by Dqtreats** [comment]
Lol I have many methods to hide my spoofing. I've been botting on one account for nearly 12 hours every day for the past week. Still haven't been banned.

**Comment by gr33nd3v1l** [comment]
I've made 2 accounts in the past 2 days both of which have been abused with the simulator to the max. Jumping continents etc.. both are lvl 20 and not banned

**Comment by Dqtreats** [comment]
Haha my man! That's awesome. I've just been jumping from NY to LA. About to make another account and give this one to my wife.

**Comment by gr33nd3v1l** [comment]
I never intended them to get this many levels... I am just testing out routes to find something better than Lillydale :8ball:

**Comment by Glasses08** [comment]
Welp. Thanks for the usefull advices. 
I've learned that when botting, don't get too attached to one account. Make multiple accounts and bot. Then try your luck there.
Btw,  thank you dev. Please do continue your hardwork. Will look forward to future updates. Just hope Niantic won't find out about this app.

**Comment by gr33nd3v1l** [comment]
You shouldn't really bot with your main account anyway.. That's no way to play the game :smiling_imp:
