### ISSUE TITLE
How to make bot loop on custom route?

### ISSUE THREAD

**Issue by lance2cool** [gosimulate/gosimulator#117]
Hi I made my first custom route and upon using it I noticed that the bot went back from its previous point instead of doing a loop when reaching the last point.

Ps. I made my last point same with the starting point coordinate. 

Kindly check custom route below.
Eastwood Philippines
14.607304,121.078717
14.607344,121.07881
14.607388,121.078909
14.607432,121.079005
14.60748,121.079109
14.607531,121.079211
14.607585,121.079323
14.607659,121.079431
14.607731,121.079545
14.60778,121.079687
14.607861,121.079833
14.607923,121.079949
14.607988,121.080069
14.60806,121.080187
14.608135,121.080266
14.608214,121.080304
14.608275,121.080335
14.608382,121.080356
14.608485,121.080356
14.608563,121.080283
14.608652,121.080174
14.60874,121.080086
14.60884,121.080089
14.608914,121.080063
14.609014,121.080098
14.60912,121.080117
14.609198,121.080124
14.609282,121.080194
14.60935,121.080271
14.609422,121.080344
14.609506,121.080426
14.609578,121.080489
14.609661,121.080556
14.609748,121.080609
14.609843,121.080661
14.609954,121.080709
14.610093,121.080729
14.610202,121.080751
14.610304,121.080739
14.610431,121.080721
14.610558,121.080684
14.61066,121.080635
14.610756,121.080578
14.610845,121.080507
14.610934,121.080428
14.61101,121.080341
14.611061,121.08024
14.611101,121.080138
14.611108,121.080037
14.611126,121.079942
14.611146,121.079837
14.611146,121.079728
14.611115,121.079597
14.611064,121.079487
14.611019,121.079377
14.61095,121.079266
14.610869,121.079166
14.61077,121.079076
14.610686,121.078987
14.610577,121.078911
14.610475,121.078816
14.610387,121.078753
14.610299,121.078679
14.610186,121.078728
14.610122,121.078832
14.61003,121.078919
14.609941,121.07901
14.609868,121.079094
14.609764,121.07917
14.609684,121.079217
14.609569,121.079265
14.609464,121.079311
14.609373,121.079383
14.609283,121.079458
14.609205,121.079534
14.60914,121.079595
14.609068,121.079671
14.608993,121.07976
14.609018,121.079856
14.609037,121.079957
14.608902,121.079898
14.608785,121.079826
14.608726,121.079707
14.608659,121.079602
14.608578,121.079554
14.608492,121.079502
14.608423,121.079463
14.608338,121.079403
14.608265,121.079349
14.608182,121.079268
14.608112,121.079187
14.608025,121.079099
14.607934,121.079007
14.607847,121.078928
14.607761,121.07888
14.60767,121.078809
14.607556,121.078704
14.607454,121.078622
14.607334,121.078641
14.607304,121.078717

**Comment by gr33nd3v1l** [comment]
#23 The bot loops back once it reaches last point.

Possible improvement in future will be circular bot movement

**Comment by lance2cool** [comment]
14.607262,121.078689
14.607291,121.078741
14.607335,121.078806
14.607378,121.078862
14.607426,121.078918
14.607458,121.078976
14.607461,121.079069
14.607501,121.079143
14.607528,121.079218
14.607566,121.079298
14.607609,121.079367
14.607641,121.07944
14.60767,121.079501
14.607705,121.079558
14.607731,121.079616
14.607765,121.07967
14.607785,121.079719
14.607811,121.079778
14.607856,121.079837
14.607898,121.079891
14.607924,121.079952
14.607955,121.080006
14.607984,121.080073
14.608025,121.08013
14.608069,121.080218
14.608042,121.08031
14.608044,121.080354
14.608034,121.080403
14.608036,121.080452
14.60805,121.080518
14.608079,121.080597
14.608106,121.080654
14.608132,121.080709
14.608177,121.080763
14.608214,121.080789
14.608251,121.080833
14.608281,121.080879
14.608328,121.080925
14.60837,121.08097
14.608422,121.081023
14.608476,121.081068
14.608521,121.081116
14.608552,121.081166
14.6086,121.081204
14.60864,121.081249
14.608694,121.081303
14.608747,121.081372
14.608783,121.081419
14.608821,121.081462
14.608858,121.081502
14.608897,121.081547
14.608939,121.081599
14.608942,121.08166
14.608929,121.081728
14.608883,121.081781
14.608838,121.081838
14.60879,121.081887
14.608738,121.081932
14.608685,121.081956
14.608624,121.081936
14.608587,121.081889
14.608555,121.081841
14.608513,121.081795
14.608452,121.08175
14.608385,121.081749
14.608332,121.081773
14.608269,121.081816
14.608221,121.081866
14.608167,121.081924
14.608144,121.081948
14.608102,121.081975
14.608079,121.082015
14.608059,121.082066
14.608021,121.082095
14.60799,121.08214
14.607944,121.082174
14.607887,121.082182
14.607835,121.082168
14.607785,121.082156
14.607741,121.082145
14.607695,121.082123
14.607648,121.082109
14.607606,121.082095
14.607556,121.082082
14.607499,121.082064
14.607423,121.082042
14.607382,121.082003
14.60737,121.081958
14.607383,121.081919
14.607413,121.081895
14.607436,121.08187
14.60747,121.081836
14.607512,121.081797
14.607534,121.081763
14.607552,121.081742
14.607564,121.081722
14.607583,121.081703
14.6076,121.081683
14.607618,121.081661
14.607645,121.081636
14.607668,121.081603
14.607696,121.081568
14.607735,121.08153
14.607768,121.081502
14.607794,121.081489
14.607836,121.081466
14.607875,121.081429
14.60793,121.081408
14.607985,121.081385
14.608019,121.081366
14.608057,121.081346
14.608098,121.081324
14.608122,121.081306
14.608156,121.081288
14.608203,121.081268
14.608245,121.081243
14.608295,121.081205
14.608338,121.081158
14.60839,121.081112
14.608428,121.081077
14.608482,121.08103
14.608528,121.080982
14.608578,121.080941
14.608618,121.080896
14.608661,121.080861
14.608679,121.080834
14.608687,121.08079
14.608709,121.080755
14.608749,121.080782
14.608774,121.08082
14.608806,121.080843
14.608847,121.080868
14.608896,121.080882
14.608953,121.080902
14.609017,121.080915
14.60909,121.080912
14.609144,121.0809
14.609206,121.080875
14.60928,121.080835
14.609314,121.080796
14.609346,121.080763
14.609398,121.080719
14.609429,121.080696
14.60945,121.080665
14.609483,121.080613
14.609521,121.080555
14.609543,121.080531
14.609568,121.080491
14.609603,121.080519
14.609596,121.080582
14.609631,121.080576
14.609683,121.080588
14.609733,121.080609
14.609778,121.080638
14.609825,121.080649
14.609882,121.080678
14.609927,121.0807
14.609982,121.080718
14.61004,121.080733
14.610095,121.080743
14.610165,121.080755
14.610231,121.080754
14.610294,121.080753
14.610358,121.080751
14.61042,121.080736
14.610488,121.080724
14.610535,121.080703
14.610588,121.08069
14.610624,121.080659
14.610673,121.080642
14.610711,121.080615
14.610737,121.080582
14.610777,121.080558
14.610816,121.080525
14.610864,121.080493
14.610908,121.080454
14.610943,121.080425
14.610973,121.080393
14.611,121.080332
14.611032,121.080278
14.611052,121.080238
14.611074,121.080187
14.611097,121.08013
14.611111,121.080071
14.611117,121.080016
14.611128,121.079965
14.611133,121.079892
14.611145,121.079842
14.611144,121.079786
14.61113,121.079707
14.611115,121.079637
14.611098,121.079583
14.611078,121.079517
14.61106,121.079459
14.611037,121.079391
14.610997,121.079329
14.610956,121.079278
14.610925,121.079239
14.610882,121.079191
14.610834,121.079141
14.610797,121.07912
14.610756,121.07908
14.610721,121.079046
14.610683,121.079007
14.61064,121.078973
14.610608,121.078944
14.610573,121.078909
14.610542,121.078881
14.610498,121.078849
14.610452,121.078813
14.610405,121.078766
14.610358,121.07873
14.610299,121.078678
14.610241,121.078625
14.610194,121.078555
14.610166,121.078497
14.610133,121.078439
14.610089,121.078404
14.610031,121.078334
14.609991,121.078299
14.609953,121.078225
14.609951,121.078172
14.609978,121.078105
14.610008,121.078068
14.610047,121.077998
14.610084,121.077963
14.610131,121.077916
14.610086,121.077901
14.610055,121.077967
14.610021,121.078038
14.609982,121.078126
14.609967,121.078176
14.609971,121.078267
14.610029,121.078342
14.610089,121.078393
14.610139,121.078463
14.610171,121.078527
14.610208,121.078608
14.610259,121.078668
14.610203,121.078711
14.61016,121.078759
14.61011,121.07883
14.610058,121.078894
14.609996,121.078966
14.60995,121.079015
14.609898,121.079065
14.609833,121.079118
14.609777,121.079161
14.609714,121.079195
14.609666,121.079227
14.60959,121.079247
14.609515,121.07929
14.609445,121.079339
14.609387,121.079383
14.609304,121.079432
14.609256,121.079485
14.6092,121.079547
14.609143,121.079559
14.609104,121.079616
14.609071,121.079678
14.609029,121.079725
14.608981,121.079775
14.60892,121.079835
14.608931,121.079883
14.608973,121.079951
14.609045,121.08002
14.609108,121.080086
14.609115,121.080151
14.609058,121.080198
14.608981,121.080226
14.608943,121.08024
14.608887,121.080214
14.608825,121.0802
14.608761,121.080149
14.608707,121.080079
14.608758,121.08009
14.608817,121.080065
14.608829,121.080019
14.608864,121.080012
14.608878,121.079981
14.60889,121.079933
14.608901,121.079879
14.608931,121.079835

Updated route above

**Comment by fierywintersnow** [comment]
Nice route. So many pokestops. Mind making a route for rizal park? Or just teach how to make a route. Thank you sir!
