### ISSUE TITLE
 Unfortunately Go Simulator has stopped.

### ISSUE THREAD

**Issue by m4yh3m** [gosimulate/gosimulator#118]
Ever since the last update app has been crashing. My settings are as what they were in the previous versions where it used to work. Tried toggling different options but to no avail.

**Comment by m4yh3m** [comment]
It stops whenever I try to start the bot.

**Comment by gr33nd3v1l** [comment]
README.md

**Comment by m4yh3m** [comment]
Yeah I checked that. Didn't leave anything blank.

**Comment by gr33nd3v1l** [comment]
Are you using a custom route

**Comment by m4yh3m** [comment]
Razz is off. Not using custom route.

**Comment by gr33nd3v1l** [comment]
What route are you using

**Comment by m4yh3m** [comment]
Tried disney, new york, and DC which all used to work for me. Tried with predefined toggled on and off.

**Comment by gr33nd3v1l** [comment]
Do you have a test account

**Comment by m4yh3m** [comment]
Nope.

**Comment by gr33nd3v1l** [comment]
Try using one of the custom routes and see if that works for you
Other than that, I really don't know where you made a mistake. Try a fresh reinstall

**Comment by Dqtreats** [comment]
Did you clear your data before you uninstalled the last version? I had this problem and had to go back to 1.1.0 to clear data, then download the update.

**Comment by m4yh3m** [comment]
Hmm just tried that. Went back to 1.7.1 which was the last version that worked(it doesn't anymore) and cleared data before uninstalling. Installed the update but unfortunately still didn't work.

**Comment by Dqtreats** [comment]
Change the values on which cp you evolve and transfer at. See if that helps or check to see if your account is banned. And you said your razz is off, did you change the value to 100,000?

**Comment by m4yh3m** [comment]
Oh. Seems I was banned. Lol oh well thanks for letting me waste you're time.

**Comment by gr33nd3v1l** [comment]
Derp.
