### ISSUE TITLE
[Route] Central London

### ISSUE THREAD

**Issue by faizmodan** [gosimulate/gosimulator#12]
[covered whole area's london.txt](https://github.com/gosimulate/gosimulator/files/416081/covered.whole.area.s.london.txt)
Romove old route that i was send i am sending new route and i am working on it  as i will send you route with full module so more pokemon can be caught and more. XP👍✌👌🙋 Great Work By dev

**Comment by deady47** [comment]
how to add route to app gosim.??
i have new route.txt but i am confius..!

**Comment by faizmodan** [comment]
Leave issue with [ROUTE] TITLE and upload your .txt on issue and put importance of your route so as may it will coincided by dev 😋 have fun bro may all botter will get caught when niantic will see your softban log 😝😝😝 including me also
