### ISSUE TITLE
[ROUTE] Retiro Park - Madrid

### ISSUE THREAD

**Issue by juanxito91** [gosimulate/gosimulator#122]
Hi.

I'm Spanish, and one of the best parts for pokestops and pokemons in Madrid is Retiro Park. 

There, we have a Scyther's nest, just in case you like this pokemon.

So, I let a little walk along it.

![retiro_park](https://cloud.githubusercontent.com/assets/18647477/17673117/fa43e5a8-631f-11e6-84ca-6d14def69e97.png)

[Park_Retiro_Madrid.txt](https://github.com/gosimulate/gosimulator/files/418603/Park_Retiro_Madrid.txt)

**Comment by Campanillo** [comment]
Thank you for that, already download ando use it. 
How you make it?. Or if you can make another one for "manzanares" zone please. 

Thank u and great work.

**Comment by gr33nd3v1l** [comment]
@Campanillo #1 < read

I can make one for you if you tell me where exactly to walk, where are rare spawns, and what is most common lure location
