### ISSUE TITLE
[ROUTE]: Rio de Janeiro, Brasil

### ISSUE THREAD

**Issue by gr33nd3v1l** [gosimulate/gosimulator#123]
[Rio de Janeiro_Quinta da Boa Vista_Brasil.txt]
(https://github.com/gosimulate/gosimulator/files/418621/Rio.de.Janeiro_Quinta.da.Boa.Vista_Brasil.txt)
![capture](https://cloud.githubusercontent.com/assets/3631381/17673210/775f2c46-6320-11e6-8ace-0f52f3b60ecc.PNG)

MEDIUM

**Comment by azziejay** [comment]
What spawns here?

**Comment by gr33nd3v1l** [comment]
Still testing.. so far nothing very special

**Comment by lecodias** [comment]
It can route sao paulo Please Brazil ?

**Comment by gr33nd3v1l** [comment]
Sure, Sao Paulo coming up - 
Where is most pokemon lure and rare spawns?
@lecodias

**Comment by lecodias** [comment]
Av . Paulista whole to the Ibirapuera Park is a good route in santana also already had appearances of Dragonite and snorlax ... Thank you for your attention and congratulations for the work @gr33nd3v1l

**Comment by gr33nd3v1l** [comment]
#133 @lecodias what more to include - Av Paulista seems a bit far

**Comment by lecodias** [comment]
understand, these two places of sao paulo is where more is Pokemons @gr33nd3v1l
