### ISSUE TITLE
App stops catching pokemon

### ISSUE THREAD

**Issue by x1v16** [gosimulate/gosimulator#124]
My app has dozens of times since I got it filled the bag up completely, and then stopped catching pokemon, and yet doesn't transfer pokemon away. If I change the transfer away to something much higher like anything below 90 IV / 700 CP it still doesn't transfer the pokemon away. I have seen it transfer them away, but I have no idea what circumstances initiate the process. Also, I login and there are 4-9 eggs ready to be hatched. Why isn't the app hatching those for me?

**Comment by gr33nd3v1l** [comment]
You need to log in to PoGO app itself to hatch the eggs since Niantic issues the hatch from server side, not client. When you click the egg you can see it stops for a milisecond, and then changes to animation of hatching.
