### ISSUE TITLE
Bot Timer

### ISSUE THREAD

**Issue by clivejo** [gosimulate/gosimulator#125]
This is a suggestion for the developers. I think a timer for bot could be an awesoke feature. For example you can start a bot for 5 hours, then automatically stop and logoff. Congrats and thanks to developers for the great job you did. This is a fantastic tool if you use this with the brain (or get banned if you prefer) ;)

**Comment by Dqtreats** [comment]
He plans on adding a 12 hour timer. Idk if he is going to make it a variable timer.

**Comment by gr33nd3v1l** [comment]
Referenced in #23 , planned to implement
