### ISSUE TITLE
Some Recommendations and Suggestions for Bot

### ISSUE THREAD

**Issue by Dark25** [gosimulate/gosimulator#126]
A very useful tool that could add is to see the full inventory : the Pokeballs , potions , fruits , incubators, eggs luck and huvos of pokemones in inventory .

All displayed in bot, Because it is somewhat tedious wait a few hours to open the pokemon go to see that we

oh yes and we see how many candies each pokemon

**Comment by gr33nd3v1l** [comment]
Partially included

Most of what you ask would be too intrusive for the bot, so it would be easily detected
