### ISSUE TITLE
[ROUTE]: Kuala Lumpur, Malaysia

### ISSUE THREAD

**Issue by azzrey77** [gosimulate/gosimulator#127]
please make route for klcc park...dataran merdeka and Putrajaya 

_edited_
[Kuala Lumpur_Petronas Towers Dataran Merdeka_Malaysia.txt](https://github.com/gosimulate/gosimulator/files/419045/Kuala.Lumpur_Petronas.Towers.Dataran.Merdeka_Malaysia.txt)
![capture](https://cloud.githubusercontent.com/assets/3631381/17681047/a6adf130-6343-11e6-8adb-9ca870ec3fe6.PNG)

**Comment by gr33nd3v1l** [comment]
Will do.

**Comment by gr33nd3v1l** [comment]
@azzrey77 Test out the route on a test account

**Comment by azzrey77** [comment]
thanks a lot dev

**Comment by gr33nd3v1l** [comment]
Use speed <10, jumps are 20m

**Comment by azzrey77** [comment]
how to test it.. sorry noob here

**Comment by gr33nd3v1l** [comment]
download txt file on sd card of mobile phone
open bot select custom route
custom route find .txt file
start bot

**Comment by azzrey77** [comment]
thanks dev.. ohsem.. later feedback

**Comment by azzrey77** [comment]
done tested.. worked awesome nice job.. superb.. if you dont mind one more route please..PUTRAJAYA (2.943314, 101.700268)

**Comment by gr33nd3v1l** [comment]
There's a lot of routes for asia area already. I'm focused on other continents now

**Comment by nqkqmurq** [comment]
can you teach me how to create a route ?
