### ISSUE TITLE
Can't Log In

### ISSUE THREAD

**Issue by biztastic** [gosimulate/gosimulator#128]
After a fresh install and restart, every time I try to log in I get an error saying"Failed to log in. Your account is probably banned. Please try with official app."

The official app loads just fine. Version 1.9.0 worked fine

PTC account on Android 6.0

**Comment by PoGoHelp** [comment]
Im not sure if ptc accounts work. Only Google accounts so far. I could be wrong though

**Comment by gr33nd3v1l** [comment]
PTC accs work - you probably put in something wrong or need a reinstall

**Comment by biztastic** [comment]
No. Everything is correct. If I try 3 times in a row, it works. Not sure if that's the best method.

**Comment by gr33nd3v1l** [comment]
You probably have some kind of residual data in memory, or your phone processes something differently.

**Comment by narutouchi55** [comment]
PTC accs doesnt work for me neither

**Comment by gosimulate** [comment]
Try loggining via officail app. If you cannot, you're banned. If you can post here again please

**Comment by biztastic** [comment]
I posted that in the original post. I can definitely log into the real app.

**Comment by gr33nd3v1l** [comment]
Can you move around loot pokestops and catch pokemon
Did you try stuff from README

**Comment by biztastic** [comment]
After I try 3 times consecutively, it logs in and works normally. Jusy scary that the initial response is that the app thinks I'm banned. 

My usual upgrade process includes removing and doing a fresh install since I install to system/app

**Comment by narutouchi55** [comment]
I have the same problem, after 3 times it works fine

**Comment by Phanthropogenic** [comment]
Probably the saved data forms of the Sim. Relaunching/Clearing Data would work.

**Comment by FriendZoneKing** [comment]
i also got that message just now.. cant enter the game in the offical app now "Failed to get game data from server" something..

**Comment by narutouchi55** [comment]
When you use a PTC account try 2-3 times to log in if you cant, try using the official PoGo app.
