### ISSUE TITLE
[ROUTE] Singapour, Malasia

### ISSUE THREAD

**Issue by juanxito91** [gosimulate/gosimulator#129]
I created a quite big Singapour route, because some people says that you could find interesting pokemons like Dragonite or Snorlax.

Working perfect and with so much pokestops. 

At the moment that I'm testing this route, I didn't find that pokemons (still in the half of the route, and I should go to the left part, river, of the route), but appart of the common ones (Pidgeys, Eevees, Weedles, Venonats, Rattatas....) y found some good Charmanders (CP521 & CP583)

![singapour](https://cloud.githubusercontent.com/assets/18647477/17675726/453113f0-632b-11e6-8e29-f90b82b53f9a.png)

[Singapure.txt](https://github.com/gosimulate/gosimulator/files/418738/Singapure.txt)

**Comment by xitopodo** [comment]
Snorlax caught!

![screenshot_20160815-212803](https://cloud.githubusercontent.com/assets/18647477/17676573/8054a808-632f-11e6-9378-2585165373da.png)

**Comment by PoGoHelp** [comment]
Will try it out!

**Comment by gr33nd3v1l** [comment]
Good job! Included
