### ISSUE TITLE
[ROUTE]: Victoria BC

### ISSUE THREAD

**Issue by sickghettopuppet** [gosimulate/gosimulator#13]
Made a route Going along Victorias water front!
You start at the breakwater with 12 pokestops along it (you will prob get 20 or so on medium speed) going to beacon hill park, where all the rare pokemon are caught (depends what you consider rare, but it is known to have scythers, pinsers, aerodactyl, eggexecute, tauros, etc.) with a surplus of eevees and charmanders then off to clover point which is currently a pikachu nest, with magnemites, polywags and magikarps as well. then back towards the breakwater. You walk along dallas road (past mile 0 for canadian highway 1) and at night you can add some ghastlys to be common.

EDIT: What the breakwater looks like http://imgur.com/eEQqHVh  (Not my picture)
[Victoria_WaterFront_BC_CANADA.txt](https://github.com/gosimulate/gosimulator/files/416127/Victoria_WaterFront_BC_CANADA.txt)

**Comment by gosimulate** [comment]
Edit issue name: to [ROUTE]: Name of route. Ty
