### ISSUE TITLE
[ROUTE]: Quezon City, Phillippines

### ISSUE THREAD

**Issue by gr33nd3v1l** [gosimulate/gosimulator#134]
@rockybalbon027 

[Quezon City_City Circle_Phillippines.txt](https://github.com/gosimulate/gosimulator/files/419196/Quezon.City_City.Circle_Phillippines.txt)
![capture](https://cloud.githubusercontent.com/assets/3631381/17683247/8a859a04-6351-11e6-90d0-19c494c91b0a.PNG)

**Comment by rockybalbon027** [comment]
Ty sir

**Comment by rockybalbon027** [comment]
Ty sir

**Comment by rockybalbon027** [comment]
Sir last request route for eevee nest please

**Comment by gr33nd3v1l** [comment]
Premade route: Melbourne Lilydale lake

Huge eevee nest

**Comment by xweirdow23** [comment]
gr33nd3v1l how about nest or where to catch lots of dratini/dragonair

**Comment by gr33nd3v1l** [comment]
Sydney Opera House
