### ISSUE TITLE
Regional pokemon

### ISSUE THREAD

**Issue by joshie3399** [gosimulate/gosimulator#135]
can anyone please provide the route  if they have caught any of the region locked pokemon?

**Comment by biztastic** [comment]
I caught Tauros in the Atlanta route.

**Comment by gr33nd3v1l** [comment]
Farfetch'd is in hong kong

**Comment by jrdan1991** [comment]
Hi greendevil can you make a route for sta. Rosa, Laguna, philippines TIA..,

**Comment by gr33nd3v1l** [comment]
There's already a lot of routes for Phillippines

**Comment by gr33nd3v1l** [comment]
Kangashkan at opera house right now

**Comment by gr33nd3v1l** [comment]
Mr. Mime in Dűsseldorf

**Comment by rmessi0688** [comment]
Hey do you have a custom route you can link for the opera house. Thanks!

**Comment by gr33nd3v1l** [comment]
#161

**Comment by jrdan1991** [comment]
Sad me

**Comment by jrdan1991** [comment]
Sad me
