### ISSUE TITLE
Failed to catch xxxx

### ISSUE THREAD

**Issue by BlinddHeart** [gosimulate/gosimulator#136]
On my main account. no matter what option I select. even if I select the slowest and lowest step, it still says failed to catch pokemon. I am still able to get items from pokestop. is it the server? if so, after a few failed captures, it says I got soft banned, then the app Removed the ban, and same thing happens again over, I'm able to get items but unable to catch. help? much is appreciate it for the creator's hard work and time that he spend on this project! special thanks.

**Comment by gr33nd3v1l** [comment]
#74
