### ISSUE TITLE
Unable to loot pokestops and catch pokemon

### ISSUE THREAD

**Issue by dasorbetero** [gosimulate/gosimulator#14]
As the title said i am unable to loot pokestops and catch pokemon. This only happened with the update since v1.3.
The app is able to transfer my pokemon so i doubt that the problem is my connection. I can still also access my account in pokemon go (gps turned off) so i guess that means i am not yet banned. Hopefully it was just a setting i missed. Please please help. Thank you very much.

**Comment by gosimulate** [comment]
SOFT BANN ! Read FAQ PLEASE
