### ISSUE TITLE
bot not using great ball or ultra ball

### ISSUE THREAD

**Issue by namecwarrior** [gosimulate/gosimulator#142]
Why is the bot not using great ball or ultra ball? It will just have a message like "something went wrong while catching pokemon" when the regular poke ball runs out. Can you please fix it devs. Btw this is a very good app for us people who are working and have no time to play. Thank you very much.

**Comment by Freshink808** [comment]
Probably something he's working on, im sure he's more focused on making it more undetectable. We just have to be patient.

**Comment by BadSly** [comment]
i think the creator of the bot is working on that.

**Comment by joshie3399** [comment]
Try turn off use berries and set the ev to 100000

On Aug 15, 2016 10:24 PM, "kombatronX" <notifications@github.com> wrote:
>
> Why is the bot not using great ball or ultra ball? It will just have a
message like "something went wrong while catching pokemon" when the regular
poke ball runs out. Can you please fix it devs. Btw this is a very good app
for us people who are working and have no time to play. Thank you very much.

**Comment by gosimulate** [comment]
This issue is already opened, im trying to fix it !
