### ISSUE TITLE
[bug]Doesn't change location to custom route

### ISSUE THREAD

**Issue by Aloha1vn** [gosimulate/gosimulator#143]
i choosed my custom map, however when i pressed start. The map doen't change, and my acccount was soffbanned right away, the red dot on the map olso doesn't change, still in Servo...

**Comment by Freshink808** [comment]
In the new version of gosim the red dot is a little laggy but it still goes to that destination.

**Comment by narutouchi55** [comment]
Visual bug

**Comment by manor7777** [comment]
this should be fixed now
