### ISSUE TITLE
new ban

### ISSUE THREAD

**Issue by mran2ny** [gosimulate/gosimulator#144]
is there anyway to unbanned manually the new soft ban.. i can get loots from pokestop but cant catch pokemon they keep on running..  i tried the 2 throw miss but doesnt work.. please help.. thanks..

**Comment by Freshink808** [comment]
Nope, you just have to wait. The bot removes the normal ban which you spin a poke stop to unbad. This is one of the newer bans that cant manually be removed. You should not use that account for at least 24hrs to avoid perma ban.

**Comment by mran2ny** [comment]
ok thanks..  maybe make a new one while waiting lol..

**Comment by AriesLaCroix** [comment]
Is "failed to get game data" a perma ban?? Just yesterday I was playing fine, battling gyms. Then today this happen..

**Comment by tsalcazar** [comment]
Yup

**Comment by AriesLaCroix** [comment]
Geez, guess I have to create a new account lol

**Comment by Freshink808** [comment]
Gyms might be a way they check your stats or time played, as I've noticed ppl have said the same. I would  avoid gyms unless you've played a few days legit on that account.

**Comment by AriesLaCroix** [comment]
You know Freshink808, u might be right.. Last night I encountered some problems when fighting gyms, I'm getting an error whenever I start the battle.

**Comment by madmappers** [comment]
Shouldn't bot and take gyms anyways

**Comment by Phanthropogenic** [comment]
I can catch but I can't loot. Happend at Level 21.

Any speculations or is this a new soft-ban?

(I did jump countries but usually GoSim fixes that softban. But on what I've seen, GoSim doesn't have the ability to fix Level 15-18 and 20+ softbanned accounts.)

**Comment by gr33nd3v1l** [comment]
#74
