### ISSUE TITLE
[Suggestion] adding supports for items and pokemon removal

### ISSUE THREAD

**Issue by BlinddHeart** [gosimulate/gosimulator#146]
is it possible to add a function to delete/remove/trash items from bags? 
what about manual pokemon transfer and manual Multi pokemon transfer? it would be great because I live in a different place but I'm using NYC location, so when items are full, I have/want to delete things off of it and in order to do so, I have to stop bot and login to PoGo.. thank you

**Comment by gr33nd3v1l** [comment]
#23
