### ISSUE TITLE
Website similar to findlatitudeandlongitude?

### ISSUE THREAD

**Issue by lance2cool** [gosimulate/gosimulator#147]
Hi all, 
Could someone suggest websites similar to "http://www.findlatitudeandlongitude.com/click-lat-lng-list/"? 

I could not access the website for some reasons or maybe the site is down? Can someone confirm this.

Thank you,
More power to GOSIM.

**Comment by Freshink808** [comment]
Site is still up. Are you on mobile or on computer?

**Comment by lance2cool** [comment]
I see. Im using mobile and I can access it yesterday. Looks like a network issue from my end.

Do you knw some similar sites that can record the coordinates of each point you made?

Thanks,

**Comment by Freshink808** [comment]
Most likely, try using a different browser. Good luck bro

**Comment by lance2cool** [comment]
I am able to access the page on PC but how to add points? I tried left and right clicks but nothing happens lmao :D

**Comment by lance2cool** [comment]
Connecting to other network solve the issue.
