### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by ptanhkhoa** [gosimulate/gosimulator#149]
Thanks for your great project, it help me great deal and i have some small suggest that can help you make better program ^^:
1. When the bot can't login due to some reason, it say: "Your account probally banned ..." and when i see it first time, it make me freaking out >.< until some second later, the program connect and run again. Should say " there is some connection issue, or maybe your account banned :D)

2. Last saved position:
When using custom route, if i need to do something on the phone, has to stop the program, and when i restart the bot jumped to the start position, which make it more obvious we are botting, so it should have the last saved position so bot can continue to run again

3. There some option to auto cleanout when the bag is reach some percentage full. And some priority for item to keep, like : Ultraball > Greatball > Pokemonball. And when catching pokemon, it should use  ball depend on enemy CP.

4. In transfer option, it only have to choose between CP and IV, It should be some condition like: below 500 CP and below IV 90/ below 500 CP or below IV 80. 

Beside these things, this it great program so far. Hope you can make it better

**Comment by Freshink808** [comment]
Awesome ideas👍

**Comment by gr33nd3v1l** [comment]
1. > Disable Location data.

2. > Implemented. Being worked on

3. > You're not using it right. This is exactly what it does
