### ISSUE TITLE
Something went wrong while catching / looting

### ISSUE THREAD

**Issue by clix12** [gosimulate/gosimulator#15]
Hope you can help me. I'm using the latest version of the app and uses wifi connection but keeps getting the said error above. Any idea what's the issue? Thanks

**Comment by clix12** [comment]
![tmpdoodle1471056972431](https://cloud.githubusercontent.com/assets/21002319/17641082/8922f288-6144-11e6-9adc-a14e7a2e7315.jpg)
I'm from PH btw..  :)

**Comment by madmappers** [comment]
stopping and restarting usually works for me

**Comment by gr33nd3v1l** [comment]
This is usually due to one of these
-bag full
-no pokeballs
-pokeslots full

**Comment by clix12** [comment]
Thanks! It seems that my bag was full.  :)
