### ISSUE TITLE
Something went wrong while catching pokemons issue

### ISSUE THREAD

**Issue by movement20** [gosimulate/gosimulator#151]
This keep appear to my feed while im using the bot. Pls fix it asap. And Good job on developing the Bot. *Two thumbs up*

**Comment by FriendZoneKing** [comment]
same here.. do you have any theories why this is happening too often?

**Comment by lance2cool** [comment]
Check the following in ur bot app:
1) bot settings/use raspberries on or off? 
- if on, check ur bag for raspberries. 0 raspberries will trigger this error msg. I recommend switching this option off while the dev is working for a fix.
2) Check ur bag for pokeballs. As of now only pokeballs is being use by the bot. Again, the dev is aware and currently working on it.

**Comment by movement20** [comment]
Well this explains it! Thx lance2cool

**Comment by lance2cool** [comment]
Sure thing mate. Happy botting :)

**Comment by FriendZoneKing** [comment]
thanks for your help Lance
