### ISSUE TITLE
ver 1.10.2

### ISSUE THREAD

**Issue by pisangz** [gosimulate/gosimulator#152]
![go](https://cloud.githubusercontent.com/assets/21055909/17693998/49c0b99e-63d4-11e6-9c49-da784d183e7b.jpg)

help me

**Comment by ShedrockN4** [comment]
bad username / password

**Comment by pisangz** [comment]
i try another phone can login, but i use my phone can't login

**Comment by haxor-haxor** [comment]
check your internet connection

**Comment by ShedrockN4** [comment]
ad blocker ? modify hosts in etc ?

**Comment by pisangz** [comment]
i use wifi n mobile data still same problem, i use another phone same wifi n mobile data working good

**Comment by pisangz** [comment]
before this i can use after 13.00 pm GMT start problem

**Comment by gr33nd3v1l** [comment]
If it worked before, and doesn't work now it's an issue on your end.

**Comment by pisangz** [comment]
ok i got banned, i already create new id but still same, i can't login GO Simulator, failed to login. Invalid credentials.

**Comment by gr33nd3v1l** [comment]
IP Ban
