### ISSUE TITLE
Can catch, Can't loot

### ISSUE THREAD

**Issue by Phanthropogenic** [gosimulate/gosimulator#156]
Recently on my main account, I encountered that GoSim cannot fix softban issues of accounts with Levels 15-18 and 20+ (citation needed). I created 5 dummy accounts to test this out and based on what I've seen, Lv. 20+ accounts get the most bans plus doesn't seem that GoSim fixes this softban, so I'm guessing this is some kind of new ban? Since GoSim could still fix softbans on accounts below 15 or so. This could be a new kind of a soft(harsh) ban that does not let you loot pokestops and leaves you suffering for pokeballs.

Is this something that we should be aware of?

**Comment by gr33nd3v1l** [comment]
#74

**Comment by Phanthropogenic** [comment]
"Relog into GoSim to claim rewards"

So relogging in the sim app, not the PoGo app itself, right?

**Comment by ncunkd** [comment]
No, my bag is empty, it just contain 75/350
I opened using pogo app and it can loot pokestop. It just not looting on GoSim

**Comment by ncunkd** [comment]
Sorry, wrong comment location 😅

**Comment by gr33nd3v1l** [comment]
@Phanthropogenic sorry, PoGO app itself, not GoSim. Disable location and you can log in safely

**Comment by Phanthropogenic** [comment]
Checked Journal Logs, it just shows up Pokemons that I caught before and after the Sim tried to fix the Softban (which failed, I napped for 3 hours and it is still stuck in 'Trying to fix it.')

No idea tho.
