### ISSUE TITLE
Map for india plz delhi state

### ISSUE THREAD

**Issue by ykingmj** [gosimulate/gosimulator#158]
Many friends of mine from india are asking for delhi map routes as i told them about the app they were gone crazy as hell as something like bot also consist lol... anyone who could help me out would be appreciated 
As i dont know how to...

**Comment by gr33nd3v1l** [comment]
Please tell me the most popular places with lots of pokemon along which I can make the best route

**Comment by ykingmj** [comment]
Oh thankyou ill tell you wait

**Comment by ykingmj** [comment]
Like delhi hat in delhi,india and india gate, taj mahal and the crowded i know is cannaught place in delhi,india this much i know...

**Comment by ykingmj** [comment]
As for reminder haus khaz in delhi too

**Comment by gr33nd3v1l** [comment]
New Delhi pokestops are very far apart.
This is the first version of New Delhi route over India Gate

[New Delhi_India Gate_India.txt](https://github.com/gosimulate/gosimulator/files/420246/New.Delhi_India.Gate_India.txt)

**Comment by ykingmj** [comment]
Oh thx much... cannaught place and hauskhaz will be more better

**Comment by gr33nd3v1l** [comment]
Haus Kraz, new route
India Gate is bad, no pokemon
[New Delhi_Hauz Khas_India.txt](https://github.com/gosimulate/gosimulator/files/420263/New.Delhi_Hauz.Khas_India.txt)

**Comment by gr33nd3v1l** [comment]
Hauz Khas is good.

**Comment by ykingmj** [comment]
Oh bro thx much can you tell me what app you are using to locate pokemons or pokestop in map...

**Comment by gr33nd3v1l** [comment]
http://www.pokemongomap.info/

I use the simulator to test the route for pokemon

**Comment by ykingmj** [comment]
Oh thx bro
