### ISSUE TITLE
Team Choice

### ISSUE THREAD

**Issue by D3vr04** [gosimulate/gosimulator#159]
Do we have to stop gosim to choose team in order to avoid ban a trigger, or can we run gosim without selecting team and be not trigger a ban? If team is needed at what level to log into Pogo app to choose? And does my location have to be on to get the team selection to activate?
Thanks.

**Comment by gr33nd3v1l** [comment]
Level 5 is needed before GoSim can be used.

**Comment by D3vr04** [comment]
Thanks Greenie!
