### ISSUE TITLE
[Issue] not looting pokestop

### ISSUE THREAD

**Issue by ncunkd** [gosimulate/gosimulator#162]
I start the apps for 3 hours, its catching several pokemon until i run out my poke ball, after that, i never meet pokestop even i change my route. It keep showing error catching pokemon because no poke ball. When i turn off catching pokemon, it just show starting bot success but no pokestop looting. Is it a bug or what?

**Comment by gr33nd3v1l** [comment]
Are you using a proper route? There is no reason for this to happen unless you have been banned

**Comment by ncunkd** [comment]
I use predefined route on santa monica, not using custom route. I opened in PoGo app and it can loot, but still not looting in GoSim app. Just stay in login bot success

**Comment by ncunkd** [comment]
It back to normal now, i just restarting my phone, opening PoGo app, looting 3 pokestop and it back to normal in my GoSim app.
