### ISSUE TITLE
Custom Routes [Malaysia(kuala Lumpur)] 

### ISSUE THREAD

**Issue by sirhon** [gosimulate/gosimulator#164]
Hi...i'm highly recommand make another custom routes at BRICKFILEDS (Mid Valley) area,there have alot of pokestop and pokemon. Thank You!!

**Comment by gr33nd3v1l** [comment]
There is already a route for Kuala Lumpur.

Make one if you want to

**Comment by sirhon** [comment]
How to make new route?Any guide/post about this?
