### ISSUE TITLE
[ROUTE]: New Delhi, India

### ISSUE THREAD

**Issue by gr33nd3v1l** [gosimulate/gosimulator#165]
[New Delhi_Hauz Khas_India.txt](https://github.com/gosimulate/gosimulator/files/420282/New.Delhi_Hauz.Khas_India.txt)

<details> 
  <summary>CLICK HERE TO PREVIEW ROUTE</summary>
   ![capture](https://cloud.githubusercontent.com/assets/3631381/17699589/e2a020a4-63c1-11e6-9ac6-bba8ded62b2e.PNG)
</details>

MACHOP

**Comment by iamarjun** [comment]
what about CP, Delhi..? can you make a route for CP also..? thanks..

**Comment by gr33nd3v1l** [comment]
You can make it yourself. There is already a lot of routes for Asia
