### ISSUE TITLE
[ROUTE]: New York, USA - Central Park

### ISSUE THREAD

**Issue by nengratu** [gosimulate/gosimulator#166]
please made a route for a whole central park new york if u dont mind

**Comment by gr33nd3v1l** [comment]
[New York_Central Park_USA.txt](https://github.com/gosimulate/gosimulator/files/420334/New.York_Central.Park_USA.txt)
![capture](https://cloud.githubusercontent.com/assets/3631381/17700400/dc824086-63c5-11e6-8d8c-5bfe5990c96e.PNG)

**Comment by nengratu** [comment]
thanks a lot .. i will try this

**Comment by gr33nd3v1l** [comment]
I will close this when I add it to Wiki, thanks
