### ISSUE TITLE
[Bug] IV transfer not working 

### ISSUE THREAD

**Issue by skidskidskidiot** [gosimulate/gosimulator#167]
It will transfer about maybe 4 Pokemon at a time, then stop. Meanwhile slowly over time Pokemon with IVs that are qualified to be transferred start to build up in your bag

**Comment by gr33nd3v1l** [comment]
Set your transfertimers differently. It takes a certain amount of time to transfer all pokemon and if your transfertime is lower than that, it will leave a few. It all depends on the buildup of your pokemon

**Comment by gosimulate** [comment]
It will periodicly transfer/evolve/clean. Its set to 5 min
