### ISSUE TITLE
[Route] Santa Monica Boardwalk/Pier

### ISSUE THREAD

**Issue by madmappers** [gosimulate/gosimulator#17]
Yes I know there is a SM map already but I'm proposing that one be replaced with this one I created.  Before botting that was my spoof location and I know the spawns well there.  The map we have misses majority of the dratinis magmars and various others spans because it goes off way to far north for like an hour or so. A more boardwalk driven map will yield more XP and PM 
[Santa Monica Boardwalk.txt](https://github.com/gosimulate/gosimulator/files/416415/Santa.Monica.Boardwalk.txt)

**Comment by gr33nd3v1l** [comment]
Agreed
