### ISSUE TITLE
Bot doesn't do anything 

### ISSUE THREAD

**Issue by clix12** [gosimulate/gosimulator#174]
I'm experiencing issues where the bot seems doesn't do anything and just keeps walking (as per the location tag). It doesn't loot or catch. Could this be an internet connection issues? I'm running at 10mbps with 40sh ping.  (WiFi) I already tried reinstalling the app but no luck.  I didn't jump to different continent.  Normally when bot starts to move  it'll loot or catch within a minute. Any suggestion will be greatly appreciated :)

**Comment by Phanthropogenic** [comment]
Reinstalling, Rebooting, Relogging in would've worked.

**Comment by clix12** [comment]
thanks but still the same :(

**Comment by msilvaz** [comment]
i have the same problem :C
