### ISSUE TITLE
[ROUTE]:Toronto_Ferry_Waterfront_Canada

### ISSUE THREAD

**Issue by Tattooedgod** [gosimulate/gosimulator#175]

**Comment by madmappers** [comment]
Was gonna make this after work lol. Does it touch all the dratini spawns near lake all the way over to like spadina area

**Comment by Tattooedgod** [comment]
its goes from music garden to sherbourne common.

**Comment by gosimulate** [comment]
Create file and put in here instead pasting coordinates please.

**Comment by Tattooedgod** [comment]
sorry will do from now on

**Comment by madmappers** [comment]
Thanks dude for getting me softbanned for jumping not toronto water ferry
DON'T UPLOAD ANYMORE MAPS

**Comment by Tattooedgod** [comment]
I'm sorry for my computer saving the wrong file name for some reason. Sorry for any trouble this caused.
