### ISSUE TITLE
 Bug to Transfer

### ISSUE THREAD

**Issue by brunoyan** [gosimulate/gosimulator#178]
Good day, pokemon screen settings this buggy is not giving the option to set how many CP should transfer . And it's all disorganized , it does not appear the transfer value only to evolve. My phone is a Xiaomi Redmi2 running KitKat .

**Comment by NextLineLife** [comment]
Hold you phone side ways, I should appear.

**Comment by brunoyan** [comment]
Thank you, now appeared . I have not thought about it.

Thank you
