### ISSUE TITLE
Transfer 

### ISSUE THREAD

**Issue by NextLineLife** [gosimulate/gosimulator#180]
The iv setting is working great when you're under the level 22/23. But above that a lot of pokemon are iv 80 or higher. So pokemon bag will get full. 

Same said for transfer under level 400/500 cp. Pokemon bag will get full. 

And it's not organized. 

Maybe add a option to transfer double pokemons with lower cp? 

Current accounts are lvl 25/27/29

**Comment by gosimulate** [comment]
APp will always keep strongest of a akind. There is already option to transfer below cp. Please read readme

**Comment by NextLineLife** [comment]
So if I put delete pokemon under cp level "4000"

It would only delete the one magikarp pokemon cause I got two? 

As you said, "the App will"ALWAYS"  keep the strongest pokemon of its "kind".
