### ISSUE TITLE
Can catch, Can't loot v.2 [Screenshots]

### ISSUE THREAD

**Issue by Phanthropogenic** [gosimulate/gosimulator#181]
![screenshot_2016-08-17-00-36-48](https://cloud.githubusercontent.com/assets/21057769/17707469/22383c96-6413-11e6-832d-c087f287303f.png)
Lv. 21 account.

![screenshot_2016-08-17-00-38-09](https://cloud.githubusercontent.com/assets/21057769/17707485/35d304f2-6413-11e6-92a4-960953394141.png)

Lv. 8 account.

I still have no conclusions to this. @gr33nd3v1l

**Comment by ncunkd** [comment]
Have you open it in PoGo app and clear the item storage?

**Comment by Phanthropogenic** [comment]
Yes indeed I've already done it.

**Comment by gosimulate** [comment]
Soft bann, shall be gone withing 15 mins

**Comment by gr33nd3v1l** [comment]
Dunno what to tell you.. This happens to me only when my bag is full. This issue has been reported in players over 20lvl. Maybe a freeze sort of ban 12-24h

**Comment by Phanthropogenic** [comment]
@gr33nd3v1l
@ncunkd
@gosimulate

Issue's fixed. I had like 340+ revives and had to wipe them completely. It's bullsh** that they had to put this limited storage space.

Thanks again guys!

**Comment by gr33nd3v1l** [comment]
Haha
