### ISSUE TITLE
Rare Pokemon in Route List

### ISSUE THREAD

**Issue by AosPONG** [gosimulate/gosimulator#182]
Somebody Please made list of rare pokemon in every route for newbie(and me)

Thank You

**Comment by Phanthropogenic** [comment]
https://github.com/gosimulate/gosimulator/wiki/ROUTES


NY and NY South - Slowbro, Farfetch'd, Dratini, Growlithe, Magnetron, Exeggutor, Scyther, Snorlax, Magmar, Electabuzz, Hitmonchan (very low chance) High CP Raticate, High CP Pidgeot, High CP Pinsir, Starmie, Arcanine (low-moderate chance)

San Francisco - Big Magikarps, Wartotle, Ivysaur, Charmeleon, Pikachu, Snorlax, Slowbro, Dragonair, Blastoise (extremely low chance, probably low CP too.)

Tokyo - Almost all generic Pokémons, Gyarados (low chance), High CP Venonat


Will probably update

**Comment by biztastic** [comment]
Atlanta - Dratini, Eevee, Exeggcute, Poliwag, Koffing, Mankey, Oddish, Ekans, Tauros, and all the generics and starters

**Comment by juanxito91** [comment]
•Retiro Park (Madrid) - Scyther's nest and common Pokémons.

•Singapour (Indonesia) - Snorlax, Dragonites, Dratinis, Pinsirs, and common Pokémons.

**Comment by juanxito91** [comment]
•Sydney (Australia) - Dratinis, Seals, Kanghaskans, Dragonites and common Pokémons.

•London (UK) - Hypnos, Drowzees and common Pokémons.

**Comment by AosPONG** [comment]
Thank to all

**Comment by AosPONG** [comment]
For me

Downtown Oklahoma - A lot of magikarp
Maxico city central park only - A lot of Growlithe

**Comment by azzrey77** [comment]
WHERE CAN I FIND AN ACCURATE LIST OF NEW NESTS? (As of 8/16/16)
Bulbasaur- Ford Park Bell Gardens
Bulbasaur - Heritage park, Irvine (Park is Huge)
Bulbasaur - Schabarum Regional Park, Rowland Heights
Bulbasaur - Hollenbeck park, Los Angeles 
Charmander - La Brea Tar Pits, Los Angeles
Charmander - Oso Creek Trail, Mission Viejo
Clafairy - Universal Studios, Hollywood
Clafairy - Almansor Park, Alhambra
Eevee - Heritage park, Irvine (Park is Huge)
Electabuzz - La mirada creek park, La mirada 
Electabuzz - Tri City Park, Placentia
Gastly- Garden Grove Park, Garden Grove 
Magnemites - Long Beach Aquarium, Long beach
Magnemites - Santa Monica Pier, Santa Monica
Nidoran - Catalina Island Avalon 
Onyx - JW Marriott, Palm Springs 
Psyduck - Salt Lake Park, Huntington Park
Psyduck - Long Beach Aquarium, Long Beach  
Scyther- Liberty Park, Cerritos
Scyther - Belvedere Park East LA
Squirtle - Peter's Canyon (around the Lake) 
Squirtle - Civic Center Park, Palm Desert
Slowpoke - Long Beach Aquarium, Long Beach
Slowpoke - Alamansor Park Alhambra
Voltorb - Hillcrest Park, Fullerton
Voltorb - Santa Monica Pier
Vulpix - Long Beach Aquarium, Long Beach
-----------------
Spawns/Not a full on Nest....
Abra - Riverside Mt. Rubidoux 
Bellsprout - Memorial park, Santa Ana (Not 100% Confirmed)
Bellsprout - Santa Monica Pier
Bulbasaur - Chino Cypress Trails Park 
Bulbasaur - Rio hondo golf club (Not 100% Confirmed)
Bulbasaur - Schabarum Park across the street from Puente Hills mall (Not 100% Confirmed)
Bulbasaur - Long Beach Aquarium (Starting appearing more recently)
Charmander - Allondra Park, Lawndale
Charmander - Chino Liberty Park 
Charmander - El Dorado Park (West Park/Duck Pond )
Charmander - Stoddard park, Anaheim (Slowing Down)
Charmander - Oak Knoll Park, Cypress
Charmander - Veterans park (Not 100% Confirmed)
Charmander - Ralph B. Clark park. Rosecrans & Beach
Clefairy - Almansor Park Alhambra
Dratini/Dragonair - Long Beach Aquarium (1/hrs ... showing up more)
Dratini/Dragonair - Santa Monica Pier (1-2/hrs)
Dratini - Catalina Island Avalon
Dratini - Newport Pier (1/hr)
Dratini - Dana Point Ocean Institute
Diglet - Grijalva Park Orange (Not 100% Confirmed)
Drowsee - Vincent Lugo Park (Not 100% Confirmed)
Drowzee - Fontana Koehler Park 
Eevee - Barnsdall Park East hollywood
Electabuzz - Aviation Park
Electrode - Windsor park in Santa Ana 
Eevee - Six Flags Magic Mountain
Eevee - Corona Citrus Community Park, Corona
Exeggcute - Pepper tree park in Tustin  (Not 100% Confirmed)
Exeggcute - Santa Ana Zoo
Exeggcute - Lincoln Park Recreation Center LA
Gastly - Jurupa Valley High School,Big Leauge Dreams Ball Park
Gastly - Queen Mary Long Beach  
Ghastly - Highland Aurantia Park (29624 Greenspot Rd) 
Growlithe - Corona Santana Regional Park 
Hitmonchan/Lee - Chino Hills Shop between Ra sushi and Victoria Secret
Horsea - Balboa Park San Diego   
Horsea - Jerome park in Santa Ana
Jigglypuff - Huntington Beach Central Park
Jynx - Santa Monica Pier (Not as frequent)
Jynx - La Palma park (La Palma and Anaheim)
Jynx - Fontana Juniper or Jack Bulik Park 
Jynx - Rancho Cucamonga Victoria Groves Park 
Jynx - UC Irvine near engineering building
Kabuto & Omnyte - Santa Monica Pier
Kabuto & Omnyte - Laguna Beach off Broadway
Kabuto & Omnyte - Newport Restaurant Parking Lot Rowland heights
Kabuto - Huntington Beach Pier
Krabby - Colton Golf Club 
Machops - Downtown Fullerton 
Machops - Downtown Covina (Spawns)
Machops - Mountain Meadows golf course 
Magmar - Bixby Park / Bluff Park Long Beach 
Magmar - Rialto Frisbie Park 
Magnemites - Memorial Park Pasadena
Magnemites - Queen Mary Long Beach   
Magnemites - Long beach Courthouse
Nidoran - Kraemer Park Placentia
Nidoran - Montebello Mall
Nidoran - Belvedere Park East LA
Nidoran - Claremont Claremont Village/City Hall 
Oddish - Chino Ruben S Ayala Park 
Pikachu - Claremont Claremont Village/City Hall 
Pikachu - Historical Main Street - Garden Grove 
Pikachu - Irvine Valley College (Not 100% Confirmed)
Pikachu - Pepper Tree Park & Honda Ya Parking Lot Tustin
Pikachu - Golden Triangle plus lower Beverly Drive Beverly Hills
Pincers - Boisseranc Park (mixed reviews-not 100%)
Pincers - Rialto Jerry Eaves Park 
Poliwag - Moreno Valley Community Park 
Psyduck - San Joaquin Golf Course (Not 100% Confirmed)
Psyduck - Long Beach Aquarium
Scyther - Pacific Palms Resort (Not 100% Confirmed)
Scyther - La Fayette Park 
Scyther - Moreno Valley Golf Course 
Scyther - Descanso Gardens in La Cañada Flintridge
Scyther - Polliwog Park
Scyther - industry hills golf course
Scyther - Fontana Veteran's Memorial Park 
Seel - Eastvale Harada Heritage Park 
Seel - Eastvale McCune Family Park 
Seel - Shatto Recreation Center (Not 100% Confirmed)
Seel - Mar Vista Rec Center
Seel - Riverside Orange Terrace Park 
Shellder- Clara Park Cudahy
Shellder- Corona El Cerrito Sports Park 
Staryou - South Gate Park (Not 100% Confirmed)
Staryou - El Salvador Park Santa Ana (Not 100% Confirmed)
Staryou - Eastvale Orchard Park 
Squirtle - Chino Mountain View Park 
Squirtle - La Puente park next to the church (Not 100% Confirmed)
Squirtle - Quiet canyon in Montebello (Not 100% Confirmed)
Squirtle - Fullerton Arboretum
Squirtle - Montebello Country Club (need to be a member)
Squirtle - Point Fermin Park in San Pedro   
Squirtle - Fullerton Greenbelt
Squirtle  - Veterans park (Not 100% Confirmed)
Taurus - Bixby Park / Bluff Park Long Beach 
Tentacool - Mccaimbridge Park Burbank
Magnemite - Peppertree Park in Tustin
Magmar - Santiago Park Orange (Not 100% Confirmed)
Pikachu - Pepper Tree park in Tustin (Not 100% Confirmed)
Voltorb - Craig Reginal Park Brea
Voltorb - Hillcrest Park Fullerton 
Voltorb - Queen Mary Long Beach
Voltorb - Perris Paragon Park 
----------------- MOVED -----------------

Eevee - Boisseranc Park (May have moved)
----------------- 
Dratini nest - Does not exist
Snorlax - Does not exist
----------------- HOT SPOTS -----------------
Long Beach Aquarium Area & Santa Monica Pier - Caught the following in multiples - Squirtle, Caterpie, Weedle, Pidgey, Rattata, Ekans, Vulpix(lots), Zubat, Oddish, Paras, Venonat, Psyduck(lots), Poliwag (lots), Tentacool (lots), Seel, Shellder, Krabby, Electrode, Horsea (lots), Goldeen (lots), Staryu (lots), Magikarp (lots),Dratini(1-3/hour), Dragonair. Also spotted -- Dragonite (1-2/day), Lapras (1-2/day), Blastoise/Charizard/Venisaur(occasionally)

**Comment by biztastic** [comment]
http://pkmngotrading.com/wiki/Nests
