### ISSUE TITLE
[Help] Route

### ISSUE THREAD

**Issue by djfaizp** [gosimulate/gosimulator#184]
Is there any alternative for getting coordinates like record coordinates from my gps so i will go to pokestops where lure module applied and it will record my route so i can set it on go sim it will make easy to build routes

**Comment by Phanthropogenic** [comment]
@gr33nd3v1l
 
You'd probably set it up manually using the latitude-coordinate app.

**Comment by djfaizp** [comment]
Can i have app url ?

**Comment by tfc20160801** [comment]
Hi, go to google map, then left click on the street starting point, then get the coordinates, then get latitude longitude:


**Format of text file would be:**
Starting Longitude, Starting Latitude, Ending Longitude, Ending Latitude
40.755066,-73.983927,40.753562,-73.985021
40.753562,-73.985021,40.755984,-73.990707

**For example:**
Line 1 is: 
              40.755066,-73.983927 42nd St and 6th Ave, NY (Starting point)
              40.753562,-73.985021 42nd St and 6th Ave, NY (End point)
Line 2 is:
             40.753562,-73.985021 (Starting point this is also the prior ending point)
             40.755984,-73.990707 (New End point)

One you give me this file coordinates, I will then generate 5M steps for all your coordinates, I did some python program to compute for it.

**Comment by gr33nd3v1l** [comment]
That website would be the easiest way, to be honest.

**Comment by djfaizp** [comment]
I know bro but i want to make route from my own walk like i am using xposed pokemon fake gps and i wll go to Sydney and play game in pokemon go and then i will collect all pokestop which are mostly use's lure module and that route i want to record so it will do that thing again and again and i will also get huge pokemons due to lure module now i though you may understand what i want to say

**Comment by gr33nd3v1l** [comment]
I understand you completely but this is still the easier way..
