### ISSUE TITLE
Great/Ultra Ball not being used

### ISSUE THREAD

**Issue by At33k** [gosimulate/gosimulator#185]
Dear Dev,

First of all thanks for such an awesome app.

The issue is the app just uses normal pokeballs to catch pokemons. When the same are finished, its doesnt start using Great/Ultra balls. Request you to find a solution to the same. Using the latest version (1.10.2).

Thanks Once Again !!

**Comment by Phanthropogenic** [comment]
This setting is being tested by the devs for the future updates.
