### ISSUE TITLE
Transfer Question

### ISSUE THREAD

**Issue by azziejay** [gosimulate/gosimulator#187]
In transferring a pokemon, I chose transfer below 100% IV. But it transferred my 97% magikarp and remained the 91% magikarp. What's the basis in transferring a pokemon?

**Comment by clivejo** [comment]
Which CP had the two magikarp?

**Comment by azziejay** [comment]
the 91 has 188cp and the 97 has 128 cp

**Comment by clivejo** [comment]
I've exp the same thing.
Maybe there is always CP priority to avoid your highest CP pkmn go away, waiting for dev to confirm.

**Comment by Campanillo** [comment]
If you setting 100%, all pokemons transfered, because te bot understand all with 100% or less are bad to save

**Comment by ktran1588** [comment]
There was a release note in the first version stating that the app will always keep one strongest CP pokemon.
