### ISSUE TITLE
[BUG] bot wan't stop!

### ISSUE THREAD

**Issue by clivejo** [gosimulate/gosimulator#191]

**Comment by clivejo** [comment]
Last version 10.2. When i press stop the bot didn't stop and keep working. Also when i try to start after a force closing, app say an error about login ("maybe you're banned") if i try again it starts and works well. But won't stop.

**Comment by clivejo** [comment]
More info about it. When i go into bag (with bot started) when i came back into main page the button tell "start". But the bot still continue tonlog activities, catch and loot. If i play start again, show me an error like i'm banned, if i try again everythings works. Also Try all TS in readme.

**Comment by djfaizp** [comment]
When i go Bag it is still loading and loading app freeze at that movement can't go back and need to force stop
