### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by m4yh3m** [gosimulate/gosimulator#193]
Won't let me donate. Will always error. Yes I have the funds.
![capture _2016-08-16-14-22-07](https://cloud.githubusercontent.com/assets/21038696/17716343/25644168-63bd-11e6-8cc1-222c397e8006.png)

**Comment by gosimulate** [comment]
Im checking it

**Comment by gosimulate** [comment]
Can you try sending money as friends and family to vedad.zornic@gmail.com. Please let me know how that ended

**Comment by gosimulate** [comment]
Should be fixed now, please try again

**Comment by mirko2002** [comment]
Is there still a AdFree version for ppls who have donated?

**Comment by gosimulate** [comment]
yea

**Comment by RafaElZgz** [comment]
Same

**Comment by m4yh3m** [comment]
Still the same error.

**Comment by m4yh3m** [comment]
Should Ijust try with echeck?

**Comment by rozbach** [comment]
Cant donate also,its said PayPal does not support donation paymeny from buyers in MY(Malaysia)

**Comment by gosimulate** [comment]
If anyone wants to donate please sent on vedad.zornic@gmail.com untill paypal button is fixes. Money must be sent as family or friends option. Ty

**Comment by mirko2002** [comment]
How to get the Adfree Version for the donating people?
Always asking here in public via issue tracker?

**Comment by gosimulate** [comment]
Also minimum donation for obtanining ad free app is 10 euros. Thank you !

**Comment by mirko2002** [comment]
I've donated already 10€ but how to get the AdFree version. 
On Twitter I got the download link via PM but here it's all public?
So I ask again: How to get the AdFree Versions here on Github when we are donater?

**Comment by gosimulate** [comment]
Contact me over twitter, send paypal proof u paid
