### ISSUE TITLE
New York USA custom routes (pikachu sightings)

### ISSUE THREAD

**Issue by tfc20160801** [gosimulate/gosimulator#194]
If you want new route, give me the coordinates of start and end and I will try to create one for you.

Sample coordinates for plotting:
[MyCoordinates_NYC_BryantPark.txt](https://github.com/gosimulate/gosimulator/files/421388/MyCoordinates_NYC_BryantPark.txt)

You can view the route by pasting the coordinates in here.

[Route_NYC_3M_HudsonRiver_Intrepid.txt](https://github.com/gosimulate/gosimulator/files/421349/Route_NYC_3M_HudsonRiver_Intrepid.txt)
[Route_NYC_5M_BryantPark.txt](https://github.com/gosimulate/gosimulator/files/421351/Route_NYC_5M_BryantPark.txt)
[Route_NYC_5M_CentralPark.txt](https://github.com/gosimulate/gosimulator/files/421354/Route_NYC_5M_CentralPark.txt)
[Route_NYC_5M_HudsonRiver_BatteryPark.txt](https://github.com/gosimulate/gosimulator/files/421350/Route_NYC_5M_HudsonRiver_BatteryPark.txt)
[Route_NYC_5M_HudsonRiver_Intrepid.txt](https://github.com/gosimulate/gosimulator/files/421352/Route_NYC_5M_HudsonRiver_Intrepid.txt)
[Route_NYC_5M_HudsonRiver_Intrepid_NorthToSouth_Water.txt](https://github.com/gosimulate/gosimulator/files/421353/Route_NYC_5M_HudsonRiver_Intrepid_NorthToSouth_Water.txt)
[Route_NYC_5M_HudsonRiver_Intrepid_SouthToNorth_Water.txt](https://github.com/gosimulate/gosimulator/files/421355/Route_NYC_5M_HudsonRiver_Intrepid_SouthToNorth_Water.txt)
[Route_Pickachu_NYC_5M_Bronx_SideViewPark.txt](https://github.com/gosimulate/gosimulator/files/421360/Route_Pickachu_NYC_5M_Bronx_SideViewPark.txt)
[Route_Pickachu_NYC_5M_Bryant_41st42nd6th.txt](https://github.com/gosimulate/gosimulator/files/421356/Route_Pickachu_NYC_5M_Bryant_41st42nd6th.txt)
[Route_Pickachu_NYC_5M_CentralPark_62ndSt5thAve.txt](https://github.com/gosimulate/gosimulator/files/421358/Route_Pickachu_NYC_5M_CentralPark_62ndSt5thAve.txt)
[Route_Pickachu_NYC_5M_CentralPark_CatsRock.txt](https://github.com/gosimulate/gosimulator/files/421357/Route_Pickachu_NYC_5M_CentralPark_CatsRock.txt)
[Route_Pickachu_NYC_5M_CentralPark_LoungingRock.txt](https://github.com/gosimulate/gosimulator/files/421359/Route_Pickachu_NYC_5M_CentralPark_LoungingRock.txt)
[Route_Pickachu_NYC_5M_CentralPark_ThePond.txt](https://github.com/gosimulate/gosimulator/files/421361/Route_Pickachu_NYC_5M_CentralPark_ThePond.txt)
[Route_Pickachu_NYC_5M_CentralPark_ThePond2.txt](https://github.com/gosimulate/gosimulator/files/421362/Route_Pickachu_NYC_5M_CentralPark_ThePond2.txt)
[Route_Pickachu_NYC_5M_CentralPark_W59th7thAve.txt](https://github.com/gosimulate/gosimulator/files/421363/Route_Pickachu_NYC_5M_CentralPark_W59th7thAve.txt)
[Route_Pickachu_NYC_5M_CentralParkEast_E89thSt90thBirdiePath.txt](https://github.com/gosimulate/gosimulator/files/421364/Route_Pickachu_NYC_5M_CentralParkEast_E89thSt90thBirdiePath.txt)
[Route_Pickachu_NYC_5M_CentralParkWest_ThePondNearCenterDrive.txt](https://github.com/gosimulate/gosimulator/files/421365/Route_Pickachu_NYC_5M_CentralParkWest_ThePondNearCenterDrive.txt)
[Route_Pickachu_NYC_5M_CentralParkWest_W62rdSt.txt](https://github.com/gosimulate/gosimulator/files/421366/Route_Pickachu_NYC_5M_CentralParkWest_W62rdSt.txt)
[Route_Pickachu_NYC_5M_CentralParkWest_W64thSt.txt](https://github.com/gosimulate/gosimulator/files/421368/Route_Pickachu_NYC_5M_CentralParkWest_W64thSt.txt)
[Route_Pickachu_NYC_5M_CentralParkWest_W106thSt.txt](https://github.com/gosimulate/gosimulator/files/421376/Route_Pickachu_NYC_5M_CentralParkWest_W106thSt.txt)
[Route_Pickachu_NYC_5M_FDRDrive_99thSt.txt](https://github.com/gosimulate/gosimulator/files/421367/Route_Pickachu_NYC_5M_FDRDrive_99thSt.txt)
[Route_Pickachu_NYC_5M_Flushing_NYHallOfScience.txt](https://github.com/gosimulate/gosimulator/files/421369/Route_Pickachu_NYC_5M_Flushing_NYHallOfScience.txt)
[Route_Pickachu_NYC_5M_Midtown_47th48thStMadisonAve.txt](https://github.com/gosimulate/gosimulator/files/421370/Route_Pickachu_NYC_5M_Midtown_47th48thStMadisonAve.txt)
[Route_Pickachu_NYC_5M_Midtown_49thSt7thAve.txt](https://github.com/gosimulate/gosimulator/files/421371/Route_Pickachu_NYC_5M_Midtown_49thSt7thAve.txt)
[Route_Pickachu_NYC_5M_Midtown_51stSt6thAve.txt](https://github.com/gosimulate/gosimulator/files/421372/Route_Pickachu_NYC_5M_Midtown_51stSt6thAve.txt)
[Route_Pickachu_NYC_5M_Midtown_E50th51stparkAveLexAve.txt](https://github.com/gosimulate/gosimulator/files/421373/Route_Pickachu_NYC_5M_Midtown_E50th51stparkAveLexAve.txt)
[Route_Pickachu_NYC_5M_Midtown_EW_ParkAveMadisonAve47th48thSt.txt](https://github.com/gosimulate/gosimulator/files/421375/Route_Pickachu_NYC_5M_Midtown_EW_ParkAveMadisonAve47th48thSt.txt)
[Route_Pickachu_NYC_5M_Uptown_91st90thSt2nd3rd.txt](https://github.com/gosimulate/gosimulator/files/421374/Route_Pickachu_NYC_5M_Uptown_91st90thSt2nd3rd.txt)
[Route_Pickachu_NYC_5M_Uptown_112thStMadison.txt](https://github.com/gosimulate/gosimulator/files/421377/Route_Pickachu_NYC_5M_Uptown_112thStMadison.txt)
[Route_Pickachu_NYC_5M_Uptown_120thSt5thAve.txt](https://github.com/gosimulate/gosimulator/files/421378/Route_Pickachu_NYC_5M_Uptown_120thSt5thAve.txt)
[Route_Pickachu_NYC_5M_Uptown_126thStPark.txt](https://github.com/gosimulate/gosimulator/files/421380/Route_Pickachu_NYC_5M_Uptown_126thStPark.txt)
[Route_Pickachu_NYC_5M_Uptown_HenryHudsonParkway161stSt.txt](https://github.com/gosimulate/gosimulator/files/421381/Route_Pickachu_NYC_5M_Uptown_HenryHudsonParkway161stSt.txt)
[Route_Pickachu_NYC_5M_Uptown_W68thStBroadway.txt](https://github.com/gosimulate/gosimulator/files/421379/Route_Pickachu_NYC_5M_Uptown_W68thStBroadway.txt)
[Route_Pickachu_NYC_5M_Uptown_W99thStBroadway.txt](https://github.com/gosimulate/gosimulator/files/421382/Route_Pickachu_NYC_5M_Uptown_W99thStBroadway.txt)
[Route_Pickachu_NYC_5M_Uptown_W126thSt.txt](https://github.com/gosimulate/gosimulator/files/421383/Route_Pickachu_NYC_5M_Uptown_W126thSt.txt)
[RouteNest_NYC_5M_CentralPark_Charmander.txt](https://github.com/gosimulate/gosimulator/files/421384/RouteNest_NYC_5M_CentralPark_Charmander.txt)
[RouteNest_NYC_5M_Intrepid_Dragonite.txt](https://github.com/gosimulate/gosimulator/files/421385/RouteNest_NYC_5M_Intrepid_Dragonite.txt)
[Route_MidTown_NYC_5M_MidTown.txt](https://github.com/gosimulate/gosimulator/files/421386/Route_MidTown_NYC_5M_MidTown.txt)

**Comment by Darkshinra** [comment]
are these all pikachu routes? or sightings because 
this one is RouteNest_NYC_5M_Intrepid_Dragonite.txt it has a dragonite text lol so i was wondering if it's dragonite? sightings

**Comment by tfc20160801** [comment]
Lol! Yes, those ones with Pikachu are the the ones I have seen Pikachu spawn at a given time.

**Comment by officiallytook** [comment]
well Nvm the other question, lol, maybe you could help me with south gate park and this gold course with bulbasaurs in Los angeles

**Comment by BlinddHeart** [comment]
so far after 2 hours, still no charmander.. 😂😂

**Comment by crzcrw** [comment]
Make route circling inside the american museum of natural history's complex for charmander

**Comment by tfc20160801** [comment]
Please go to https://github.com/gosimulate/gosimulator/issues/195. Follow the instructions and send me the coordinates and I will plot the path for you.

**Comment by Darkshinra** [comment]
how come im level 24 but im still capturing 400 cp or below!
