### ISSUE TITLE
Best place to catch pokemon? high CP

### ISSUE THREAD

**Issue by Darkshinra** [gosimulate/gosimulator#196]
trying to collect good high CP pokemon and rare as well what's the best route?

**Comment by tfc20160801** [comment]
Central Park NY would be really good, 40.764755, -73.973046. You will get high CP ones you level up.

**Comment by Riceball0831** [comment]
Is NYC time square fine

**Comment by narutouchi55** [comment]
Bulbourne Lillydale

**Comment by kingkai808** [comment]
#263
