### ISSUE TITLE
Help me please. 

### ISSUE THREAD

**Issue by Raichuv** [gosimulate/gosimulator#200]
before my account is normaly, i can catch, looting, battle gym. i not use bot again. But in 30 min later  i can't login to my account.
I get message "Failed to get game data from server"
How to fix this?

Sorry if i bad english.

**Comment by lance2cool** [comment]
Looks like you have been banned. Got the same message on my first account.

**Comment by NextLineLife** [comment]
Did you do anything suspicious?

**Comment by Raichuv** [comment]
I just stoping use bot at the night, and tomorrow i go login in official app. First i just get softban. In 3hours softban is deleted. Then I catch 2 pokemon from official app. I go offline and in 30 min i go online again.
Boom, i get the message.

**Comment by madmappers** [comment]
Yup you've been banned what level,where youb

**Comment by madmappers** [comment]
My two bottled account are banned while my spoof account is still alive level 25

**Comment by Raichuv** [comment]
OMG i got banned my level is 25 -,-

**Comment by Raichuv** [comment]
But i am try make new account and i use the same nickname. But nickname is already.

**Comment by madmappers** [comment]
Ya don't  bot past 20 especially in under like a week spread bot time out an hr here and there.  Level 25 in under a month  set bot  to target Rares and legendary instead of everything so doesn't accumulate too,much xp

**Comment by lance2cool** [comment]
I did the same and got the same result. I cant use the same nickname. However, I made 3 accounts. 1st account gets banned, same message from yours. Then I tried changing the name of my 2nd account and change also my 3rd account name to my 2nd account previous name but got the result of "the nickname is not available". Looks like, we couldnt identify the banned account existence thru nickname.

**Comment by Raichuv** [comment]
https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308

I will try this..

**Comment by matkodah** [comment]
i also got the same message at lvl 28.... so sad.. my new acc now at lvl 16.

**Comment by Freshink808** [comment]
If you live in the us i would bot in a different country, Vise versa. I have 3 accounts past 25 and no ban or soft bans. Idk what all you guys keep doing to get banned so much. Make sure you read the read me section. Use common sense.

**Comment by Freshink808** [comment]
Wouldn't*

**Comment by gosimulate** [comment]
Might be banned, be careful. Use latest version
