### ISSUE TITLE
I got an email saying somebody changed my password. Is it Perma-ban?

### ISSUE THREAD

**Issue by incubuster** [gosimulate/gosimulator#201]
What does it mean? Is it permaban?

**Comment by BlinddHeart** [comment]
probably someone hacked ur account and changed it. make sure ur password is strong and secure. try changing it again and make a stronger one using symbols, letters, capital letters, and numbers

**Comment by BadSly** [comment]
i think your account is hacked

**Comment by BlinddHeart** [comment]
what he said above^ permanent ban won't change your password. there's no point even if they changed it. you're banned either way 😂

**Comment by incubuster** [comment]
hahah you are right. thanks anyways.

**Comment by BlinddHeart** [comment]
nm, glad we can help

**Comment by BlinddHeart** [comment]
do not underestimate hackers my friend. never.
