### ISSUE TITLE
[ROUTE]:Franklin_NH_USA

### ISSUE THREAD

**Issue by Tattooedgod** [gosimulate/gosimulator#203]
[Franklin_NH_USA.txt](https://github.com/gosimulate/gosimulator/files/421663/Franklin_NH_USA.txt)

**Comment by Tattooedgod** [comment]
![franklin_nh_usa](https://cloud.githubusercontent.com/assets/3638377/17723268/c1d0b9d4-6406-11e6-9ab5-d344ce18f020.png)

**Comment by mran2ny** [comment]
whats on this route?

**Comment by Adonist** [comment]
how did you take a photo of the route like that?

**Comment by Tattooedgod** [comment]
http://www.darrinward.com/lat-long/?id=2178602

**Comment by Tattooedgod** [comment]
before I use any routes from here I double check before hand. This site allows you to paste all info from text then it shows on map

**Comment by Adonist** [comment]
That's great! Thank you for that mate!

**Comment by gedoyz** [comment]
How to create route easily bro?
