### ISSUE TITLE
Where to get specific RARES?

### ISSUE THREAD

**Issue by paulination** [gosimulate/gosimulator#204]
Hi, just started trying this out. I really want a Charizard more than anything. I've tried most routes so far, but always low yield for Charmander. Any suggestions?

**Comment by clivejo** [comment]
Try route Parco Sempione Milano italy. Is a custom route shared on this forum. There is a lot of charmander. I mean a lot.

**Comment by paulination** [comment]
Alright. Will check it out. Thanks!

**Comment by crzcrw** [comment]
NY have all kinds of pokemon, but some are really few. In my experience, NY's American Museum of Natural History almost, but not always have 1 charmander in inside its complex. Just set the marker there, and set the step minimum, and long time for move to next step

**Comment by Darkshinra** [comment]
@crzcrw how come im level 24 and im still catching 400 or below cp? over and over again

**Comment by crzcrw** [comment]
@Darkshinra I think our level is to determine the upper limit of pokemon's cp that we will encounter, however the lower limit is all the same for all level. I'm level 25 and yesterday I got a dragonite with 100 something cp. x.x

**Comment by narutouchi55** [comment]
See #196
