### ISSUE TITLE
failed to login, you are probably banned

### ISSUE THREAD

**Issue by x1v16** [gosimulate/gosimulator#208]
I got this message the first time I used version 1.10.2. I wasn't actually banned at all. Scared me to death at first, lol.

**Comment by gosimulate** [comment]
It doesnt mean u are banned, but u are probably banned. Please try again 💃

**Comment by Darkshinra** [comment]
u just need to spam it, it happens to me as well

@gosimulate sir, how come im level 24 but im still catching cp 400 or below
