### ISSUE TITLE
ROUTES FOR RARE POKEMONS

### ISSUE THREAD

**Issue by gengchu** [gosimulate/gosimulator#212]
Sorry if I am going to post this stupid question again, I have read that I only need the .txt file and just save it to my sdCard then suddenly it will just work?
**Also please tell where on earth has an abundant supply of fire and ghost pokemons please!!

**Comment by BadSly** [comment]
if you saved that .txt file custom route, go to Go Simulator > Bot Settings > Use Custom Route then select the custom route you downloaded

**Comment by gengchu** [comment]
I saw it already. I was using 1.7.1 back then but now 1.10.2 :D
