### ISSUE TITLE
Custom Route On Bluestacks

### ISSUE THREAD

**Issue by mrkanor** [gosimulate/gosimulator#216]
Hello can someone teach me how to add custom route using bluestacks? thanks!

**Comment by benyaj** [comment]
download a file explorer, for example, ES Explorer. Open up the app, then open up the folder you wish to save the routes to, then click and drag the route from windows and drop it into the open folder in bluestacks

**Comment by tfc20160801** [comment]
Hi mrkanor, please see https://github.com/gosimulate/gosimulator/issues/195. Follow the instructions and send me the coordinates and I will plot it for you.

**Comment by mrkanor** [comment]
thank you guys!
