### ISSUE TITLE
WTF BANNED

### ISSUE THREAD

**Issue by mran2ny** [gosimulate/gosimulator#219]
![screenshot_20160817-234931](https://cloud.githubusercontent.com/assets/21026846/17738637/76af3e24-64d5-11e6-9778-bdf45ab72b19.png)

**Comment by scissors14** [comment]
I get that warning. Just retry

**Comment by mran2ny** [comment]
retry the gosi or on pogo apps?

**Comment by gr33nd3v1l** [comment]
Restart gosim and retry

**Comment by ykingmj** [comment]
I got the same error with new account at lvl14 but i retry it works maybe its a glitch....
