### ISSUE TITLE
[ROUTE]: Brasil

### ISSUE THREAD

**Issue by gr33nd3v1l** [gosimulate/gosimulator#22]
[Santos_Quebra-Mar_Brasil.txt](https://github.com/gosimulate/gosimulator/files/416552/Santos_Quebra-Mar_Brasil.txt)

by @wesjj

**Comment by gosimulate** [comment]
Pleasre rename route to something like : city_place_brazil.txt

**Comment by gr33nd3v1l** [comment]
Alright, lemme first check where this actually goes in that case:)
