### ISSUE TITLE
1.10.2 "Something went wrong while catching pokemons"

### ISSUE THREAD

**Issue by surfingbirds** [gosimulate/gosimulator#220]
lvl 26 but I'm not banned. Yet. Not looking forward to but 
1. Is this still about not having a Poke Ball in the bag? 
-I kept deleting Poke Balls cause I'm getting heaps of Great Balls & Ultra Balls so I thought I could just use those.
2. If it's because my pokemon bag is full, it's not. I've checked it still have 50 slots.

**Comment by mran2ny** [comment]
bot only use poke balls..

**Comment by surfingbirds** [comment]
Aye. Thanks
