### ISSUE TITLE
Seconds config

### ISSUE THREAD

**Issue by madlibquas** [gosimulate/gosimulator#222]
What better setting for bot (seconds ) to be fast, but not to ban ?

**Comment by Darkshinra** [comment]
8 seconds and put it on slow

**Comment by domdonit** [comment]
The new version doesn't have the speed option anymore. What would be the new one? The "one step in metters? How should i set it? i didn't understand the configs

**Comment by gosimulate** [comment]
Speed is changed to multiple options so you can choose ur own
