### ISSUE TITLE
translate language 

### ISSUE THREAD

**Issue by azzrey77** [gosimulate/gosimulator#226]
<Sumber>
    <Rentetan name = "APP_NAME"> GO Simulator </ rentetan>
    <Rentetan name = "title_activity_maps"> Peta </ ​​rentetan>
    <Nama string = "action_settings"> Tetapan </ rentetan>
    <Nama string = "title_activity_settings"> Tetapan </ rentetan>
    <Nama string = "logo"> Logo </ rentetan>
    <Nama string = "logo1"> logo </ rentetan>

    <Nama string = "pref_header_general"> Maklumat Login </ rentetan>

    <Nama string = "login_info_username_tittle"> Nama pengguna </ rentetan>

    <Nama string = "pref_header_settings"> Tetapan Bot </ rentetan>
    <Nama rentetan-array = "predefine_file_walks">
        <Item> Sarajevo </ item>
        <Item> Melburne </ item>
        <Item> Melburne Lillydale Lake </ item>
        <Item> New York </ item>
        <Item> Boston </ item>
        <Item> San Francisco </ item>
        <Item> New York Selatan </ item>
        <Item> Santa Monica </ item>
        <Item> Bandar Raya Mexico </ item>
        <Item> Dusseldorf </ item>
        <Item> Atlanta Downtown </ item>
        <Item> Columbus Ohio Arena </ item>
        <Item> Downtown Oklahoma </ item>
        <Item> Ilminster </ item>
        <Item> Iloilo City </ item>
        <Item> Koper Izola </ item>
        <Item> Dengan ini Disneyland </ item>
        <Item> Bontang Cibodas negeri indonesia </ item>
        <Item> London </ item>
        <Item> Washington DC </ item>
        <Item> Manhattan Rockefella Pusat NY </ item>
        <Item> Mexico City Central Park Hanya </ item>
        <Item> Mexico City Deer Park </ item>
        <Item> Pittsburgh Thepoint Pa Amerika Syarikat </ item>
        <Item> St Paul Downtown MN Amerika Syarikat </ item>
        <Item> Stockport England </ item>
        <Item> Denver Zoo Colorado Amerika Syarikat </ item>
        <Item> Dusseldorf Pokemonbridge Jerman </ item>
        <Item> Marikina River Filipina </ item>
        <Item> Santa Monica Boardwalk </ item>
        <Item> Santos Quebra Mar Brasil </ item>
        <Item> London Semua Kawasan </ item>
        <Item> Toronto Downtown </ item>
        <Item> Victoria Waterfront BC Canada </ item>
    </ Tali-array>

    <Nama string = "login_info_password_tittle"> Kata Laluan </ rentetan>
    <Nama string = "pref_predefined_walk_title"> Laluan </ rentetan>
    <Rentetan name = "use_predefined_routes_checkbox"> Gunakan laluan yang telah ditetapkan </ rentetan>
    <Nama string = "pref_speed_title"> Speed ​​</ rentetan>
    <Nama string = "transfer_checkbox"> Pokemons Transfer </ rentetan>
    <Nama string = "evolve_checkbox"> Evolve Pokemons </ rentetan>
    <Nama string = "evolve_over_cp"> Evolve Pokemons lebih CP </ rentetan>
    <Nama string = "evolve_pokemons_description"> <! [CDATA [Evolve Pokemons yang mempunyai CP> = nilai kemudian setted]]> </ rentetan>
    <Nama string = "transfer_over_cp"> Pokemons Pemindahan di bawah CP </ rentetan>
    <Nama string = "transfer_pokemons_description"> <! [CDATA [Pokemons Transfer yang mempunyai CP <kemudian menetapkan value]]> </ rentetan>
    <Nama string = "hatchEggs"> telur Hatch </ rentetan>
    <Nama string = "cleanUselessItems"> ramuan Bersih dan menghidupkan </ rentetan>
    <Nama string = "isGoogleAuth"> Adakah akaun google? </ Rentetan>
    <Rentetan name = "poke_list"> Pokemon Tetapan </ rentetan>
    <Nama string = "useLuckyEggPlaceholder"> Gunakan telur bertuah sebelum Evolve </ rentetan>
    <Nama string = "beg"> Bag </ rentetan>
    <Nama string = "useCustomRoute"> Laluan Penggunaan adat </ rentetan>
    <Nama string = "thx_for_support"> Terima kasih kerana menyokong saya, membawa ciri-ciri baru pada masa depan! </ Rentetan>
    <Nama string = "close_adblock_message"> Tutup menambah blocker dan mula pergi sim. </ Rentetan>
    <Nama string = "bermula"> Mula </ rentetan>
    <Nama string = "berhenti"> Menghentikan </ rentetan>
    <Nama string = "bermula"> Bermula </ rentetan>
    <Nama string = "close_adblock"> Tutup menambah blocker dan mula pergi sim. </ Rentetan>
    <Nama string = "missing_username"> nama pengguna Hilang </ rentetan>
    <Rentetan name = "missing_password"> kata laluan Hilang </ rentetan>
    <Nama string = "use_predefined_route_error"> Gunakan laluan yang telah ditetapkan dipilih tetapi tiada laluan dipilih. </ Rentetan>
    <Nama string = "use_custom_route_error"> Gunakan laluan adat dipilih tetapi tiada fail dipilih. </ Rentetan>
    <Nama string = "bag_warning_message"> Simulator perlu berjalan untuk melihat beg </ rentetan>
    <Nama string = "berhenti"> Stop </ rentetan>
    <Rentetan name = "PLAYER_NAME"> "Player:" </ rentetan>
    <Nama string = "PLAYER_LEVEL"> "Level:" </ rentetan>
    <Nama string = "pengalaman"> "Pengalaman:" </ rentetan>
    <Rentetan name = "loading_pokemons"> Loading Pokemons, sila tunggu </ rentetan>
    <Nama string = "failed_to_load_pokemons"> Gagal untuk memuatkan Pokemons </ rentetan>
    <Nama string = "invalid_transfer_value"> Nilai tidak sah untuk bidang pemindahan. Julat mesti (0-100) </ rentetan>
    <Nama string = "invalid_evolev_value"> Nilai tidak sah untuk bidang Evolve. Julat mesti (0-100) </ rentetan>
    <Nama string = "transfer_below_iv"> Pemindahan di bawah IV </ rentetan>
    <Nama string = "transfer_below_cp"> Pemindahan di bawah CP </ rentetan>
    <Nama string = "evolve_over_iv"> Evolve lebih IV </ rentetan>
    <Nama string = "evolve_over_cp_sps"> Evolve lebih CP </ rentetan>
    <Nama string = "use_custm_route_fp"> "Gunakan laluan adat" </ rentetan>
    <Nama string = "failed_to_initialize_bot"> Gagal untuk memulakan bot, berhenti </ rentetan>
    <Rentetan name = "fw_turn_arround"> ​​Baca coordiante lepas daripada fail, menjadikan persekitaran diseluruh. </ Rentetan>
    <Nama string = "error_while_walking"> sesuatu yang tidak kena ketika berjalan </ rentetan>
    <Nama string = "internet_error"> Ralat berlaku semasa menghubungi pelayan. Semak internet anda. </ Rentetan>
    <Rentetan name = "unknown_error"> Ralat tidak diketahui berlaku, menunggu 10 saat untuk terus </ rentetan>
    <Nama string = "critical_error"> Ralat kritikal berlaku. Loggining off. Plese tekan butang start lagi. </ Rentetan>
    <Nama string = "logged_in"> Berjaya log masuk. Bermula bot </ rentetan>
    <Nama string = "invalid_cred"> Gagal log kelayakan in.Invalid. </ Rentetan>
    <Rentetan name = "server_is_having_issues"> Gagal log masuk. Server mempunyai isu-isu. </ Rentetan>
    <Nama string = "probable_bann_message"> Gagal masuk. Akaun anda mungkin diharamkan. Sila cuba dengan aplikasi rasmi. </ Rentetan>
    <Nama string = "transfer_error"> Ralat berlaku semasa memindahkan Pokemons, ponteng. </ Rentetan>
    <Nama string = "evolve_error"> Ralat berlaku semasa berkembang Pokemons, ponteng </ rentetan>
    <Nama string = "hatch_eggs_error"> Ralat occuered manakala penetasan telur, ponteng </ rentetan>
    <Nama string = "clean_items_error"> Ralat berlaku semasa pembersihan barangan. Ponteng </ rentetan>
    <Rentetan name = "used_lucky_egg"> Digunakan telur bertuah sebelum berkembang. </ Rentetan>
    <Nama string = "evolved_pokemon"> "pokemon Evolved" </ rentetan>
    <Nama string = "dengan"> "dengan" </ rentetan>
    <Nama string = "dan"> "dan" </ rentetan>
    <Nama string = "evolved_to"> "Evolved untuk" </ rentetan>
    <Nama string = "pemindahan"> Pindah </ rentetan>
    <Nama string = "catch_error"> Ada masalah berlaku semasa menangkap Pokemons </ rentetan>
    <Nama string = "loot_error"> Ada masalah berlaku semasa rompakan pokestops </ rentetan>
    <Nama string = "failed_to_catch_message"> Gagal menangkap pokemon </ rentetan>
    <Nama string = "no_pokeballs_left"> No pokeballs kiri. </ Rentetan>
    <Nama string = "catch_pokemon"> Catch </ rentetan>
    <Nama string = "loot_message"> Loot pokestop </ rentetan>
    <Rentetan name = "awarded_items"> barangan Dianugerahkan </ rentetan>
    <Nama string = "softban_detected"> Dikesan larangan lembut mungkin, cuba untuk memperbaikinya ... </ rentetan>
    <Rentetan name = "softban_removed"> Dikeluarkan Bann lembut, congratz:) </ rentetan>
    <Nama string = "softban_error"> Ada masalah berlaku semasa membuang Bann lembut </ rentetan>
    <Nama string = "service_critical_error"> Gagal untuk memulakan perkhidmatan. Sila mulakan semula aplikasi. </ Rentetan>
    <Nama string = "pokemon_name"> nama Pokemon </ rentetan>
    <Rentetan name = "pokemon"> Pokemon </ rentetan>
</ Sumber>

**Comment by gosimulate** [comment]
U made it wrong,  please do it this way:

<string name="DO_NOT_TRANLATE_THIS_VALUE"> {TRANSLATE THIS ONE} </string>
