### ISSUE TITLE
How to donate

### ISSUE THREAD

**Issue by SpiitDaico** [gosimulate/gosimulator#230]

**Comment by gosimulate** [comment]
paypal

**Comment by SpiitDaico** [comment]
Can i get detail

**Comment by gosimulate** [comment]
You can donate on my friends paypal account vedad.zornic@gmail.com Min ammout to get adfree apk is 10 euros. Thx

**Comment by SpiitDaico** [comment]
Can get perfect version and letest version on email?

**Comment by gosimulate** [comment]
when u donate I'll check, u will get it

**Comment by gosimulate** [comment]
Donation must be send as family and friends option

**Comment by SpiitDaico** [comment]
Orite.. i will donate for u..

**Comment by SpiitDaico** [comment]
I will inform u..
