### ISSUE TITLE
banned 2weeks account lvl 26

### ISSUE THREAD

**Issue by drewranger** [gosimulate/gosimulator#235]
sad to say i got banned

idont know if the bot or the flying gps lol

any safe tips for method ?

**Comment by BlinddHeart** [comment]
I live like 45 mins away from NYC's central park. so before I did anything, I usually look up how long it'll take me from wher3 I live to Central Park. and I wait like about 5 minutes + the traveling time. then I start the bot. it works for me. I have 2 acc, Main is 26 and Sub is 23.

**Comment by D3vr04** [comment]
Blind, 
Do you run a predefined route? If yes for how long each time?

**Comment by narutouchi55** [comment]
Dont use the bot for longer than 12 hours.
