### ISSUE TITLE
Translated to HINDI

### ISSUE THREAD

**Issue by Anand094** [gosimulate/gosimulator#238]
<resources>
    <string name="app_name">GO सिम्यलेशन</string>
    <string name="title_activity_maps">नक्शे/string>
    <string name="action_settings">सेटिंग्स</string>
    <string name="title_activity_settings">सेटिंग्स</string>
    <string name="logo">प्रतीक चिन्ह</string>
    <string name="logo1">प्रतीक चिन्ह</string>

    <string name="pref_header_general">लॉगिन जानकारी</string>

    <string name="login_info_username_tittle">उपयोगकर्ता नाम</string>

    <string name="pref_header_settings">बॉट सेटिंग्स</string>
    <string-array name="predefine_file_walks">
        <item>Sarajevo</item>
        <item>Melburne</item>
        <item>Melburne Lillydale Lake</item>
        <item>New York</item>
        <item>Boston</item>
        <item>San Francisco</item>
        <item>New York South</item>
        <item>Santa Monica</item>
        <item>Mexico City</item>
        <item>Dusseldorf</item>
        <item>Atlanta Downtown</item>
        <item>Columbus Ohio Arena</item>
        <item>Downtown Oklahoma</item>
        <item>Ilminster</item>
        <item>Iloilo City</item>
        <item>Koper Izola</item>
        <item>Hereby Disneyland</item>
        <item>Bontang cibodas state indonesia</item>
        <item>London</item>
        <item>Washington DC</item>
        <item>Manhattan Rockefella Center NY</item>
        <item>Mexico City Central Park Only</item>
        <item>Mexico City Deer Park</item>
        <item>Pittsburgh Thepoint Pa USA</item>
        <item>St Paul Downtown MN USA</item>
        <item>Stockport England</item>
        <item>Denver Zoo Colorado USA</item>
        <item>Dusseldorf Pokemonbridge Germany</item>
        <item>Marikina River Phillippines</item>
        <item>Santa Monica Boardwalk</item>
        <item>Santos Quebra Mar Brasil</item>
        <item>London All Areas</item>
        <item>Toronto Downtown</item>
        <item>Victoria Waterfront BC Canada</item>
    </string-array>

    <string name="login_info_password_tittle">पासवर्ड</string>
    <string name="pref_predefined_walk_title">मार्गों</string>
    <string name="use_predefined_routes_checkbox">पूर्वनिर्धारित मार्गों का उपयोग</string>
    <string name="pref_speed_title">गति</string>
    <string name="transfer_checkbox">हस्तांतरण पॉकेमोन</string>
    <string name="evolve_checkbox">पॉकेमोन को विकसित करना</string>
    <string name="evolve_over_cp">इस C.P के उपर विकसित करे</string>
    <string name="evolve_pokemons_description"><![CDATA[Evolve pokemons that have CP >= then setted value]]></string>
    <string name="transfer_over_cp">इस C.P के उपर हस्तांतरण करे</string>
    <string name="transfer_pokemons_description"><![CDATA[Transfer pokemons that have CP < then set value]]></string>
    <string name="hatchEggs">अंडे सेना</string>
    <string name="cleanUselessItems">औषधि और जान को निकले</string>
    <string name="isGoogleAuth">क्या ई गूगले अकाउंट है ?</string>
    <string name="poke_list">पॉकेमोन सेटिंग्स</string>
    <string name="useLuckyEggPlaceholder">विकसित होने से पहले भाग्यशाली अंडे का उपयोग</string>
    <string name="Bag">बैग</string>
    <string name="useCustomRoute">कस्टम मार्ग का प्रयोग करें</string>
    <string name="thx_for_support">मुझे समर्थन भविष्य में नई सुविधाओं लाने के लिए धन्यवाद !</string>
    <string name="close_adblock_message">बंद अवरोधक जोड़ने और सिम जाना शुरू.</string>
    <string name="start">प्रारंभ</string>
    <string name="stopping">रोक</string>
    <string name="starting">शुरुआत में</string>
    <string name="close_adblock">बंद अवरोधक जोड़ने और सिम जाना शुरू.</string>
    <string name="missing_username">लापता उपयोगकर्ता नाम</string>
    <string name="missing_password">गुम पासवर्ड</string>
    <string name="use_predefined_route_error">उपयोग पूर्वनिर्धारित मार्ग का चयन किया है , लेकिन कोई मार्ग चुना जाता है.</string>
    <string name="use_custom_route_error">उपयोग कस्टम मार्ग का चयन किया है , लेकिन कोई फ़ाइल चुना जाता है.</string>
    <string name="bag_warning_message">सिम्युलेटर आदेश बैग देखने के लिए चल रहा हो गया है</string>
    <string name="stop">रुकें</string>
    <string name="player_name">"खिलाड़ी: "</string>
    <string name="player_level">"स्तर: "</string>
    <string name="experience">"अनुभव: "</string>
    <string name="loading_pokemons">लोड हो रहा है pokemons , कृपया प्रतीक्षा करें</string>
    <string name="failed_to_load_pokemons">pokemons लोड करने में असफल</string>
    <string name="invalid_transfer_value">हस्तांतरण क्षेत्र के लिए अमान्य मान । रेंज होना चाहिए ( 0-100 )</string>
    <string name="invalid_evolev_value">विकसित क्षेत्र के लिए अमान्य मान । रेंज होना चाहिए ( 0-100 )</string>
    <string name="transfer_below_iv">नीचे स्थानांतरण IV</string>
    <string name="transfer_below_cp">नीचे स्थानांतरण CP</string>
    <string name="evolve_over_iv">साथ विकसित IV</string>
    <string name="evolve_over_cp_sps">साथ विकसित CP</string>
    <string name="use_custm_route_fp">"कस्टम मार्ग का प्रयोग करें"</string>
    <string name="failed_to_initialize_bot">बॉट प्रारंभ करने में विफल , रोक</string>
    <string name="fw_turn_arround">फ़ाइल से पिछले coordiante पढ़ें , चारों ओर मोड़.</string>
    <string name="error_while_walking">चलते समय कुछ गलत हो गया</string>
    <string name="internet_error">जबकि सर्वर से संपर्क त्रुटि हुई । अपने इंटरनेट की जाँच करें.</string>
    <string name="unknown_error">अज्ञात त्रुटि हुई, जारी रखने के लिए 10 सेकंड प्रतीक्षा</string>
    <string name="critical_error">गंभीर त्रुटि हुई। बंद Loggining । Plese प्रेस शुरू बटन को फिर से.</string>
    <string name="logged_in">सफलतापूर्वक शुरू बॉट में लॉग इन किया</string>
    <string name="invalid_cred">अमान्य साख में लॉग इन करने में विफल।</string>
    <string name="server_is_having_issues">लॉग इन करने में असफल। सर्वर होने मुद्दों है.</string>
    <string name="probable_bann_message">में लॉग इन करने में विफल रहा है । आपका खाता शायद प्रतिबंध लगा दिया है । आधिकारिक app के साथ प्रयास करें.</string>
    <string name="transfer_error">त्रुटि हुई pokemons स्थानांतरित करते हुए , लंघन.</string>
    <string name="evolve_error">त्रुटि हुई pokemons विकसित हो रहा है, जबकि लंघन</string>
    <string name="hatch_eggs_error">त्रुटि हुई अंडे सेने जबकि , लंघन</string>
    <string name="clean_items_error">जबकि आइटम सफाई त्रुटि हुई । रस्सी कूदना</string>
    <string name="used_lucky_egg">प्रयुक्त भाग्यशाली अंडे से पहले विकसित।</string>
    <string name="evolved_pokemon">"विकसित Pokemon"</string>
    <string name="with">" साथ में"</string>
    <string name="and">" तथा "</string>
    <string name="evolved_to">"करने के लिए विकसित "</string>
    <string name="transfer">हस्तांतरण</string>
    <string name="catch_error">जबकि pokemons पकड़ने कुछ गलत हो गया</string>
    <string name="loot_error">pokestops लूटपाट , जबकि कुछ गलत हो गया</string>
    <string name="failed_to_catch_message">Pokemon पकड़ने में विफल</string>
    <string name="no_pokeballs_left">पॉकेबाल्लस ख़तम हो गये</string>
    <string name="catch_pokemon">पकड़ लो</string>
    <string name="loot_message">pokestop लूट</string>
    <string name="awarded_items">सम्मानित किया आइटम</string>
    <string name="softban_detected">पता चला संभावित मुलायम प्रतिबंध है, यह तय करने के लिए कोशिश कर रहा है ...</string>
    <string name="softban_removed">हटाया मुलायम Bann , congratz :)</string>
    <string name="softban_error">जबकि मुलायम Bann हटाने कुछ गलत हो गया</string>
    <string name="service_critical_error">सेवा प्रारंभ करने में विफल । आवेदन पुनः प्रारंभ करें</string>
    <string name="pokemon_name">Pokemon के नाम</string>
    <string name="pokemon">Pokemon</string>
</resources>

**Comment by ykingmj** [comment]
Lol
