### ISSUE TITLE
[TRANSLATE] To dutch!

### ISSUE THREAD

**Issue by wesjj** [gosimulate/gosimulator#239]
Hopefully you like it :)
[string-language.txt](https://github.com/gosimulate/gosimulator/files/423590/string-language.txt)
I'm back with helping, (wvrolijk90)

**Comment by NextLineLife** [comment]
Nice :)

**Comment by jgcw** [comment]
Nice but in app not un perfect dutch  for example

Catch weedle is now in the app vang weedle and it has to be gevangen weedle. 
If i get the permision i wil take a better look in how the app uses the sentence and wat is the correct dutch translation.
Still a damn nice job wesjj!!!
