### ISSUE TITLE
[TRANSLATION] Spanish (New lines)

### ISSUE THREAD

**Issue by narutouchi55** [gosimulate/gosimulator#241]
﻿

    <string name="catch_pokemon_sps">Capturar Pokemon</string>
    <string name="evolve">Evolucionar</string>
    <string name="use_iv_value_for_evolve">Usar valores IV para evolucionar</string>
    <string name="use_iv_value_for_transfer">Usar valores IV para transferir</string>
    <string name="save_for_all_pokemons">Guardar para todos los pokemon</string>
    <string name="save">Guardar</string>
    <string name="name">Nombre</string>
    <string name="one_step_in_meters">Una paso en metros</string>
    <string name="wait_after_next_step">Espera para el siguiente paso ( segundos )</string>
    <string name="wait_after_catch">Espera después de capturar pokemon ( segundos )</string>
    <string name="wait_after_pokestop">Espera después de lootear una pokeparada ( segundos )</string>
    <string name="wait_after_transfer">Espera después de transferir un pokemon ( segundos )</string>
    <string name="wait_after_evolve">Espera después de evolucionar un pokemon ( segundos )</string>
    <string name="use_raspberries">Usar bayas para capturar pokemon</string>
    <string name="use_raspberries_for_pokemons"><![CDATA[Usar bayas para poekmon con un CP más alto de >= ?]]></string>

**Comment by narutouchi55** [comment]
[1iCt45V7.txt](https://github.com/gosimulate/gosimulator/files/423607/1iCt45V7.txt)

**Comment by Dark25** [comment]
Go

**Comment by Dark25** [comment]
God

**Comment by narutouchi55** [comment]
@Dark25 what?
