### ISSUE TITLE
1.10.4

### ISSUE THREAD

**Issue by BlinddHeart** [gosimulate/gosimulator#248]
Question, what's fix/changed/new in 1.10.4 update?
sorry if it's abit annoying but I'm just curious.
thank you for the time you put into this app.

**Comment by narutouchi55** [comment]
Better translations

**Comment by BlinddHeart** [comment]
What's new in the latest update.

**Comment by narutouchi55** [comment]
@BlinddHeart Better translations

**Comment by BlinddHeart** [comment]
ohh, I thought u ment to be more clear. thank u
