### ISSUE TITLE
is this a bug? 

### ISSUE THREAD

**Issue by Darkshinra** [gosimulate/gosimulator#252]
normally as a level 25 you would catch 600 cp+ pokemon but ever since i made a new account im in NYC time square im level 25 and i keep catching 400 or below cp pokemon is this normal? or is this like a new niantic thing where getting 600+ cp is rare now

**Comment by narutouchi55** [comment]
Try changing this settings
![screenshot_20160818-015718](https://cloud.githubusercontent.com/assets/21021007/17757469/46291ae2-64e7-11e6-824b-7bab54997cd0.png)

**Comment by Riceball0831** [comment]
what is this going to do lol

**Comment by Riceball0831** [comment]
@narutouchi55 
what is this going to do
