### ISSUE TITLE
New version inst

### ISSUE THREAD

**Issue by MarcoBelinea** [gosimulate/gosimulator#254]

**Comment by narutouchi55** [comment]
Better translations

**Comment by MarcoBelinea** [comment]
Installed - as system app - reboot phone - start go sim - make options as in for me working perfect last Version (without german) when i hit Start - black screen Go Sim must be closed Error

Any

**Comment by narutouchi55** [comment]
Delete the app before installing a new version

**Comment by kingkai808** [comment]
Don't install it if you don't need the translations. Its just a translator update nothing else.
