### ISSUE TITLE
Error On Gym

### ISSUE THREAD

**Issue by mrkanor** [gosimulate/gosimulator#255]
I get "error message" when fighting a gym leader. does anyone experiencing it?

**Comment by narutouchi55** [comment]
Happens sometimes, why do you post it here?

**Comment by mrkanor** [comment]
I thought it was an issue because of the gosim.

**Comment by mrkanor** [comment]
or a bug for constant using of gosim..

**Comment by narutouchi55** [comment]
Its not because of gosim, I had the same error before using gosim.

**Comment by mrkanor** [comment]
hmmmm ok thank you sir.
