### ISSUE TITLE
[REQUEST] POST ALL OLD VERSION OF GO SIMULATOR.

### ISSUE THREAD

**Issue by funkpunk8624** [gosimulate/gosimulator#256]
Kindly post it back of those old version of go simulator bcuz of other smartphone dont fixed or having error in every new or old version of the app.

Thank you! :)

**Comment by narutouchi55** [comment]
Search the apk on your Download folder, uninstall gosim and install the older versión.

**Comment by funkpunk8624** [comment]
Anyone got v1.9.0+ till .9.0 only?
