### ISSUE TITLE
Google accounts beware

### ISSUE THREAD

**Issue by Freshink808** [gosimulate/gosimulator#257]
I've had to 25+ Google accounts perma banned, one a few days ago and another today. Didn't use bot for awhile on last account, only fly gps and spoofed only in my city. I suggest anyone using not use it on Google accounts. All ptc accounts i have are using both bots/fly gps have not been banned yet. Idk if google accounts are easier to detect but it seems like it.

**Comment by gengchu** [comment]
Using fake gps makes you ban faster rather than using bot.

**Comment by Freshink808** [comment]
Figured that out the hard way lol

**Comment by namecwarrior** [comment]
It's how you use the app. If you are not very careful, you will probably get ban either you use PTC account or Google account login. I created a PTC dummy account for me to know how to get ban. I level it to 24 in just two days by using the bot but i did not spoof my location. So my conclusion here is not to level up too fast and always simulate the time of travel before you change your location. That's all. Have a good day.

**Comment by biztastic** [comment]
Both of my accounts were PTC. It's not just Google

**Comment by Freshink808** [comment]
Seems like spoofing is way riskier, i suggest don't bother unless your rooted.
