### ISSUE TITLE
Will IV transferring be fixed + best starter nest routes?

### ISSUE THREAD

**Issue by skidiiot** [gosimulate/gosimulator#258]
Hey all!

Curious to know what you guys have found to be the best starter nests? (When I refer to starters I mean Squirtle, Bulbasaur, and Charmander. Some people refer to the first 20 pokemon in the dex as starters)

Also any plans to fix the IV transfer where some pokemon are just skipped over when they qualify?

**Comment by narutouchi55** [comment]
Best starter routes (for me) are: NY South and Melbourne Lilydale

**Comment by kingkai808** [comment]
I always catch squirtle at Santa Monica beach
