### ISSUE TITLE
Bot doesn't do anything

### ISSUE THREAD

**Issue by msilvaz** [gosimulate/gosimulator#259]
I can not capture pokemon, or take pokestop, only says "SUCCESSFULLY LOGGED IN. STARTING BOT"  only walk...

**Comment by biztastic** [comment]
Same here

**Comment by narutouchi55** [comment]
Make sure to uninstall gosim before installing a new updated app. Select a route and adjust the bot settings.

**Comment by msilvaz** [comment]
I restore my cellphone, and i have the same problem

**Comment by kingkai808** [comment]
You are IP banned. Just wait 4-8 hours. Or use a VPN.

**Comment by biztastic** [comment]
Generally, with an IP ban I can't even log in

**Comment by kingkai808** [comment]
Its only soft IP ban. Hard IP means u can't login at all.

**Comment by msilvaz** [comment]
No, i try in a new account and i have the same problem
