### ISSUE TITLE
WHERE IS THE TRANSLATION 

### ISSUE THREAD

**Issue by AZZREYNAZARETH** [gosimulate/gosimulator#260]
how can i use translation in new update 1.10.4?..Sorry newbie here

**Comment by narutouchi55** [comment]
The app uses your phone language. Maybe your there is no translation into your language. If you want to translate into your language use this: https://github.com/gosimulate/gosimulator/wiki/Translate-guide

**Comment by AZZREYNAZARETH** [comment]
create already

**Comment by narutouchi55** [comment]
It will implemented in a few days #249
