### ISSUE TITLE
Manual softban fix button?

### ISSUE THREAD

**Issue by AriesLaCroix** [gosimulate/gosimulator#261]
can the developer implement this? So we don't need to wait for the app to unban us.

**Comment by narutouchi55** [comment]
The app detects the soft ban and unbans you automatically. Also dont use the app for more than 12 hours a day.

**Comment by zakydudutz** [comment]
manual unsoftbaned lets try:
a step which we did quite pokestop and loot , and get out of pokestop . do over and over again until 40x in the same pokestop .
