### ISSUE TITLE
Someone make a San Francisco pier 39 and waters edge route?

### ISSUE THREAD

**Issue by kingkai808** [gosimulate/gosimulator#263]
It has the highest dratini spawns I've ever seen. By manually putting g the GPS there I get error while walking. Its fucking annoying. But I've caught over 100 candies worth so far. They seem to only appear at night though. Please make a route that goes up and down pier 39 continuously!

**Comment by narutouchi55** [comment]
#196

**Comment by narutouchi55** [comment]
#195

**Comment by tfc20160801** [comment]
kingkai88 I posted your request in #195. You can also use #194 for Dratini's Nest

**Comment by jgcw** [comment]
I would love to see a pier 9 route at night its dratini heaven and during the day magicarps
