### ISSUE TITLE
Bot not doing anything

### ISSUE THREAD

**Issue by dalord3532** [gosimulate/gosimulator#265]
Bot is just trying to loot pokestops
Not catching any pokemon

**Comment by narutouchi55** [comment]
IP banned

**Comment by dalord3532** [comment]
solution to it?

**Comment by narutouchi55** [comment]
Just wait, you can be soft ip banned or banned forever.

**Comment by dalord3532** [comment]
IP Not banned, my other user is working fine, issues with trainer club account, not with Google account.

**Comment by manor7777** [comment]
You are softbanned on that account. Wait some time, and don't switch countries often, wait 5-6 hours between locations
