### ISSUE TITLE
Botted to 20 using 1.10.2 

### ISSUE THREAD

**Issue by powerboxizm** [gosimulate/gosimulator#267]
Default settings in with a custom route from my front door continuously around town. Not one softban.

Cheers

**Comment by rgdwz** [comment]
I hope, same here into level 21

**Comment by narutouchi55** [comment]
If its a Google account you will probable get banned

**Comment by rgdwz** [comment]
Login with ptc, cuz my previous account get banned in level 24..so sad

**Comment by narutouchi55** [comment]
Idk why but I got all my 10 Google account banned but my ptc accounts are fine, weird

**Comment by powerboxizm** [comment]
Its ptc my google got hit hard with my lvl 30 3000cp dragonite

**Comment by powerboxizm** [comment]
My ptc got hit running 1.10.4 or whatever but on fast nonstop.but in my town everyones like 26 now

**Comment by powerboxizm** [comment]
Beware of lvl 24 guys not in one day atleast

**Comment by narutouchi55** [comment]
Do not use the app for longer than 12 hours

**Comment by rgdwz** [comment]
Agree

**Comment by powerboxizm** [comment]
Is the softban message in v1.10.2?

**Comment by carongaden** [comment]
Go sim 1.10.4 
Map can't moving...?
Help?

**Comment by narutouchi55** [comment]
Visual bug

**Comment by carongaden** [comment]
Can fix ?
