### ISSUE TITLE
Something went wrong....

### ISSUE THREAD

**Issue by kurtsky** [gosimulate/gosimulator#269]
Anyone keep getting this error?
I keep getting it since yesterday. 
Ideas? My speed is on Medium and same continent since yesterday.
It goes away and then back again.

Something went wrong while catching Pokemon/Something went wrong while looting Pokestops
I also sometimes dont get loot from Pokestops

**Comment by Freshink808** [comment]
Read the "read me" section under code.

**Comment by abojobo** [comment]
Maybe ur connection very slow

**Comment by neospeed83** [comment]
Me too same issue
