### ISSUE TITLE
All rrlease after 1.2 crashes on my device.

### ISSUE THREAD

**Issue by ryan7646** [gosimulate/gosimulator#27]
I am not sure what is happening. When I start it it would just turn white for a few seconds and crash. 1.2 works fine on my device but the 1.3 onwards are not.
Device info:
Gionee E7

**Comment by VernMcC** [comment]
This happens for me occasionally. I typically get two pop-ups then back to background screen.  If I restart it works fine.  I have found if it crashes after I have been in settings it may require a force kill of app to get it started correctly again.

**Comment by gosimulate** [comment]
Please be sure if u selected Predefined route u have an actually route selected. If no route is selected app will crash on start button

**Comment by ryan7646** [comment]
I haven't goten to that part yet. The app will just launch and crash. Thats it. It will turn white for 1-2 second and then crash. It turns to white in 1.2 and then continue to show the UI but the latter versions it will just crash.

**Comment by ryan7646** [comment]
Additional note. I usually clear cache and data to see if it works. If not I clear them again and restart my device. To no avail it rrally crashes on startup. I'm also wondering why the new releases no longer worked.

**Comment by gr33nd3v1l** [comment]
Do you have an adblocker installed

**Comment by ryan7646** [comment]
Nope. Phone is rooted with no ad blocker. Uc browser has a built in adblock. I don't think this is the culprit.

**Comment by gr33nd3v1l** [comment]
Try completely clearing app cache and uninstalling, rebooting, reinstalling.

Probably already have.. but heh

**Comment by ryan7646** [comment]
Yep already did those experiments. The only version that worked on my phone is 1.2.0.

**Comment by gr33nd3v1l** [comment]
I'll leave it open. Experiment some more..

**Comment by ryan7646** [comment]
I got good news. 1.9 seems to work when I converted it to system app. I wonder why it didn't worked for the other. I'll test it for a few times and update you folks. Thanks always.

**Comment by clix12** [comment]
![Uploading Screenshot_2016-08-15-03-02-53.png…]()
I'm also experiencing issues with versions 1.5 and higher. The only version works for me is 1.4.0. Itried everything but keeps crashing :(
