### ISSUE TITLE
Route For Pikachu Fans, Centennial Park, Sydney

### ISSUE THREAD

**Issue by bhembenk** [gosimulate/gosimulator#271]
Here you go for Pikachu Fans.

[CentennialPark_sidney_pikachu.txt](https://github.com/gosimulate/gosimulator/files/424298/CentennialPark_sidney_pikachu.txt)

![pikachu](https://cloud.githubusercontent.com/assets/19658073/17764670/144c1f74-654b-11e6-8d71-96662cf92140.png)

**Comment by Shooriki** [comment]
Udaman! Was wondering where this nest is

**Comment by FriendZoneKing** [comment]
what else spawns in there?

**Comment by bhembenk** [comment]
some eeve, growlithe, mostly zubat
