### ISSUE TITLE
Pokemon settings is blank

### ISSUE THREAD

**Issue by Odinlancer** [gosimulate/gosimulator#272]
Every thing is fine but when I open the pokemon settings, the only thing I see Is the catch pokemon, evole swtich. Nothing else. I don't see the iv settings or transfer setting. It is blank. I wish I can send you the screenshot.

**Comment by Freshink808** [comment]
Remember to uninstall and delete older apk from downloads/device storage then redownload new apk and install.

**Comment by Odinlancer** [comment]
I already did that but still. How can I send screenshots?

**Comment by Freshink808** [comment]
What device are you using?

**Comment by Odinlancer** [comment]
Samsung galaxy grand neo. The other versions were fine till IVs were introduced and this happens

**Comment by Freshink808** [comment]
Not sure what more you could do. You just have to wait till the dev has time to answer your problem. Jus delete/transfer things manually for now and remember to have your gps off.

**Comment by Omanez** [comment]
Same issue like me :(
fix it please..
my device acer z205.

**Comment by zakydudutz** [comment]
blank too at my friend device zenfone C,but on my device zenfone 4 not problem :)
#sory bad english

**Comment by NextLineLife** [comment]
Hold you phone side ways. I should appear.

**Comment by NextLineLife** [comment]
It*

**Comment by afk1997** [comment]
same issue for Samsung Galaxy Core 2

**Comment by Odinlancer** [comment]
it worked thanks

**Comment by narutouchi55** [comment]
Rotate your phone. This happens when you have a small screen.
