### ISSUE TITLE
Something went wrong error

### ISSUE THREAD

**Issue by neospeed83** [gosimulate/gosimulator#273]
The bot when in background says this quite a few times. I have lots of pokeballs too. Same location as always on 3G internet. Works fine in official app. What am i doing wrong. (All settings are default) 10.2 version

**Comment by Freshink808** [comment]
Try checking in your app manger-gosim and check that it holds priority and all permissions granted. Its also possible that your opening another app with gosim in the background and its holding priority over gosim.

**Comment by narutouchi55** [comment]
Check if you have enough Rasperries. Also dont use the bot for longer than 12 hours.
