### ISSUE TITLE
Questions please answer 

### ISSUE THREAD

**Issue by Darkshinra** [gosimulate/gosimulator#274]
I was in NY originally but i accidentally put australia and i haven't wait 1 day or so to make it less suspicious i accidentally pressed start i loot 1 stop in australia and then I immediately stopped it will i get banned?

**Comment by Freshink808** [comment]
Most likely you will only receive a normal soft ban. I suggest be very careful.

**Comment by Darkshinra** [comment]
@Freshink808  but i'll be fine though right?

**Comment by Freshink808** [comment]
Most likely. Also a side note if you're gps spoofing with a non rooted phone i suggest you stop because that will cause a perma ban/hard ban.

**Comment by Darkshinra** [comment]
is go simulator gps spoofing? i mean i do use it wisely 4-5 hours uses 5 hours break 
if i want to change location wait for 1 day

**Comment by Freshink808** [comment]
No it bypasses spoofing all together. But i suggest staying in your local city just because of your ip is set for that area. Theres alot of info in the "read me" section under code.
