### ISSUE TITLE
New update on bans! Read before botting

### ISSUE THREAD

**Issue by Freshink808** [gosimulate/gosimulator#275]
Saw this in an article written the other day. Makes sense to me

Several new types of bans have been implemented by Niantic over the past couple of weeks - bans that come from developer innovations running a bit too deep for their liking. The "if this then that" of these bans suggest that they're aimed at automatic bots - the bane of legitimate Pokemon GO gamers everywhere.

1. Pokestop over-use: Users will be banned when they tap and spin around 2-thousand Pokestops within a single day.

2. Pokemon over-catch: Users will be banned when they catch over 1-thousand Pokemon in a single day.*

*Even if a user caught one Pokemon every 5 minutes without fail for a full day, they'd only be capturing 288 monsters total. For a real user, catching 1,000 Pokemon in a single day isn't actually possible without cheating.

**Comment by Freshink808** [comment]
Bot wisely ppl.

**Comment by FriendZoneKing** [comment]
good reminder. thanks

**Comment by narutouchi55** [comment]
Dont bot for longer than 12 hours

**Comment by SmilingSword** [comment]
dont do snipe also
