### ISSUE TITLE
Am i permanent banned

### ISSUE THREAD

**Issue by ykingmj** [gosimulate/gosimulator#278]
As i try to to login with the bot i saw a message unable to get data from serve as your ban and from the app too even i didnt get a email from niantic for the ban am i really permanent ban or freeze?

**Comment by savage500** [comment]
Fail to get data from server more than 24 hours mean you're permanently banned.

**Comment by ykingmj** [comment]
Not morethan 24 hours i succefully login yesterday... and around 10hrs had passed i think i should wait..

**Comment by operz** [comment]
Login Fail 3 Day with bot unable to get data from serve as your ban
