### ISSUE TITLE
Problems with ROUTE

### ISSUE THREAD

**Issue by raistlin74** [gosimulate/gosimulator#279]
Hi all,
I'm having problems with some routes.
If I use a route like Milano Parco Sempione, everything works like a charm. But if I change in Opera House Sidney, the app say that it can't login and maybe I'm banned. 
I've tried with the PokemonGo app and I'm not banned.

If I change again to Milano, it works again. 

Which is the problem?

Thanks in advance

**Comment by ErikK194** [comment]
Same with Dusseldorf

**Comment by gosimulate** [comment]
Please restart application, change route, start app. Maybe it can help

**Comment by ErikK194** [comment]
Nope.
Name of the route is d,sseldorf in app.
