### ISSUE TITLE
Requesting a route

### ISSUE THREAD

**Issue by Anthony15432** [gosimulate/gosimulator#280]
I would like someone to help me make a route at a  beach at Singapore the starting coordinate would be 1.25572, 103.80994. I would like to request on someone to help me make a route on that beach thanks

**Comment by gedoyz** [comment]
#195

**Comment by Anthony15432** [comment]
1.255794,103.809827 (Starting Route) 
1.251032,103.817078 (Ending Route)
1.251032,103.817078 (Ending Route)
1.255794,103.809827 (Starting Route)

**Comment by tfc20160801** [comment]
Anthony15432, it is uploaded in #195
