### ISSUE TITLE
[Request] Custom route for Mumbai(India)

### ISSUE THREAD

**Issue by afk1997** [gosimulate/gosimulator#281]
Hello! can you make a custom route for Gateway of India,Mumbai. There are too many pokestops amd one can easily catch around 50 pokemons without bot in 40-45 mins. and even location is real good for rare as well as all type of pokemons. Psyduck and Tentacool, magikarp are most common. 

And one more route request on only pokestop loot. Thanks..

**Comment by tfc20160801** [comment]
Go to #195 and follow directions in there for route request
