### ISSUE TITLE
Theory about bans

### ISSUE THREAD

**Issue by Freshink808** [gosimulate/gosimulator#282]
You guys think they use gyms to read players play time and other stats because two gps spoof/bot accounts i used to take gyms have been perma ban and the bot accounts i havent used on a gym are fine. Also sniped with a bot account but havent used in a gym and it is still ban free.

**Comment by afk1997** [comment]
One more thing if you purchase coins and do teleport they don't ban you.. I have tried this way too much like going crazy all over world using pokesniper.. My acc lvl is 21

**Comment by biztastic** [comment]
I've never even been to a gym and I have been banned on two accounts.
