### ISSUE TITLE
Some Pokémon Location?

### ISSUE THREAD

**Issue by BrazilianHomewrecker** [gosimulate/gosimulator#285]
Hey, can you guys tell me what is the best route for Abra, Hitmonlee, Hitmonchan, Voltorb, Rhyhorn, Gastly, Machop, Mr. Mime, Vulpix, Clefairy, Jigglypuff, Diglett, Mankey, Growlithe and Meowth?
Really need these guys for candies...
Thanks!

**Comment by myhadhy** [comment]
I believe Santa Monica fit for you.

**Comment by manor7777** [comment]
Closed. Marked as duplicate - see #196
