### ISSUE TITLE
Does gosim auto spoof location to route?

### ISSUE THREAD

**Issue by D3vr04** [gosimulate/gosimulator#291]
Or do I have to spoof/fake/fly GPS to route location before starting gosim?
What location data is Niantic getting when our account is used by gosim to run routes?
Thanks!

**Comment by rgdwz** [comment]
I dont use gps, bot still running.. Hehe

**Comment by D3vr04** [comment]
Okay cool rgdwz. But now I need either greendevil or gosimulate to answer what location data is Niantic getting when our account is used by gosim to run routes? Does gosim auto spoof location of the route?

**Comment by narutouchi55** [comment]
The bot spoofs the location and then it logs in your account.
