### ISSUE TITLE
help with route making

### ISSUE THREAD

**Issue by freezup4** [gosimulate/gosimulator#292]
Hi, whenever I try making my own route login the bot crash... how can I make it work ?

**Comment by gosimulate** [comment]
post ur route here please

**Comment by freezup4** [comment]
45.190513,5.72734
45.190457,5.727399
45.190406,5.72746
45.190358,5.727511
45.190312,5.727573
45.190264,5.727649
45.190205,5.727745
45.190193,5.727847
45.190191,5.727927
45.190179,5.728029
45.190177,5.728139
45.190152,5.728234
45.190139,5.728315
45.190135,5.72838
45.190122,5.72848
45.190115,5.728539
45.190098,5.728619
45.190135,5.728649
45.190153,5.728612
45.190167,5.728514
45.19017,5.728405
45.190152,5.728313
45.190153,5.728222
45.190152,5.728146
45.190172,5.72804
45.190175,5.727927
45.190191,5.727814
45.190203,5.727708
45.190226,5.727639
45.190256,5.727592
45.190285,5.72756
45.190334,5.727513
45.190368,5.727483
45.190402,5.727436
45.190444,5.727421
45.190475,5.727392
45.190519,5.727362
45.190566,5.72729
45.190578,5.727188
45.190566,5.727086
45.190525,5.72697
45.190502,5.726872
45.190462,5.726886
45.190442,5.726941
45.190447,5.727007
45.190461,5.727094
45.190459,5.727149
45.190457,5.727198
45.190452,5.727263
45.190427,5.727333
45.190513,5.72734

**Comment by freezup4** [comment]
And same with this one 

45.190531,5.727293
45.190532,5.727365
45.190484,5.727393
45.190447,5.727442
45.190408,5.727499
45.190369,5.727552
45.190338,5.727601
45.1903,5.72769
45.19029,5.72777
45.190267,5.727822
45.19024,5.727883
45.190223,5.727943
45.190214,5.728013
45.190206,5.728073
45.190179,5.728132
45.190162,5.728092
45.190165,5.728021
45.190176,5.727965
45.190187,5.727902
45.190187,5.727851
45.19018,5.727792
45.190186,5.727731
45.190201,5.727666
45.190238,5.727589
45.190278,5.727518
45.190314,5.727447
45.190376,5.727396
45.190415,5.72733
45.19045,5.727253
45.190481,5.727187
45.190534,5.727116
45.190545,5.727175
45.190517,5.727224
