### ISSUE TITLE
Successfully Logged In but No Loot or Catch

### ISSUE THREAD

**Issue by iamjustoohandsome** [gosimulate/gosimulator#298]
I am seeing that its moving but it doesnt loot or catch pokemon
I download the latest app version but it didnt change
I logged in back to official app and I am not banned
Please help

**Comment by iamjustoohandsome** [comment]
Found out something
I am using my 4G and I used customer route here in my country then its working

**Comment by manor7777** [comment]
@iamjustoohandsome Try restarting the app and making sure you are not soft banned (app takes a while to detect it, best know yourself)
