### ISSUE TITLE
[ROUTE]: Palembang, Benteng Kuto Besak (BKB), Indonesia

### ISSUE THREAD

**Issue by HAZE4U** [gosimulate/gosimulator#300]
one of the most favorite place in Palembang. 
Check This out : 
[Palembang_Benteng_Kuto_Besak_Indonesia.txt](https://github.com/gosimulate/gosimulator/files/425601/Palembang_Benteng_Kuto_Besak_Indonesia.txt)

**Comment by iamjustoohandsome** [comment]
what are good catch there?

**Comment by HAZE4U** [comment]
nothing special, just some magicrap golduck, pidgey, ratata, poliwag, sometimes bulbasaur lickitung.
