### ISSUE TITLE
10.4 exp update interval

### ISSUE THREAD

**Issue by Shooriki** [gosimulate/gosimulator#301]
not sure when and how it updates exp counter, but it is crucial on low levels not to run through 10 of them in an hour and then get banned.

**Comment by Shooriki** [comment]
... what i mean. it updates exp on 1/2 of the route or some other interval, not after each catch/loot. I prefer to gain a level on bot and then login in app to collect level rewards

**Comment by carongaden** [comment]
V1.10.4 cant moving in map?can fix?

**Comment by Shooriki** [comment]
Spotted exp showing sequence: it updates with lvl up, sometimes more often.
