### ISSUE TITLE
[ROUTE]:  Urayasu, Disneyland Japan

### ISSUE THREAD

**Issue by HAZE4U** [gosimulate/gosimulator#302]
for ppl who looking for Farfetchd and some rare pokemon
check this out : 

[Urayasu_Disneyland_Japan.txt](https://github.com/gosimulate/gosimulator/files/425653/Urayasu_Disneyland_Japan.txt)

**Comment by iamjustoohandsome** [comment]
example of rare pokemons?

**Comment by BrazilianHomewrecker** [comment]
Example of rare Pokémon? [2]

**Comment by HAZE4U** [comment]
im not sure but in  this route i always find pikachu, dratini, sometimes spawned abra, charmander, magmar , jynx, hitmonchan, and farfetchd (only that u can find in ASIA)
