### ISSUE TITLE
[ROUTE] Sao.Paulo_Avenida.Paulista_Brasil

### ISSUE THREAD

**Issue by TiagoEsp** [gosimulate/gosimulator#304]
Nice Route Brasil +30 PokeStops
Drogonite
Pokemons Ghosts
Etc.....

[Sao.Paulo_Avenida.Paulista_Brasil.txt](https://github.com/gosimulate/gosimulator/files/425800/Sao.Paulo_Avenida.Paulista_Brasil.txt)

**Comment by iamjustoohandsome** [comment]
i will try. thanks for sharing. try also the japan latest posted. got high cp basic pokemon for evolve

**Comment by FriendZoneKing** [comment]
@iamjustoohandsome  
are you talking about this route in japan? that has high cp starters?
https://github.com/gosimulate/gosimulator/issues/60
