### ISSUE TITLE
APP closes at logon

### ISSUE THREAD

**Issue by Dem0nIO** [gosimulate/gosimulator#308]
Every time I press start, the app logs me in, but then closes when the app attemps to show the login-ad

Any chance to fix this issue?

**Comment by narutouchi55** [comment]
Make sure to uninstall gosim before installing a new update. Make sure to have all the settings right and a route that actually works.

**Comment by manor7777** [comment]
Marked as Needs Additional Information.

Please post the log of the app (screenshot it), either before or after it crashes and you re open it to see if we can find the problem.

**Comment by Dem0nIO** [comment]
This happens when i select a custom route. The app works well with predefined routes.

For installation, i followed these steps:
1. Uninstalled previous app
2. Reboot
3. Installed new version
4. Reinstalled as system app
5. Set rw-r--r--
6. Reboot

The custom route txt has no invalid characters.

Any ideas? Will post screenshots ASAP.
