### ISSUE TITLE
Switching to predefined routes from custom routes

### ISSUE THREAD

**Issue by biztastic** [gosimulate/gosimulator#316]
I think I found a bug that might have got me banned. I am using an account I created 3 days ago and I made it this far without a soft ban by using a set of custom routes aroud my home and work.

Today I tried to switch to a predefined route an hour away after waiting 3 hours, but it just sent me to thw default location in Sarajevo. Got my first soft ban and then another when I jumped back. Should be banned tomorrow.

**Comment by gosimulate** [comment]
I'll check that. Thx for reporting
