### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by hanncreator** [gosimulate/gosimulator#317]
Can you add features pokeball how many and how great ball that we can from the loot pokestop?

**Comment by hanncreator** [comment]
Or show list item pokeball in my bag?

**Comment by narutouchi55** [comment]
You cant choose the items you will get from a pokestop.

**Comment by manor7777** [comment]
@narutouchi55 i think he means just a list of how many items you got from a pokestop, should be easy to put that in

**Comment by narutouchi55** [comment]
@manor7777 it shows (my bag is full)

![screenshot_20160819-040106](https://cloud.githubusercontent.com/assets/21021007/17796560/9ac14ab8-65c1-11e6-941b-c1b1d8457010.png)

**Comment by manor7777** [comment]
@narutouchi55 i know, but from what they are saying, i think like the journal in pokemon go (where it shows all the pokemon you catch, and the loot from stops) should go in the bag section

**Comment by narutouchi55** [comment]
@manor7777 okay

**Comment by hanncreator** [comment]
Feature same pokemon bag, i request item bag
