### ISSUE TITLE
Loot Requesting

### ISSUE THREAD

**Issue by mugemuge** [gosimulate/gosimulator#318]
i wish in bag u can delete your item inside like pokeball , revive and etc...for not peding in poke stop.. then you loot what ever you want..

**Comment by powerboxizm** [comment]
What the fuck did you just even write

**Comment by narutouchi55** [comment]
Could you be more clear please?

**Comment by andy1688878** [comment]
1 floor Use eng please

**Comment by mugemuge** [comment]
sorry my bad english.. i wish in bag u can delete your item inside like pokeball , revive and etc...for not peding in poke stop.. then you loot what ever you want..

**Comment by Phanthropogenic** [comment]
Just use the PoGo app and turn off the Location service.

**Comment by mugemuge** [comment]
@Phanthropogenic do you have a link ?

**Comment by BadSly** [comment]
@mugemuge said that you should use the official app of Pokemon Go, just turn off your GPS before using it.
