### ISSUE TITLE
permabanned?

### ISSUE THREAD

**Issue by crzcrw** [gosimulate/gosimulator#321]
I just got failed to login message from one of my account (lv 25), and failed to get data from the server in the pokemon go app. 
I never log in elsewhere besides NY, but I haven't login for 25+ hours, because I planned to catch farfetchd, mr mime and kangaskhan for completing the pokedex. Approx 1 hour ago, I've caught a farfetchd in hong kong, and I wait for 10 minutes and logged in to catch a dragonite nearby. Still worked. 1 hour later, I tried to log in (still in hong kong), and failed. 

Is this account still have hope? 
Are all the account that have failed to get data from the server message got permabanned?

**Comment by marvz098** [comment]
Yeah thats perma banned..say goodbye to your account haha

**Comment by SmilingSword** [comment]
where do you go>

**Comment by crzcrw** [comment]
Got to move on then hahaha :D

What do you think is the cause of that permaban? After jumped, I still can caught a farfetchd and dragonite, and logged off.  Only in the next login after 1 hour later I got permabanned.

**Comment by crzcrw** [comment]
@SmilingSword from NY to Hong kong, after 25+ hour

**Comment by SmilingSword** [comment]
and then?

**Comment by SmilingSword** [comment]
try ban appeal

**Comment by crzcrw** [comment]
In hong kong, I still can caught a monster or two, loot at a pokestop, and logged off.
After 1 hour I logged in still in there, and got banned.

**Comment by crzcrw** [comment]
Ok I will try that (y)

**Comment by SmilingSword** [comment]
i think they ban you base on you ip

**Comment by crzcrw** [comment]
Yes, that's most likely true. So seems it is more unsafe to jump on other continents now
