### ISSUE TITLE
[ROUTE]: Sao.Paulo_Largo.Batata_Brasil

### ISSUE THREAD

**Issue by TiagoEsp** [gosimulate/gosimulator#322]
[Sao.Paulo_Largo.Batata_Brasil.txt](https://github.com/gosimulate/gosimulator/files/426291/Sao.Paulo_Largo.Batata_Brasil.txt)

**Comment by gengchu** [comment]
What usually can be found here?

**Comment by TiagoEsp** [comment]
Rock/Eletric
