### ISSUE TITLE
Failed to get game data from server

### ISSUE THREAD

**Issue by BlinddHeart** [gosimulate/gosimulator#325]
Is this Permanent Ban or must I wait for Niantic to send me an email saying I'm ban?

**Comment by marvz098** [comment]
Hahaha thats perma banned no need to confirm to niantic

**Comment by BlinddHeart** [comment]
thank you!

**Comment by mugemuge** [comment]
its under observation that's why you Failed to get game from the date..

**Comment by BlinddHeart** [comment]
what does that mean? @mugemuge
