### ISSUE TITLE
Requesting Feature

### ISSUE THREAD

**Issue by BlinddHeart** [gosimulate/gosimulator#327]
Deleting/Removing/Transferring pokemon(s) and item(s) manually from bot app so we don't have to login into the official PoGo app to do so.

**Comment by BlinddHeart** [comment]
Edit: Evolving as well!!

**Comment by andy1688878** [comment]
Agree

**Comment by gosimulate** [comment]
Working on it

**Comment by BlinddHeart** [comment]
awesome!

**Comment by mugemuge** [comment]
Nice GOsimulate.. more power in your apps.. :)

**Comment by gosimulate** [comment]
Implemented !
