### ISSUE TITLE
Any solution to this my avatar wont move

### ISSUE THREAD

**Issue by marvz098** [gosimulate/gosimulator#329]
My gps is workig properly why did this happen

**Comment by gosimulate** [comment]
GPS dont have to be turned on. If mark is not moving, are logs shown ?

**Comment by manor7777** [comment]
Marked as won't fix until more information is provided.

Need logs from the program (a few screenshots etc)

I suspect it's just a visual glitch or you are soft banned.

**Comment by biztastic** [comment]
When I had this issue, I cleared data, restarted my phone, and it worked.
