### ISSUE TITLE
[ROUTE]: Sydney, Australia

### ISSUE THREAD

**Issue by gr33nd3v1l** [gosimulate/gosimulator#33]
[Sydney_Opera.House_Australia.txt](https://github.com/gosimulate/gosimulator/files/417251/Sydney_Opera.House_Australia.txt)

![capture](https://cloud.githubusercontent.com/assets/3631381/17649596/b31ab31e-6239-11e6-8000-02f363a95d6d.PNG)

by [Anthon](http://forum.xda-developers.com/android/apps-games/app-gobot-pokemon-bot-t3430545/post68168074#post68168074)

**Comment by faizmodan** [comment]
# I suggest to Dev that please verified route before including in app as to many ppl are getting banned due to long jumping

**Comment by gr33nd3v1l** [comment]
![capture](https://cloud.githubusercontent.com/assets/3631381/17649596/b31ab31e-6239-11e6-8000-02f363a95d6d.PNG)

this appears to be fine

**Comment by xitopodo** [comment]
This route works great and I like so much because appear Dratinis.

I'm trying to have a Dragonite :smiling_imp: 

Also, appear Seals, Slowpokes and some commons Pokemons.

**Comment by rockybalbon027** [comment]
Sir how to custom the route using android please teach me

**Comment by gr33nd3v1l** [comment]
@rockybalbon027 read the end of readme.md

**Comment by AosPONG** [comment]
Thank you sir

I will try this Route for Catch Draniti

**Comment by SpiitDaico** [comment]
![screenshot_2016-08-17-09-09-41](https://cloud.githubusercontent.com/assets/21088449/17749389/0d0f6276-64f0-11e6-97d3-6b0e51024b3f.png)
Thanks !!
