### ISSUE TITLE
route kijkduin holland

### ISSUE THREAD

**Issue by denn2k** [gosimulate/gosimulator#336]
In holland the masses go crazy at kijkduin holy grale hotspot. Rare pokemons are there ppl flock from everywhere to go there.
If put a link with photo for the best spawn locations in it. Could someone make a good route plz.

http://www.pokemongofans.nl/wp-content/uploads/2016/08/Pokemon-Hotspots.jpg

**Comment by manor7777** [comment]
Closed. If you want to make or download a route, see https://github.com/gosimulate/gosimulator/wiki/ROUTES and https://github.com/gosimulate/gosimulator/blob/master/README.md#how-do-i-make-my-own-route
