### ISSUE TITLE
Singapore Route - Hougang Ave 10 Blk 401 (Lots of Pokestops and Rare Pokemons - Snorlax/Gyarados)

### ISSUE THREAD

**Issue by SaveOlafPlease** [gosimulate/gosimulator#338]
This is the famous Hougan Ave 10 Blk 401, where Singaporean Pokemon Zombies go to at night and cause havoc for the residents!
[Hougang_Ave_10.txt](https://github.com/gosimulate/gosimulator/files/426798/Hougang_Ave_10.txt)
![13938204_10153964865787572_9051980921433547283_o](https://cloud.githubusercontent.com/assets/21123115/17807393/d47ce41c-663c-11e6-883f-c8ae07308897.jpg)
![13958092_10153964869372572_4491981017909612289_o](https://cloud.githubusercontent.com/assets/21123115/17807395/d682be30-663c-11e6-9efa-fc7d91c031da.jpg)
![13909261_10153964866132572_7003035119729769236_o](https://cloud.githubusercontent.com/assets/21123115/17807398/d86892a6-663c-11e6-8087-f1af2df64502.jpg)
![13995634_10153964865832572_7137863744531244187_o](https://cloud.githubusercontent.com/assets/21123115/17807401/da082d88-663c-11e6-9709-f96f7d88f9e2.jpg)

Just look at the images! Even the police have to be called in!

**Comment by paulyow100** [comment]
I try it but alwaus poke stop without poke ball. No pokemkn catch haha

**Comment by SaveOlafPlease** [comment]
Then most likely your bag is full if the pokestop has no awarded items

**Comment by paulyow100** [comment]
Its clean. Im already 39.
