### ISSUE TITLE
request for next update

### ISSUE THREAD

**Issue by dwinydaine** [gosimulate/gosimulator#339]
Im using latest version for sniping pokemon with the custom route feature when im rest the bot
Just editing the file .txt in custom route with the position of pokemon that u want to snip with pokemon map live (like pokemap live) and copy location in ur custom route txt. Save. Then start the bot
(Im boting in newyork, and snip in newyork too to avoid a perm banned)

I hope in the next update there are feature for single line route for snip pokemon without editing txt file
Like searching location in gps :)
Thx dev

Sorry for my bad english

**Comment by Freshink808** [comment]
I doubt sniping will be added because of how easily you can be banded/detected.

**Comment by manor7777** [comment]
+1 @Freshink808 @dwinydaine I doubt this will be added, the goal of the bot is to get levels and xp, and **NOT** get banned.

**Comment by dwinydaine** [comment]
Oh thanx for great explanation @manor7777 and @Freshink808 bro :) 
1 question, is it safe when im start and stop the bot with fast interval? (Like : 5minutes im start stop the bot 10time maybe) ? Or i must waiting for hours to start it again when i get error like "cant catch pokemon" ?

Thx for the dev and all member :)

**Comment by narutouchi55** [comment]
You can use the PokeSniper app to snipe pokemons.
