### ISSUE TITLE
Singapore Route - Botanic Gardens (PokeStop Every 10 steps, Lots of Dratini, Magikrap & Rare Pokemons)

### ISSUE THREAD

**Issue by SaveOlafPlease** [gosimulate/gosimulator#340]
[Botanic_Gardens_V2.txt](https://github.com/gosimulate/gosimulator/files/426858/Botanic_Gardens_V2.txt)

**Comment by SaveOlafPlease** [comment]
http://www.gpsvisualizer.com/display/20160819044011-40051-map.html

**Comment by SaveOlafPlease** [comment]
`http://www.gpsvisualizer.com/display/20160819044011-40051-map.html`

**Comment by SaveOlafPlease** [comment]
[http://www.gpsvisualizer.com/display/20160819044011-40051-map.html](url)

**Comment by SaveOlafPlease** [comment]
<http://www.gpsvisualizer.com/display/20160819044011-40051-map.html>

**Comment by SaveOlafPlease** [comment]
![screen shot 2016-08-19 at 7 54 18 pm](https://cloud.githubusercontent.com/assets/21123115/17809095/c1eb6a6c-6646-11e6-966b-46ac2c66532e.png)

**Comment by SaveOlafPlease** [comment]
Any issues so far?

**Comment by tsalcazar** [comment]
I started using it an hour ago.  So far so good.  I can confirm there are some good pokemon here....Lots of Voltorb, few Nidoran, Exeggcute, Staryu, Jigglypuff and Magikarp.

**Comment by tampororut** [comment]
No dratinis hehe lot of pokeballs

**Comment by tsalcazar** [comment]
Stopped for a bit, came back and first thing I caught was a Dratini.

**Comment by tsalcazar** [comment]
I think this is a Voltorb nest.

**Comment by juanxito91** [comment]
I've tested during a few and I haven't found anything interesting....

But yes, looks like is a Voltorb nest :-)
