### ISSUE TITLE
Are the pokestops in the routes live?

### ISSUE THREAD

**Issue by SaveOlafPlease** [gosimulate/gosimulator#345]
For example if you're route is filled with pokestops filled with lure, will it affect the catch rate?
I need to know as I am planning a route for Orchard Road Singapore. 
Also the shopping malls in orchard road are releasing hundreds of lures to attract shoppers.

[http://www.todayonline.com/tech/hundreds-pokemon-go-lures-be-released-ion-orchard]
![cplcpwnvuaqt3lx](https://cloud.githubusercontent.com/assets/21123115/17810124/c011e9b2-664d-11e6-9ec5-29bc7562f3c8.jpg)

**Comment by tampororut** [comment]
Can u make me a route orchard hehe

**Comment by narutouchi55** [comment]
Yes, its like you are using the PoGo app but instead you are using a bot.

**Comment by SaveOlafPlease** [comment]
@narutouchi55 so that means catch rate will increase?

**Comment by narutouchi55** [comment]
@SaveOlafPlease it should

**Comment by gr33nd3v1l** [comment]
Why is this labeled route
