### ISSUE TITLE
Niantic - Emails for banned Accounts.

### ISSUE THREAD

**Issue by roofyoreppin** [gosimulate/gosimulator#347]
Has anybody recieved an email from niantic confirming their ban? Its been 2 days and i still havent recieved mine, stuck at failed to get game data from the server.

**Comment by D3vr04** [comment]
Still none for me.

**Comment by zakydudutz** [comment]
me too failed to get game data from the server. :v 
and not yet recieved email from niantic.

**Comment by tampororut** [comment]
All u guys are perma banned hehe

**Comment by roofyoreppin** [comment]
If you dont have any usefull information do not comment

**Comment by tampororut** [comment]
Haha thats too usefull u know ill tell the truth that u are banned no need to wait email confirmation on niantic hahaha

**Comment by rgdwz** [comment]
Agree
