### ISSUE TITLE
Can catch pkmn on official, but simluator says im banned on loggin?

### ISSUE THREAD

**Issue by dewbus** [gosimulate/gosimulator#350]
I turned on simulator today and after logging in it said i was "probably banned and.... try logging in to official." So I logged on first w/o gps then with gps and both times I got in. When I had gps on, I caught a pidgeotto so clearly I'm not banned :)

Just wondering if theres a hold on 1.10.4 or something?

**Comment by gosimulate** [comment]
close app, clean data, restart app

**Comment by Freshink808** [comment]
You just need to press start again on the gosim app, it seems to be a minor bug. That usually pops up saying your banned, but your not unless you press start again and you keep getting that same message.
