### ISSUE TITLE
"Failed to login. your acoount is probably banned"

### ISSUE THREAD

**Issue by gengchu** [gosimulate/gosimulator#351]
This keeps on appearing but my account does still works on the real PoGo account.

**Comment by gengchu** [comment]
Anyone? Solutions?

**Comment by tampororut** [comment]
Clear data ur gobot and retype ur username and password correctly

**Comment by NextLineLife** [comment]
Seems like a "bug". 

I got a clean install and install as a system app. 

I always get the message on the first try. 
Second try always said i logged in successfully.

**Comment by Freshink808** [comment]
Gosim has seems to have a minor bug with this. All you have to do is when the message pops up saying your probably banned you just have to press start again. Now if you press start again and you get the same message over and over and you can't login on pogo your probably banned.
