### ISSUE TITLE
ver 1.10.4

### ISSUE THREAD

**Issue by mran2ny** [gosimulate/gosimulator#352]
whats on the ver 1.10.4? normally he mention whats inside the updates..

**Comment by manor7777** [comment]
Probably bug fixes and anti-ban fixes. Closed

**Comment by narutouchi55** [comment]
@mran2ny Better translations.

**Comment by mran2ny** [comment]
just translation?

**Comment by narutouchi55** [comment]
@mran2ny yes. Join the gosim forum:  http://gosimulator.boards.net
