### ISSUE TITLE
route request

### ISSUE THREAD

**Issue by bonez0129** [gosimulate/gosimulator#356]
can anyone make a route.txt for mandaluyong, philippines?

thanks

**Comment by gedoyz** [comment]
Request there #195

**Comment by Kennypahenri** [comment]
@bonez0129,

You can request there #195 

Give me the park or city to plot, and i will make a basical plot. Then, the post owner makes the 5 meters plot that you need to put in GoSimulator.

Regards!

**Comment by bonez0129** [comment]
mandaluyong city philippines

@kennypahenri
dont know how to get the map.

**Comment by Kennypahenri** [comment]
Don't care, ill get the map and plot it ;)

Go to post #195. I'll upload the plot there ;)

**Comment by narutouchi55** [comment]
Request here #195

**Comment by bonez0129** [comment]
thanks a lot sir.
