### ISSUE TITLE
Bot is on but shows as if its stopped

### ISSUE THREAD

**Issue by neospeed83** [gosimulate/gosimulator#358]
Attached ss. 
Bot on from 3 hrs
It's working correctly but it UI shows that its off.
P.s how do i attach screenshots?

**Comment by Kennypahenri** [comment]
PD: If you want Custom Maps, you can request there #195.

![screenshot_3](https://cloud.githubusercontent.com/assets/21104948/17817052/59298298-660a-11e6-8c97-a1005061e9b9.png)

**Comment by narutouchi55** [comment]
@Kennypahenri he dindt ask for a custom map

**Comment by Kennypahenri** [comment]
Edited!
