### ISSUE TITLE
Suggestions for this app

### ISSUE THREAD

**Issue by xgil** [gosimulate/gosimulator#359]
It would be very useful an option just to loot pokestops (no transfers/evolve/catch pokemons). This app is awesome, and I would like this feature for people like me with no option to access pokestops nearly. I would like to play the game normally but it’s very difficult to get pokeballs. Thanks in advance.

**Comment by gosimulate** [comment]
Please dont ask me about this feature anymore. There is workarround to make this:

1. Go to single pokemon settings, turn of catch pokemons!
2. Turn transfer off
3. Turn evolve off.
4. Save for all !!!!
