### ISSUE TITLE
1.11.0

### ISSUE THREAD

**Issue by NextLineLife** [gosimulate/gosimulator#362]
Stops as soon as i press start.

**Comment by paulopogi** [comment]
Banned account, if you'rr using google account check the is google account beta testing or route problem

**Comment by tfc20160801** [comment]
Where is the link for 1.11? What were the changes?

**Comment by manor7777** [comment]
@tfc20160801 everything is moved here: http://gosimulator.boards.net/thread/2/download-1-11

Closed
