### ISSUE TITLE
Singapore Route - Japanese Gardens (40 Pokestops, Growlithes Nest & Rare Arcanine)

### ISSUE THREAD

**Issue by SaveOlafPlease** [gosimulate/gosimulator#365]
[Japanese_Gardens.txt](https://github.com/gosimulate/gosimulator/files/428008/Japanese_Gardens.txt)
This place has an opening and closing time of 5.30 am - 7 pm  and it is so popular among Singaporeans that people tried to break into the garden at night!!! You will find a lot of Growlithes which you can use to evolve to Arcanine!
![20160818_japgarden_wb](https://cloud.githubusercontent.com/assets/21123115/17826421/3bfa7b02-66a3-11e6-97e2-dc045806dfe3.jpg)
![screen shot 2016-08-20 at 6 51 52 am](https://cloud.githubusercontent.com/assets/21123115/17826424/44f491de-66a3-11e6-8a70-d8a5917664bc.png)

**Comment by gosimulate** [comment]
use forum please
