### ISSUE TITLE
Need help with a setting/Getting No Pokeballs left

### ISSUE THREAD

**Issue by kurtsky** [gosimulate/gosimulator#366]
I got the error.
Failed to catch, no pokeballs left.
How do make the bot just go to pokestops and not catch?

**Comment by narutouchi55** [comment]
![screenshot_20160820-030550](https://cloud.githubusercontent.com/assets/21021007/17827765/0abd3d42-6683-11e6-8b73-f87be42c00b3.png)
Next time use the new forum: http://gosimulator.boards.net

**Comment by kurtsky** [comment]
Thanks Heaps!
