### ISSUE TITLE
MallOfAsia_Philippines

### ISSUE THREAD

**Issue by lance2cool** [gosimulate/gosimulator#371]
14.541583,120.980289
14.54155,120.98024
14.54152,120.980199
14.541504,120.980139
14.541533,120.98008
14.54154,120.980018
14.541522,120.979957
14.541498,120.979898
14.54147,120.979832
14.541444,120.97976
14.541421,120.979701
14.541409,120.979627
14.541419,120.979548
14.54141,120.979485
14.541389,120.979435
14.541365,120.979381
14.541355,120.979325
14.541321,120.979275
14.541292,120.979231
14.541273,120.979178
14.541241,120.979129
14.541211,120.979076
14.54118,120.979019
14.541151,120.978967
14.541111,120.978897
14.541078,120.978945
14.541035,120.978995
14.54099,120.97904
14.540938,120.979054
14.540868,120.979053
14.540811,120.979053
14.540744,120.979064
14.540683,120.97907
14.540616,120.979068
14.540551,120.979062
14.540487,120.979061
14.54042,120.979063
14.540351,120.979067
14.540288,120.979069
14.540225,120.979073
14.540157,120.979075
14.540088,120.979078
14.540015,120.979083
14.539943,120.979091
14.539869,120.9791
14.539796,120.979108
14.539721,120.979116
14.539653,120.979116
14.539597,120.979111
14.539536,120.9791
14.539476,120.97909
14.539403,120.979104
14.539328,120.979111
14.539268,120.979096
14.539162,120.979092
14.53911,120.979087
14.539059,120.979083
14.539001,120.979081
14.538949,120.979082
14.538887,120.979085
14.538831,120.97908
14.538755,120.97908
14.538698,120.979088
14.538645,120.979094
14.538591,120.979094
14.538527,120.979102
14.538461,120.97912
14.538398,120.979125
14.538337,120.979133
14.538261,120.979135
14.538191,120.979135
14.538113,120.979138
14.538056,120.979137
14.537989,120.979143
14.537925,120.979143
14.537858,120.979135
14.537796,120.979121
14.537729,120.979103
14.537682,120.979098
14.537588,120.979101
14.537531,120.979108
14.537468,120.979114
14.53742,120.97911
14.537363,120.979117
14.537308,120.979125
14.537241,120.979135
14.537172,120.979139
14.537118,120.979146
14.537052,120.979145
14.536988,120.979134
14.536919,120.979137
14.536867,120.979143
14.536806,120.979151
14.536749,120.979153
14.536703,120.979155
14.536648,120.979202
14.536601,120.979142
14.536538,120.979139
14.536482,120.979147
14.536443,120.979145
14.536406,120.979129
14.536337,120.979134
14.536264,120.979161
14.536186,120.979176
14.536103,120.97918
14.536047,120.979169
14.535983,120.979176
14.535931,120.979204
14.535859,120.97921
14.53579,120.979202
14.535703,120.979217
14.535659,120.979198
14.535615,120.97918
14.535575,120.979164
14.535535,120.979159
14.535461,120.979159
14.535409,120.979164
14.535344,120.979176
14.535269,120.979182
14.535195,120.979177
14.535152,120.979161
14.535098,120.979167
14.535048,120.979168
14.534996,120.979169
14.534944,120.979176
14.534881,120.97919
14.534817,120.9792
14.534758,120.97921
14.534706,120.979216
14.534658,120.979228
14.534607,120.979222
14.534558,120.979226
14.534506,120.97923
14.534464,120.979246
14.534418,120.979221
14.53437,120.979192
14.534309,120.979198
14.534266,120.979239
14.534209,120.979255
14.534155,120.979268
14.5341,120.979263
14.534046,120.979232
14.53399,120.979208
14.533927,120.97921
14.533868,120.979241
14.533805,120.979247
14.533761,120.979249
14.533727,120.979243
14.533649,120.979243
14.533608,120.979251
14.533536,120.979263
14.533483,120.979257
14.533415,120.97925
14.533369,120.979264
14.533319,120.979257
14.533256,120.979257
14.533195,120.979264
14.533144,120.979273
14.533093,120.979267
14.533028,120.979276
14.532966,120.979287
14.532921,120.979297
14.53286,120.9793
14.5328,120.979296
14.532729,120.979304
14.532683,120.979314
14.532636,120.979321
14.532588,120.979319
14.532528,120.9793
14.532512,120.97932
14.53245,120.979314
14.532407,120.979316
14.532368,120.979312
14.53232,120.979309
14.532266,120.979306
14.53222,120.979306
14.532174,120.979308
14.532124,120.979307
14.532078,120.979308
14.53203,120.97931
14.531978,120.979318
14.531934,120.979325
14.531897,120.979328
14.531853,120.979324
14.531787,120.979332
14.531739,120.979338
14.531681,120.979348
14.531627,120.979343
14.531577,120.979349
14.531538,120.979351
14.531497,120.979359
14.531449,120.979363
14.531395,120.979361
14.531341,120.979361
14.531304,120.979356
14.531235,120.979348
14.531177,120.979359
14.531117,120.979356
14.531035,120.979353
14.530984,120.979367
14.530936,120.979367
14.530886,120.979383
14.530836,120.979454
14.530799,120.979534
14.530772,120.979623
14.530721,120.979691
14.530667,120.979749
14.530616,120.979816
14.530598,120.979888
14.530583,120.979943
14.530565,120.98002
14.530547,120.980093
14.530544,120.980187
14.530532,120.980246
14.530522,120.980323
14.530509,120.980407
14.530504,120.980497
14.530498,120.980565
14.530496,120.980647
14.530505,120.980737
14.530509,120.980821
14.530509,120.980905
14.530506,120.980994
14.530502,120.981074
14.530498,120.981166
14.530493,120.981248
14.530489,120.981317
14.530483,120.981388
14.530478,120.981459
14.530467,120.981603
14.530461,120.981654
14.530476,120.981714
14.530509,120.98179
14.530533,120.981856
14.530543,120.981912
14.530541,120.981961
14.530546,120.982021
14.530559,120.982072
14.530622,120.982103
14.530698,120.982099
14.530766,120.982088
14.530838,120.982086
14.53089,120.982066
14.530928,120.982072
14.530981,120.982068
14.53104,120.98207
14.531116,120.982076
14.531195,120.982078
14.531248,120.982082
14.53132,120.982086
14.531393,120.982084
14.531464,120.98208
14.531477,120.982059
14.531493,120.98206
14.531512,120.982066
14.531529,120.982078
14.531553,120.982081
14.531576,120.982086
14.531604,120.982084
14.531639,120.982081
14.531674,120.982082
14.531713,120.982083
14.531752,120.982076
14.531797,120.982079
14.531845,120.982079
14.531896,120.982069
14.531939,120.982068
14.531941,120.98207
14.531967,120.982065
14.53199,120.982068
14.532013,120.982068
14.532045,120.982068
14.532076,120.982067
14.532111,120.982061
14.532155,120.982057
14.532193,120.982062
14.532242,120.982056
14.532285,120.982057
14.532327,120.982062
14.532373,120.982067
14.532421,120.982068
14.532472,120.982064
14.532522,120.982051
14.532546,120.982047
14.532583,120.982047
14.532625,120.982047
14.532672,120.982046
14.532723,120.982043
14.532777,120.982033
14.532829,120.982029
14.532895,120.98202
14.532953,120.982026
14.533013,120.982028
14.533069,120.982025
14.533121,120.982023
14.533186,120.982021
14.533252,120.982015
14.533321,120.982009
14.533386,120.982002
14.533455,120.981994
14.533531,120.981987
14.533613,120.98198
14.533689,120.98197
14.533755,120.981964
14.533836,120.981954
14.53391,120.981954
14.533979,120.981948
14.534033,120.981944
14.534109,120.981939
14.534179,120.981929
14.534253,120.981922
14.534346,120.981897
14.534394,120.981892
14.534461,120.981892
14.534529,120.981885
14.534592,120.981891
14.534618,120.981893
14.534647,120.981893
14.534703,120.981889
14.534734,120.981886
14.534764,120.981881
14.534803,120.981865
14.534864,120.981859
14.534932,120.981856
14.534995,120.981862
14.53506,120.981862
14.535114,120.981858
14.535173,120.981854
14.535235,120.981847
14.535293,120.981844
14.535346,120.981858
14.535386,120.981872
14.535435,120.981883
14.535489,120.981888
14.535537,120.981878
14.535578,120.981855
14.535638,120.981848
14.535699,120.981848
14.535752,120.981856
14.535809,120.981867
14.535844,120.981872
14.53589,120.981878
14.535948,120.981877
14.535994,120.981872
14.536019,120.98184
14.536033,120.981787
14.536041,120.981746
14.53605,120.981681
14.536052,120.98162
14.536051,120.98161
14.536041,120.981561
14.536035,120.981503
14.536041,120.981452
14.536048,120.981387
14.536046,120.981326
14.536043,120.981258
14.536046,120.981206
14.536046,120.981154
14.536047,120.981099
14.536052,120.981026
14.53608,120.980947
14.536113,120.980887
14.536143,120.980842
14.536136,120.980778
14.536089,120.980763
14.536033,120.98076
14.535969,120.980753
14.535958,120.980696
14.535946,120.980634
14.535931,120.98058
14.535913,120.980521
14.535909,120.980468
14.535902,120.980399
14.53589,120.980363
14.535585,120.980553
14.535549,120.980549
14.535498,120.980546
14.535457,120.980549
14.53541,120.980563
14.535361,120.980574
14.535312,120.980574
14.535259,120.980574
14.535208,120.980576
14.535143,120.980573
14.535085,120.980573
14.535005,120.980576
14.534967,120.980569
14.534917,120.980566
14.534856,120.98057
14.534791,120.980566
14.534736,120.980559
14.534675,120.980557
14.534612,120.980552
14.53455,120.980546
14.534505,120.980541
14.534439,120.980532
14.534386,120.980515
14.53432,120.980519
14.53426,120.980513
14.534181,120.980507
14.534127,120.980507
14.534074,120.980505
14.534075,120.980442
14.534017,120.980444
14.533942,120.980444
14.533855,120.980446
14.53377,120.980446
14.533692,120.980452
14.53361,120.980457
14.533524,120.980459
14.533519,120.980458
14.533445,120.980467
14.533374,120.980472
14.533306,120.980472
14.533237,120.980474
14.533173,120.980483
14.533115,120.980476
14.533047,120.980479
14.532967,120.980492
14.532958,120.980548
14.532964,120.980606
14.532969,120.980702
14.532977,120.980814
14.532973,120.980907
14.532973,120.981007
14.53298,120.981122
14.532985,120.981221
14.532923,120.981204
14.532869,120.98115

**Comment by kurtsky** [comment]
How do I add these to the bot?
