### ISSUE TITLE
[ROUTE]: Split, Croatia

### ISSUE THREAD

**Issue by gr33nd3v1l** [gosimulate/gosimulator#41]
[Split_Old.City.Core_Croatia.txt](https://github.com/gosimulate/gosimulator/files/417254/Split_Old.City.Core_Croatia.txt)

Old City core is almost always 24\7  lured

**Comment by gr33nd3v1l** [comment]
![capture](https://cloud.githubusercontent.com/assets/3631381/17649646/87256528-623a-11e6-81ae-d3e7fd088885.PNG)

**Comment by xitopodo** [comment]
I've been there in holidays, so, I wanna try if it's true if we can catch lured pokemons there :tongue:

**Comment by xitopodo** [comment]
Well, not bad. I used 2 times because it's short route and:
-Abra
-Mr. Mime
-Haunter
-Venusaur
-Scyther

I will try more times, but looks true what did you say :stuck_out_tongue:
