### ISSUE TITLE
Another Suggestions.

### ISSUE THREAD

**Issue by myhadhy** [gosimulate/gosimulator#42]
1. Please add a feature to not transfer High IV pokemons, somehow at top level we prioritize IV over CP. 
2. A favourite pokemon shouldn't get transferred, i just found out my Dratini IV 100% with low CP has been transferred although i toogled Favourite to it.
3. If possible it would be great if we can save a setting, so we don't start at beginning when we reinstall or clear data.

**Comment by scissors14** [comment]
Say u find a ev with 100iv.. if you evolve it will the iv say the same?

**Comment by myhadhy** [comment]
IV will never change dude, it's like the talent of our pokemon. :)
