### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by madmappers** [gosimulate/gosimulator#43]
Since great balls and ultra balls aren't used by bot as of yet why not an option to discard like potions for time being unless a fix is planned

**Comment by myhadhy** [comment]
Ah i like this. If possible we also can manage maximum number of Potions, Balls, and Revives so if it reach the maximum numbers it will be deleted automatically.

**Comment by MrPokemon** [comment]
I was also thinking having a option to use a lure at a set time

**Comment by gr33nd3v1l** [comment]
#23
