### ISSUE TITLE
[bug]  IV toggles not sticking 

### ISSUE THREAD

**Issue by VernMcC** [gosimulate/gosimulator#45]
Using 1.7
When I slide the iv toggle on Pokemon settings,  enter a value and hit save or save for all,  then open up a Pokémon the iv sliders are off,  but the values are there. 

For example,  I slide the toggle evolve over 90 iv,  clicked save. Then reopened the same Pokémon and the 90 was the value,  but the slider for iv was off and the wording appeared to be associated with cp for evolve,  not iv.

**Comment by dewbus** [comment]
Trying doing a fresh reinstall of 1.70, I have a issue listed. It might help you out and worst comes you can just download your previous version.

**Comment by VernMcC** [comment]
Dewbus,  thanks.  Do the toggles stay for you with by iv on?

**Comment by dewbus** [comment]
They don't. Maybe its as simple as a line of code.

**Comment by VernMcC** [comment]
I just tested,  with evolve by iv set to 90 and transfer by iv less than 90. I then selected save for all. If I click on a Pokémon in settings it will not show the iv settings toggled.  However when the bot gets to the evolve transfer phase it is transferring critters with cp over 90 but with iv less than 90, so I think it is working., the toggles are just not sticking.

**Comment by gosimulate** [comment]
Fixing it right now, its just UI issue. Thy

**Comment by gosimulate** [comment]
fixed
