### ISSUE TITLE
Unable to use "Save For All Pokemons" in 'Pokemon Settings'

### ISSUE THREAD

**Issue by dewbus** [gosimulate/gosimulator#46]
Upgraded from 1.3>...>1.60>1.70

Woulnd't let me use Save For All Pkmns

FIXED: Uninstalled the app completely, and installed 1.70 fresh, works now

**Comment by VernMcC** [comment]
If you set by iv,  do the toggles stay?  I have Uninstaller and installed 1.7 twice and don't get the iv toggle to stick, but I can update the threshold values with save or save for all.

**Comment by dewbus** [comment]
The toggles do stay...

However (and I'm testing this now) the bot just starts and sits there now. I just rebooted my phone gimme 2seconds.

**Comment by dewbus** [comment]
It works now, just caught a Goldeen. And IV Values Saved

**Comment by VernMcC** [comment]
If the bot is not moving,  look for adblocker conflict. The author added ad blocker to v1.5 but quickly rolled out 1.6 and 1.7 so I think most missed that.

**Comment by VernMcC** [comment]
Thanks

**Comment by dewbus** [comment]
Actually nope, the toggles dont save sorry. Idk

**Comment by gosimulate** [comment]
its just UI issue, fixing it right now !
