### ISSUE TITLE
Issue Bot speed 

### ISSUE THREAD

**Issue by madmappers** [gosimulate/gosimulator#47]
Can we tweak the speed to be slower?  I've noticed and believe the error something happened when catching pokemon is due to the 10 sec refresh for pokemon to appear in game.  If bot moves too fast the PM won't spawn

**Comment by madmappers** [comment]
Just zoomed in and on slow speed bot stays in one place for 3-4secs

**Comment by madmappers** [comment]
Make slow like 25 secs medium 15 high 10 before moving on to next coordinate will maxmize pull potential.  It's like being in a car now ever since they changed refresh rates if going too fast you miss everything until you slow down

**Comment by gosimulate** [comment]
Will make it all configurable at ur own

**Comment by madmappers** [comment]
Awesome looking forward to it keep up good work

**Comment by gr33nd3v1l** [comment]
#23
