### ISSUE TITLE
Adblocker info

### ISSUE THREAD

**Issue by VernMcC** [gosimulate/gosimulator#49]
Can we get the sites we need to whitefish in our adblockers? I don't want to leave add blocking off on my system, but am fine to white list sites your app uses until I decide to buy.

**Comment by gosimulate** [comment]
I cant answer u that since i have no idea.

**Comment by VernMcC** [comment]
K,  Thank you.  I will check network traffic and see if I can figure it out.

**Comment by VernMcC** [comment]
I tried to do it by allowing all of the app ads but it did not work.  Tcpdumping all the traffic the app makes and white listing DNS in adaway did not let me keep adaway turned on while using the app.  I got all the same ads,  but the app still complained I was running an ad blocking and would not move the avatar.
