### ISSUE TITLE
[ROUTES] Faulty routes and bad routes 

### ISSUE THREAD

**Issue by djfaizp** [gosimulate/gosimulator#50]
Guys please click coordinates care fully if one of the wrong click will make huge difference in route it will bounce there and as some of are selecting coordinates wrong as it was happed with me ... So select coordinates closely as human foot.. Use 21 zoom and before start coordinating alow map to load as some route are jumping to much and some route are become short due to over laping of route

**Comment by gr33nd3v1l** [comment]
Please report faulty routes here.

**Comment by faizmodan** [comment]
Lilidale lake Melbourne at end point jumping and jumping,st paul downtown mn usa i will tell you other route here later and i suggest you to make routes by ur self as some ppl are making routes for thair fun they don't care about ppl may get ban....etc

**Comment by faizmodan** [comment]
Victoria waterfront bc canada to much jumping

**Comment by faizmodan** [comment]
I will comment here more routes later please tell ppl that distance shold not more then 5 miter as it will also help ppl to set speed at medium and human can not catch pokemon at speed 20-40 m/s lol but its true

**Comment by benyaj** [comment]
I'll remake downtown st paul later today.. not effective as I originally planned. And yes too much jumping around.

**Comment by faizmodan** [comment]
Santa monica broadwalk but need to adjust with more poke shop to much jumping at start to risky if i will sleep after put it on as after reverse and Before reverse it will jump to much adjust routes guys and make it better as you should sense human can't jump like that

**Comment by benyaj** [comment]
[St_Paul_Downtown_MN_USA_Updated.txt](https://github.com/gosimulate/gosimulator/files/417285/St_Paul_Downtown_MN_USA_Updated.txt)

Updated Downtown St Paul

**Comment by faizmodan** [comment]
Ty @benyaj

**Comment by djfaizp** [comment]
Now. Can make own route no need this issue any more closing it
