### ISSUE TITLE
[ROUTE] - Durban Ushaka Marine World (Complete)

### ISSUE THREAD

**Issue by Morkai-bde** [gosimulate/gosimulator#52]
[Durban_Ushaka_South Africa.txt](https://github.com/gosimulate/gosimulator/files/416766/Durban_Ushaka_South.Africa.txt)

**Comment by gr33nd3v1l** [comment]
These jumps look to be 100m, refine your route

[<img src="http://i.imgur.com/VKCGJtL.png">](http://i.imgur.com/VKCGJtL.png)

**Comment by Morkai-bde** [comment]
I made sure each one was roughly 10m

![route](https://cloud.githubusercontent.com/assets/20994840/17645975/3ce9f278-61b6-11e6-9190-645df864f752.png)

**Comment by gr33nd3v1l** [comment]
This is over 200m
[<img src="http://i.imgur.com/bXvlSAv.png">]
