### ISSUE TITLE
[ROUTE]: Hong Kong, China (Farfetch'd nest)

### ISSUE THREAD

**Issue by gr33nd3v1l** [gosimulate/gosimulator#53]
[HONG KONG_VICTORIA HARBOUR_CHINA.txt](https://github.com/gosimulate/gosimulator/files/417229/HONG.KONG_VICTORIA.HARBOUR_CHINA.txt)

Very carefully made using pokemongomap to maximize pokestops. This one should be brutal.

![capture](https://cloud.githubusercontent.com/assets/3631381/17651650/d1dd0496-626b-11e6-9c53-f080fd718d33.PNG)

**Comment by MrHopsing** [comment]
Did you upload the wrong file? 
Seems like the coordinates are wrong, this is for Split, Croatia.

**Comment by gr33nd3v1l** [comment]
Oshit.. willfix
