### ISSUE TITLE
[ROUTE] Marikina River Philippines *Fixed*

### ISSUE THREAD

**Issue by Arclaynsoa** [gosimulate/gosimulator#56]
![capture](https://cloud.githubusercontent.com/assets/3631381/17651897/3c37bc2e-6270-11e6-9365-7a796b107fa6.PNG)
The earlier added route makes the application crash. figured that it may have been the route coordinates so I'm re-uploading it with a clearer set. Thanks!
[Marikina_River_Philippines.txt](https://github.com/gosimulate/gosimulator/files/416820/Marikina_River_Philippines.txt)

**Comment by gr33nd3v1l** [comment]
Rename to Marikina_Marikina River_Phillippines.txt

This is a fix by the original route creator

**Comment by Arclaynsoa** [comment]
Edit: Updated Txt File Name.
