### ISSUE TITLE
[ROUTE] - Puerto Madero , Argentina

### ISSUE THREAD

**Issue by topsonic** [gosimulate/gosimulator#57]
![capture](https://cloud.githubusercontent.com/assets/3631381/17651962/ab0bf592-6271-11e6-8422-7c483efc5a93.PNG)
[PuertoMadero_Argentina_v2.txt](https://github.com/gosimulate/gosimulator/files/417250/PuertoMadero_Argentina_v2.txt)

_edited_

**Comment by gr33nd3v1l** [comment]
add [ROUTE] PuertoMadera_Argentina to the first line

<img src="http://i.imgur.com/Vc4xyCN.png">
Looks to be just around one park
Is this worth a route?

**Comment by topsonic** [comment]
fixed it
it has lots of pokestops with lures. Dratini and pikachu spawn there every once in a while too

**Comment by Svenjorn** [comment]
Longer route around Puerto Madero (needs testing)
[PuertoMadero_Argentina_v2.txt](https://github.com/gosimulate/gosimulator/files/417137/PuertoMadero_Argentina_v2.txt)

**Comment by gr33nd3v1l** [comment]
Keep in mind first line needs to be empty for custom route
