### ISSUE TITLE
[ROUTES]: Tokyo, Japan (Nippon)

### ISSUE THREAD

**Issue by gr33nd3v1l** [gosimulate/gosimulator#60]
[Tokyo_Imperial Palace and Ginza_Japan.txt](https://github.com/gosimulate/gosimulator/files/417372/Tokyo_Imperial.Palace.and.Ginza_Japan.txt)

![capture](https://cloud.githubusercontent.com/assets/3631381/17652642/218cd76c-6282-11e6-8443-6531b0d2dc94.PNG)

HIGH YIELD
100 POKESTOPS
MAGIKARP, PSYDUCK, SLOWPOKE, THRASHMONS
_______________________________________
![capture](https://cloud.githubusercontent.com/assets/3631381/17653205/c35fae5c-6291-11e6-9a7e-e54deff9caf0.PNG)
[Tokyo_Prince park and Tokyo Tower_Japan.txt](https://github.com/gosimulate/gosimulator/files/417414/Tokyo_Prince.park.and.Tokyo.Tower_Japan.txt)

VERY BALANCED POKESTOP/CATCHRATE
HIGH EXP / HOUR
Possibly the best route so far. Still testing

**Comment by faizmodan** [comment]
Have you selected coordinates right as human foot now distances between one jump should not more then 3 Mitre as it is alway detected as ban (a new ban)

**Comment by gr33nd3v1l** [comment]
Distances between jumps are anywhere from 10 to 15 m

My routes are intended for SLOW setting or MEDIUM at most

**Comment by gr33nd3v1l** [comment]
Added another route. Should be lures and rare spawnes
