### ISSUE TITLE
[bug]  username field update

### ISSUE THREAD

**Issue by VernMcC** [gosimulate/gosimulator#63]
I mistyped my ptc account username and when I tried to start the bot I got the invalid credential log message.  I updated the user name and tried to restart,  but still got the invalid credentials log message.  I then force killed the app and restarted.  I was then able to authenticate successfully without further modifying the username other than the one fix.  It appears that updating this field after it is set does not use the new value to actually authenticste until the app reloads

**Comment by gr33nd3v1l** [comment]
You should restart the completely whenever you encounter a fatal error

**Comment by VernMcC** [comment]
I just want to make sure you understand the issue, so I didn't want to reopen one on github, but I think it might be part of the invalid credential reports users of the app have been making

- I clean installed the app
- I started the app
- I put in my PTC credentials but I mistyped my username (I also updated settings to add a route)
- I started a route
- The app issued a warning about authentication failure
- I checked my credentials and noted the typo
- I fixed the typo
- I tried to start the route but got the same authentication error
- I double checked my credentials (they were right this time)
- I exited the app (close all)
- I started the app
- I tried to start the route but got the authentication failure message
- I force killed the app
- I started the app
- I tried to start the route and it began

I think the issue is there is some memory resident storage that has the initial value of the username field and it only updates from a fresh restart or when initially set. Not a big deal, but considering how many times people have been reporting authentication issues, this could be a contributing cause. Even if they update correctly, they either need to force kill the app or they need to reboot the device to get the updated value in the field to be the value offered during authentication.
