### ISSUE TITLE
Bot doesn't work when running in the background 

### ISSUE THREAD

**Issue by skidiiot** [gosimulate/gosimulator#64]
I've introduced my sister to the bot and she has a Galaxy S6 (Verizon). The app works when it's the currently present one running on screen, but whenever she goes to another app or her home screen and goes back to the app, all she sees is 'Something went wrong while catching pokemon etc.' Any help would be appreciated as its sucking having to only be in the app and have the phone screen on to run.

**Comment by afarinah1234** [comment]
Read readme at first page. You need install it in system app otherwise it is not working.

**Comment by skidskidskidiot** [comment]
Don't see why I'd need to do that as it runs just fine on my Galaxy S7 as a regular 3rd party app + she wouldn't want to root her phone

**Comment by roofyoreppin** [comment]
Rooting is very easy, i did it on my galaxy s4 mini specifically so i can run the bot as a system app and its deffo worth doing

**Comment by gr33nd3v1l** [comment]
skid i am using s5 and rarely this happens in background

is the phone debloated? does some app take priority over
