### ISSUE TITLE
i have a question sorry for being inosent

### ISSUE THREAD

**Issue by byungaw031** [gosimulate/gosimulator#65]
my i know what is the purpose of new update this one " lV"?
for the example lV:76%
thank you for the very good application :+1:

**Comment by Morkai-bde** [comment]
IV's are pokemon's Individual Values, it is a bunch of hidden stats that determine how strong a pokemon is, eg, a pokemon with an IV of 80% is way better than one with 30%
it is calculated according to 3 stats, Attack, Defense, and Stamina of which all 3 has a value from 0 to 15

**Comment by byungaw031** [comment]
owww. i see thanks to this app :+1:
