### ISSUE TITLE
[ROUTE] MEMORAL_PARK_HOUSTON_TX

### ISSUE THREAD

**Issue by oriax123** [gosimulate/gosimulator#66]
[ROUTE] MEMORAL_PARK_HOUSTON_TX

http://www55.zippyshare.com/v/oqToYn5E/file.html

**Comment by gosimulate** [comment]
Please attach file here, do not post mirror links.

**Comment by gr33nd3v1l** [comment]
[Houston_MemorialPark_USA.txt](https://github.com/gosimulate/gosimulator/files/417034/Houston_MemorialPark_USA.txt)

Looks fine

![capture](https://cloud.githubusercontent.com/assets/3631381/17649341/4dae361e-6233-11e6-985f-f5d956e6fc50.PNG)

**Comment by luway65** [comment]
What kind of spawns are there here? And how many pokestop are there?
