### ISSUE TITLE
what is this NEW BAN of POGO ?

### ISSUE THREAD

**Issue by byungaw031** [gosimulate/gosimulator#67]
i`m confused with this two types of ban this SOFT BAN and the NEW BAN? can any one explain to me what is the difference with this two ban?
i know what is soft ban is but the NEW BAN i`m still confused with this new ban, other said its permanent ban and the other said the ban is for 8hours only. 
i hope guys you can help me THANK YOU !

**Comment by afarinah1234** [comment]
Softban: 
-Unable to catch pokemon(always runaway)
-Unable to loot poke stop
To unban just spin 30-50 times

New ban: IP ban
Unable to see pokemon, pokestop, gym
To unban wait for 8-24hours(not sure about this)

**Comment by byungaw031** [comment]
I hope your right because may main account i cant opennit i think its new ban.

**Comment by gr33nd3v1l** [comment]
There is also the freeze ban. You can loot pokestops but pokemon flee. 12-24h
