### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by MrPokemon** [gosimulate/gosimulator#68]
The app keepz hits pokestops, not collecting anything and not catching any pokemon on The new realease and 1.6

**Comment by byungaw031** [comment]
try to uninstall the go sim and re install it

**Comment by MrPokemon** [comment]
I have 3 times i dont know whats going is it working for yall?

**Comment by byungaw031** [comment]
Yeah! Its working. Uninstall the go sim and restart your phone. And then install the go sim 1.7 makr sure that its thr latest version

**Comment by gr33nd3v1l** [comment]
Read the README.md

It should fix your problem and answer your questions
