### ISSUE TITLE
[ROUTE] Samar, Philippines

### ISSUE THREAD

**Issue by siegetank999** [gosimulate/gosimulator#69]
[calbayog_proper_samar_philippines.txt](https://github.com/gosimulate/gosimulator/files/416901/calbayog_proper_samar_philippines.txt)

**Comment by gr33nd3v1l** [comment]
Looks okay i guess
![capture](https://cloud.githubusercontent.com/assets/3631381/17649328/ecb8fbaa-6232-11e6-84ac-874d57378173.PNG)

**Comment by kurogemz** [comment]
can someone help me??? tried to make route for baguio city burnham but looks like i failed... thanks

**Comment by kurogemz** [comment]
[Baguio_Burnham_lake_Bunguet_philippines.txt](https://github.com/gosimulate/gosimulator/files/417689/Baguio_Burnham_lake_Bunguet_philippines.txt)

is that right?

**Comment by gr33nd3v1l** [comment]
pretty short but looks fine
![capture](https://cloud.githubusercontent.com/assets/3631381/17661243/3f31a8f4-62de-11e6-88f4-771c74cc6fdd.PNG)

**Comment by rockybalbon027** [comment]
Create me the route around mall of asia phillipines. And around quezon city circle ty

**Comment by JuanTheGreat** [comment]
can you create route in Bonifacio Global City??? there are sightings of Blastoise and onix there. Also in pasig river makati lots of magikarp and dratini

**Comment by kraynorgrey** [comment]
![2016-08-19_211449](https://cloud.githubusercontent.com/assets/21125468/17810976/d5826a74-6652-11e6-9df3-3f03c395a3b4.jpg)
i agree with JuanTheGreat, i recommend this route in bonifacio global city, lots of statues, artworks as pokestops, and heard lotsof good pokemons there. please make one.

**Comment by kraynorgrey** [comment]
route looks like this.. at present
![2016-08-19_213736](https://cloud.githubusercontent.com/assets/21125468/17811418/44039106-6655-11e6-925f-ed44663a1e05.jpg)
