### ISSUE TITLE
[ROUTE] Nha Trang Beach, Vietnam

### ISSUE THREAD

**Issue by ptanhkhoa** [gosimulate/gosimulator#71]
Nha Trang is a famous city in Vietnam that attract tourist from over the world, so there are a lot of poke stop and Gym along the beach, i create a path that travel most poke stop along the beach :). 
[NhaTrang_ThapTramHuong_KhanhHoa_Vietnam.txt](https://github.com/gosimulate/gosimulator/files/416918/NhaTrang_ThapTramHuong_KhanhHoa_Vietnam.txt)

**Comment by gr33nd3v1l** [comment]
Read the #35 ROUTE tutorial and add it to the first line

![capture](https://cloud.githubusercontent.com/assets/3631381/17648688/ce49b88a-621e-11e6-9cd3-8bf85077da3f.PNG)

otherwise, looks fine :)

**Comment by ptanhkhoa** [comment]
thanks for fixing it xD, i forget
