### ISSUE TITLE
can not save in pokemon setting

### ISSUE THREAD

**Issue by insider111** [gosimulate/gosimulator#73]
Where save button ?

**Comment by gr33nd3v1l** [comment]
SCREENSHOT PLEASE

**Comment by insider111** [comment]
Ss http://imgur.com/f8xJFEf

**Comment by onur9605** [comment]
Settings/Screen ,  enable turn automatically. 
Open gosim/ Pokemon settings / choose any Pokemon and rotate screen

**Comment by insider111** [comment]
Thanks
