### ISSUE TITLE
[ROUTE] - Stockport_England_Updated

### ISSUE THREAD

**Issue by roofyoreppin** [gosimulate/gosimulator#75]
This is the updated stockport route for england which now has twice as many pokestops and a more stable path.
[stockport_england_updated.txt](https://github.com/gosimulate/gosimulator/files/416995/stockport_england_updated.txt)

**Comment by gr33nd3v1l** [comment]
Looks good
![capture](https://cloud.githubusercontent.com/assets/3631381/17649313/553c18c0-6232-11e6-832a-1cb36237181a.PNG)

**Comment by roofyoreppin** [comment]
Thanks mate, ill be finishing the main town centres of England tonight, if there is a specific area you need me to create let me know

**Comment by gr33nd3v1l** [comment]
There's a ton of routes so far, and next release will probably include userdefined routes
