### ISSUE TITLE
[ROUTE] Thailand bangkok

### ISSUE THREAD

**Issue by pdateam** [gosimulate/gosimulator#76]
![capture](https://cloud.githubusercontent.com/assets/3631381/17649565/e06d9ee0-6238-11e6-987f-c805e5eb6238.PNG)

[thailand_bangkok.txt](https://github.com/gosimulate/gosimulator/files/417037/thailand_bangkok.txt)

_edited_

**Comment by gosimulate** [comment]
Please put file here as attachment.

**Comment by pdateam** [comment]
[thailand_bangkok.txt](https://github.com/gosimulate/gosimulator/files/417014/thailand_bangkok.txt)
oops Sorry and thanks

**Comment by gr33nd3v1l** [comment]
Can't read the file, it has some dots in between and no new lines between sets of coordinates.

Dunno if that is an issue

**Comment by pdateam** [comment]
[thailand_bangkok.txt](https://github.com/gosimulate/gosimulator/files/417037/thailand_bangkok.txt)
![screenshot_2016-08-14-20-39-12](https://cloud.githubusercontent.com/assets/19990873/17649421/4cbe71de-625f-11e6-9543-e61a5cd3d1a3.jpg)
@gr33nd3v1l 
Edit new

**Comment by pdateam** [comment]
hmmm and 
v1.8.0
pokemon setting = error

i use zenfone5 androud 5.0 x86

**Comment by gr33nd3v1l** [comment]
Completely remove previous version and reinstall

**Comment by minibiizz** [comment]
AWESOME คนเขียนเส้นทางหล่อมากกกกก ^^

**Comment by pdateam** [comment]
@minibiizz -*-

**Comment by azziejay** [comment]
everytime i use this map the app crashes

**Comment by gr33nd3v1l** [comment]
I will update it in a few minutes

**Comment by azziejay** [comment]
@gr33nd3v1l thank you!

**Comment by pdateam** [comment]
[new_bangkok.txt](https://github.com/gosimulate/gosimulator/files/418578/new_bangkok.txt)
new edit

**Comment by pdateam** [comment]
[pataya.txt](https://github.com/gosimulate/gosimulator/files/418586/pataya.txt)
and thailand pataya

**Comment by gr33nd3v1l** [comment]
You can edit your first post. I havent been able to make the first route work

**Comment by gr33nd3v1l** [comment]
reupload pataya route please
