### ISSUE TITLE
[ROUTE] Parco Sempione_Milano_Italy

### ISSUE THREAD

**Issue by Thekillerit** [gosimulate/gosimulator#77]
I hope it goes well, inserted all pokestop the park also there are many pokemon.
Bye
![capture](https://cloud.githubusercontent.com/assets/3631381/17649296/b3ac3bf2-6231-11e6-8e7d-e0eedeca6440.PNG)

[Parco Sempione_Milano_Italy.txt](https://github.com/gosimulate/gosimulator/files/417019/Parco.Sempione_Milano_Italy.txt.txt)

**Comment by gr33nd3v1l** [comment]
Looks good
![capture](https://cloud.githubusercontent.com/assets/3631381/17649296/b3ac3bf2-6231-11e6-8e7d-e0eedeca6440.PNG)

**Comment by clivejo** [comment]
I confirm, this will be a great route.

**Comment by xitopodo** [comment]
Great route.

Works good. I caught a 900CP Ivysaur. Also, some high CP Pinsirs and common pokemons.

**Comment by clivejo** [comment]
Full of Charmander...

**Comment by Thekillerit** [comment]
I'm glad you like the place just like I have some time I will bring an update of the coordinates.

**Comment by clivejo** [comment]
I saw with a radar that now there is Kadabra and Kabuto near your route, just some meters away. Sigh..  Maybe if you "enlarge" your route would be great. Also i think you can made more points to make walking more realistic... Thanks for the route man!
