### ISSUE TITLE
[BUG] Changes to username require force app kill or device reboot

### ISSUE THREAD

**Issue by VernMcC** [gosimulate/gosimulator#78]
- I clean installed the app
- I started the app
- I put in my PTC credentials but I mistyped my username (I also updated settings to add a route)
- I started a route
- The app issued a warning about authentication failure
- I checked my credentials and noted the typo
- I fixed the typo
- I tried to start the route but got the same authentication error
- I double checked my credentials (they were right this time)
- I exited the app (close all)
- I started the app
- I tried to start the route but got the authentication failure message
- I force killed the app
- I started the app
- I tried to start the route and it began

I think the issue is there is some memory resident storage that has the initial value of the username field and it only updates from a fresh restart or when initially set. Not a big deal, but considering how many times people have been reporting authentication issues, this could be a contributing cause. Even if they update correctly, they either need to force kill the app or they need to reboot the device to get the updated value in the field to be the value offered during authentication.

**Comment by faizmodan** [comment]
Some times bot couldn't show stop button and it is not stop after stop button

**Comment by VernMcC** [comment]
That seems like a different issue than the authentication fields.

**Comment by gr33nd3v1l** [comment]
_Removed two comments. One was not related to thread_

**Comment by PoGoHelp** [comment]
Strange. With me I don't need to reboot my phone or the app aside from the occasional crashing

**Comment by VernMcC** [comment]
I am using a rooted Samsung Galaxy Tab s2 with the app installed as a system app.

**Comment by gr33nd3v1l** [comment]
Hmm yeah rooted Samsung S5 with system app. Changes normally for me too

**Comment by VernMcC** [comment]
I am not in a position to check, did 1.10 fix this?

> `No more need to restart app after config is changed ( Before changes were not applied untill app restarts)`

**Comment by gr33nd3v1l** [comment]
Yep
