### ISSUE TITLE
[Bug] Kindly resolve it

### ISSUE THREAD

**Issue by djfaizp** [gosimulate/gosimulator#79]
[screenshot_2016-08-14-20-24-36](https://cloud.githubusercontent.com/assets/20996246/17649924/b0d1f03a-625d-11e6-9477-ff74ea6ef5fb.png)
![screenshot_2016-08-14-20-24-19](https://cloud.githubusercontent.com/assets/20996246/17649933/c0f5047a-625d-11e6-99b9-a307da21601f.png)

**Comment by faizmodan** [comment]
There is two images i share

**Comment by gr33nd3v1l** [comment]
What seems to be the issue

**Comment by gosimulate** [comment]
It might happen if u use raspberries. Please try to set use raspberrie > 100000

**Comment by gr33nd3v1l** [comment]
#98
