### ISSUE TITLE
[ROUTE] - Downtown_St_Paul_MN_US

### ISSUE THREAD

**Issue by benyaj** [gosimulate/gosimulator#8]
This route takes you to the through out downtown Saint Paul where you will find rare pokemon and way too many pokestops. Big route.

[St_Paul_Downtown_MN_USA.txt](https://github.com/gosimulate/gosimulator/files/415687/St_Paul_Downtown_MN_USA.txt)

**Comment by benyaj** [comment]
Updated downtown St Paul route
[St_Paul_Downtown_MN_USA_Updated.txt](https://github.com/gosimulate/gosimulator/files/417290/St_Paul_Downtown_MN_USA_Updated.txt)

**Comment by gr33nd3v1l** [comment]
@gosimulate
