### ISSUE TITLE
Ban on slow speed

### ISSUE THREAD

**Issue by madlibquas** [gosimulate/gosimulator#80]
I left the app running and went to sleep , however even at slow speed and not jumping continents received catch flee ban , any help?

**Comment by gr33nd3v1l** [comment]
When did the ban happen. In the morning when you opened your PoGO app?

**Comment by madlibquas** [comment]
The ban happened 4 am, 6 am I wake up and opened the simulator, not open the pokemon .

**Comment by gr33nd3v1l** [comment]
Which route?

**Comment by madlibquas** [comment]
New York route, I started the simulator 9 pm.

**Comment by gr33nd3v1l** [comment]
Hm.. Did your IP maybe reset in the meantime?

**Comment by madlibquas** [comment]
It would be possible? It was the second time this happened to me.

**Comment by roofyoreppin** [comment]
Only leave the bot for long periods of time near an area local to you, most routes are not fully tested & will deffo get you a ban if used at the wrong speed or if the co-ordinates are too far apart, i recieved my soft ban from using the new york route. Im from the UK so i only now use UK routes. Alot of hard work is goin into this so we should all be a little more aware of how we are using the app and not complain about soft bans to the developer, lets just try our best to remember how it happened and give the information to others to avoid it happening again. Best regards to everybody :)

**Comment by madlibquas** [comment]
Ok i will try a route near me thank you.

**Comment by roofyoreppin** [comment]
You can request a route if you read the main page readme file

**Comment by gr33nd3v1l** [comment]
So, issue resolved?

**Comment by madlibquas** [comment]
Yep
