### ISSUE TITLE
InstaCrush bug 1.7.1 + 1.8

### ISSUE THREAD

**Issue by adusk** [gosimulate/gosimulator#81]
On My Samsung Galaxy S6 crash everytime GOSIM if i wanna change Pokemon Settings.
Im Sorry for bad english.

**Comment by VernMcC** [comment]
Do you have an ad blocker running?

**Comment by adusk** [comment]
no i dont

**Comment by gr33nd3v1l** [comment]
Have you completely uninstalled before reinstalling the new version

**Comment by adusk** [comment]
i had and i clear cache and reboot but it crash after i wanna set pokemon evolution and transfer. every other works nice he bot but dont transfer pokemon

**Comment by gr33nd3v1l** [comment]
Try doing this just once more.

Uninstall
Clear cache
Reboot
Reinstall

**Comment by adusk** [comment]
now its work. but a idea is an easy route maker for yourself that we can make short routes. cause i cant find Dratini Farm Routes.

**Comment by gr33nd3v1l** [comment]
In new release
