### ISSUE TITLE
Bug on 1.7.1  

### ISSUE THREAD

**Issue by MrPokemon** [gosimulate/gosimulator#82]
It says " Failed to log in.invalid credentials" 
Please dont just tell me to look at the read me ive done everything reinstalled, the app is also a system app, ive tried multiple pogo account aswell as making a brand new one. And i can sign in to my offical pogo app aswell

**Comment by gr33nd3v1l** [comment]
Give me a screenshot of your settings for the account but blur out the password and part of your email

**Comment by MrPokemon** [comment]
http://m.imgur.com/BPlRb5k 
I think thats what you wanted and I tried 1.8 same thing is happening it was working like a charm up till 1.6 for me

**Comment by MrPokemon** [comment]
I also have this picture aswell http://m.imgur.com/TQGQRS0

**Comment by VernMcC** [comment]
Are you using the plus (+) sign in your gmail address?

**Comment by roofyoreppin** [comment]
I think it could be a CaSe SeNSitiVE bug with the email/password fields

**Comment by MrPokemon** [comment]
No the (+) plus sign is not in my email and i am very ocd so i always type my email and password case sensative

**Comment by roofyoreppin** [comment]
Maybe the entry fields isnt recognizing CaSe SeNsItIvE text

**Comment by VernMcC** [comment]
Did you change either field after you entered the values the first time?  If so did you reboot or force kill the app after the change? (that is from issue 78)

**Comment by gr33nd3v1l** [comment]
What you wrote seems ok from screenshot

Try this
Enter correct credentials
Reboot
See if it works
Try entering correct once more 
Force close
Try

**Comment by MrPokemon** [comment]
Ok ive force killed the app reinstalled it even went through all my files trying to find hiden files that could have been left behind its just not working for me ugh

**Comment by onur9605** [comment]
Did u try remove app data and cache ?

**Comment by gosimulate** [comment]
If it says invalid credintials, then its invalid credintials. Im not creating response, i get it.
