### ISSUE TITLE
[ROUTE] - Manchester_CityCentre_England

### ISSUE THREAD

**Issue by roofyoreppin** [gosimulate/gosimulator#83]
Here is the Manchester City Centre Route starting at picadilly gardens. This route is well designed and has alot of pokemon/pokestops.

![capture](https://cloud.githubusercontent.com/assets/3631381/17651884/ce7c965a-626f-11e6-9761-9ced671cb2f5.PNG)

[Manchester_CityCentre_England.txt](https://github.com/gosimulate/gosimulator/files/417134/Manchester_CityCentre_England.txt)

**Comment by xitopodo** [comment]
I can confirm that works great and there are so much pokestops and pokemons.

I could catch so much Drowzees and evolve to a good 1500CP Hypno! :smile:

**Comment by roofyoreppin** [comment]
Thank you very much i hope to create atleast 2 more routes like this for the UK once i uodate the manchester route once more.

**Comment by roofyoreppin** [comment]
I reccommend you try the Stockport England route!
