### ISSUE TITLE
Not walk the bot

### ISSUE THREAD

**Issue by Dark25** [gosimulate/gosimulator#84]
The bot is paralyzed in the same place and not moving anywhere pilling stays in the same place start and will not start.

**Comment by VernMcC** [comment]
This is the effect when t app detects and adblocker.  Do you have an adblocker?  If so, you can try turning it off to run the app.

**Comment by Dark25** [comment]
I have no app to lock apps

**Comment by gr33nd3v1l** [comment]
Did you select a route
Have you checked all settings and readme troubleshooting

**Comment by Dark25** [comment]
Now Moves But not predenta trapping pokemon , nor do I shows the objects recojidos

**Comment by Dark25** [comment]
Now move but does not show that catches pokemon , nor do I shows the objects collected

**Comment by roofyoreppin** [comment]
Try another version of the app

**Comment by gr33nd3v1l** [comment]
You are probably soft banned or you didn't select a proper route
