### ISSUE TITLE
[ROUTE] Semarang, Central Java, Indonesia

### ISSUE THREAD

**Issue by didayat** [gosimulate/gosimulator#85]
![capture](https://cloud.githubusercontent.com/assets/3631381/17651853/12f9eda6-626f-11e6-901c-56cc33282cf9.PNG)

[tmp_30302-Semarang_Simpang.Lima_Indonesia576351924.txt](https://github.com/gosimulate/gosimulator/files/417855/tmp_30302-Semarang_Simpang.Lima_Indonesia576351924.txt)

**Comment by gr33nd3v1l** [comment]
Txt file?

**Comment by vincentstevent** [comment]
gan it pke app apaan sih bwt ngetracknya?

**Comment by bayoesa** [comment]
Bikinin route jogja donk gan ... btw ajarin cara bikinnya donk gan ?

**Comment by didayat** [comment]
itu mah pakek google maps trus edit pakek paint gan hehehe
