### ISSUE TITLE
Something went wrong while catching pokemon

### ISSUE THREAD

**Issue by BroccoliHunter** [gosimulate/gosimulator#86]
This happens to me since 1.6. Can you fix it? <IMG SRC="http://i.imgur.com/SQrCRi5.png">

**Comment by Ryuukensi** [comment]
please update to version 1.9.0 thanks

**Comment by BroccoliHunter** [comment]
I am already using version 1.9.0 and the bug is still there. Thanks

**Comment by Arclaynsoa** [comment]
@BroccoliHunter It also occured to me previously. 
Possible Issues are:
>Internet connectivity, Check if your connection is stable, try using wifi and data both and see the difference.
>Toggle only the basic settings:
Bot Settings Only turn on:
Hatch Eggs,
Use Berries above 500 CP
Speed Slow

for pokemon
Don't toggle evolve
Toggle on Catch
Toggle on transfer
*Use CP values*

**Comment by Arclaynsoa** [comment]
Were you able to fix this?

**Comment by BroccoliHunter** [comment]
@Arclaynsoa no :/

**Comment by gr33nd3v1l** [comment]
Checked bags and pokeslots? Using a route?

**Comment by BroccoliHunter** [comment]
@gr33nd3v1l my bag and my pokeslots aren't full. Yes i am using a route. (Santa Monica) but it also happens when i use different routes.

**Comment by gr33nd3v1l** [comment]
Dunno..

**Comment by PoGoHelp** [comment]
Perhaps you're softbanned? This happened to my account. Looting pokestops wouldn't work and it couldn't catch any pokemon. Currently waiting for softban to be lifted

**Comment by gr33nd3v1l** [comment]
#98

**Comment by BroccoliHunter** [comment]
@PoGoHelp i am not softbanned. If i would be softbanned it would say "Failed to catch (name of Pokemon)

**Comment by gr33nd3v1l** [comment]
Merged into other thread
