### ISSUE TITLE
Custom route

### ISSUE THREAD

**Issue by Ryuukensi** [gosimulate/gosimulator#87]
how to use custom route? make txt file or app gps save?

**Comment by Arclaynsoa** [comment]
just create a .txt File 
Exmaple is
My_Custom_Route.txt

Create it through here
http://www.findlatitudeandlongitude.com/click-lat-lng-list
spacing should be between 5 and 15 meters

**Comment by Ryuukensi** [comment]
thanks before

**Comment by gosimulate** [comment]
read redme file before posting issue
