### ISSUE TITLE
Bot doesnt walk and I don't have any Ad blocking software

### ISSUE THREAD

**Issue by realcirX** [gosimulate/gosimulator#88]
Bot doesnt walk and I don't have any Ad blocking software

**Comment by Arclaynsoa** [comment]
Please add specifics like
>Are you using custom route?
>Are you using route from the app?
>What are your current bot Settings

Thanks

**Comment by realcirX** [comment]
Im using a custom Route from Issues , i activated use custom routes , hatch eggs is activated , speed is medium, i have picked the route and clean potions and revives is activated , use razzberies is at over 500

**Comment by roofyoreppin** [comment]
Paste your route here i will look at it

**Comment by Arclaynsoa** [comment]
We have two ways of checking if problem is from route or bot settings
1st is try to toggle of use of predefined or custom route then manually point the marker in the map to the location you wish to roam at. If the Bot walks without the use of the route, then issue is with the route.

2nd is if the bot still doesn't walk with the cusom/pre defined route toggled off. Try toggling off clean potions and revive and set razzberries to >10000 and set speed to slow. also toggle off hatch eggs and start bot with the use of the custom route or with a manual start point.

If we are still unable to isolate the problem from the two please do tell

**Comment by realcirX** [comment]
[Manchester_CityCentre_England.txt](https://github.com/gosimulate/gosimulator/files/417183/Manchester_CityCentre_England.txt)

**Comment by realcirX** [comment]
But it doesnt walks at all routes and if i started the bot and wang to stop it it says i have an adblocker which i should deactivate

**Comment by roofyoreppin** [comment]
Im using this route right now, i created it myself, im experiencing no problems with it. I will post my setup

**Comment by roofyoreppin** [comment]
![screenshot_2016-08-14-19-39-17](https://cloud.githubusercontent.com/assets/2872938/17651104/f31a581c-6256-11e6-8a53-35ca308116dc.png)
![screenshot_2016-08-14-19-39-17](https://cloud.githubusercontent.com/assets/2872938/17651111/0d69bfaa-6257-11e6-955d-b484b62ab17e.png)
![screenshot_2016-08-14-19-42-18](https://cloud.githubusercontent.com/assets/2872938/17651115/3d9065a8-6257-11e6-9cae-2acba7657a24.png)

**Comment by roofyoreppin** [comment]
Samsung Galaxy S4 Mini Rooted with bot as system application

**Comment by roofyoreppin** [comment]
What device do you have? Is it rooted?

**Comment by realcirX** [comment]
I have a Meizu M2 mini and it is rooted with the bot as system application

**Comment by Arclaynsoa** [comment]
Do you have any applications like Antivirus etc similar to adblockers? that may have been the cause of your app malfunctioning

**Comment by realcirX** [comment]
Yes i have AVG antivirus installed

**Comment by Arclaynsoa** [comment]
Can you try turning that off and see if you can run the app without any problems or receiving said message afterwards?

**Comment by roofyoreppin** [comment]
Copy my settings & reboot, go onto pokemon go with location services disabled & clean your inventory so only pokeballs are in there & valuable items like lures. Be sure you are below the max capacity for items and check you have atleast 20 pokeballs before running the bot. Also check you are within the maximum capacity for pokemon. If all that fails then check you dont have an anti-virus installed and no form of ad-blocker then do a complete reinstall of the app as a system app and copy my settings once more.

**Comment by realcirX** [comment]
Turning off didnt change anything going to try roofyoreppons suggestion

**Comment by realcirX** [comment]
Didnt work either

**Comment by gr33nd3v1l** [comment]
Have you tried selecting another route and trying to start a few times. Sometimes it starts only on the second start

**Comment by roofyoreppin** [comment]
Is it this specific route or all routes this is happening?

**Comment by realcirX** [comment]
It happens on all routes and i tried it three four times

**Comment by roofyoreppin** [comment]
Have you tried a different version of the bot?

**Comment by realcirX** [comment]
Now i tried one and it works

**Comment by realcirX** [comment]
Thank You!

**Comment by roofyoreppin** [comment]
What did you try exactly lol? Different version? Or my original suggestion?

**Comment by realcirX** [comment]
A different version

**Comment by roofyoreppin** [comment]
Ok great this helps the developer. You should try once more with 1.9 and if it doesnt work then i guess you know another version does.
