### ISSUE TITLE
[BUG] Transfer IV/CP Confusion

### ISSUE THREAD

**Issue by D3vr04** [gosimulate/gosimulator#89]
When Transfer and Use IV for transfer is toggled ON(red), 
the next line: Transfer below... is changed to CP. 
When Transfer and Use IV for transfer is toggled OFF(gray), 
the next line: Transfer below... is changed to IV.
Isn't this backwards? or is a fix in the works? or am I missing something? lol

**Comment by gr33nd3v1l** [comment]
Slider to left is off
Slider to right is on
IV value is 0-100%
CP value is 0-99999

**Comment by gr33nd3v1l** [comment]
Oh. I see. Willfix

**Comment by D3vr04** [comment]
lol 
thanks @gr33nd3v1l Please let me know once fixed.

**Comment by gosimulate** [comment]
fixed
