### ISSUE TITLE
Boston Route Crash

### ISSUE THREAD

**Issue by VernMcC** [gosimulate/gosimulator#9]
Whenever I select the Boston Route and try to start the app crashes.  v1.3.0
Using other routes works fine, but the Boston route crashes.  I mapped out the Boston Route in Google Earth and did not see any errors in the route.

**Comment by scissors14** [comment]
I vouche. Boston won't work for me either

**Comment by VernMcC** [comment]
I think I found it, in live 153 of the route, the long has an alpha character:
42.38862,-71.151216a

**Comment by VernMcC** [comment]
I ran some regex on the text files with the lat/long data and this dropped out the Boston alpha character too:

- gosim-1.3.0/res/raw$ grep --perl-regexp --invert-match "^\s*(\-?)\d{1,3}\.\d{1,6},\s*(\-?)\d{1,3}\.\d{1,6}\s*$" *.txt

This dropped out the errant line in boston.txt

It also noted that the first line of sarajevo has the following bytes leading the corrdinates.  I don't have a VPN for Europe, so I have not tried the Sarajevo route yet, but wanted to highlight what the grep looking for potential mismatches found.
First three bytes of sarajevo.txt: **EF BB BF**

**Comment by gosimulate** [comment]
Fixed
