### ISSUE TITLE
[Suggestion] IV Renaming

### ISSUE THREAD

**Issue by skidskidskidiot** [gosimulate/gosimulator#90]
A nice feature would be is if the simulator could rename our pokemon to its IV percentage with different formats to choose from:
IV-Pokemon 
Pokemon-IV 
or IV
e.g.
56-Magikarp

**Comment by skidskidskidiot** [comment]
Whoops, that was an accident anyways but

56-Magikarp
38-Eevee
or just simply the IV% number: 72

Thanks!

**Comment by gr33nd3v1l** [comment]
I don't know about this.. You can see the IV in the pokemon bag viewer.
Depends how easy it is for him to make. He'll close it if he doesn't like it
For now.. enhancement

**Comment by VernMcC** [comment]
There is a windows cli app that does this already: [http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/564278-ivy-pokemon-batch-renamer-show-pokemon-iv-perfection-their-nickname.html](url)

**Comment by gosimulate** [comment]
not neccasary
