### ISSUE TITLE
[Suggestion] Inventory Viewing

### ISSUE THREAD

**Issue by Arclaynsoa** [gosimulate/gosimulator#91]
A lot of the users are reporting issues about not catching any pokemons and the like. I think it would help if we have an option to view the inventory space and items via the app to identify first if the problem is originating there.

**Comment by gr33nd3v1l** [comment]
I believe he is working on this? Unsure

**Comment by ManusiaDariBumi** [comment]
thanks dor making this thread
i did thinking like u 
but well
u already did this
thanks
my friend suggest that i must not use go simulator and pogo (same account) if i dont want to get banned 😢😢😢
i do really hope this feature
so we can use another acc as previous acc can we configured for evolving,transfer,and clearing items 😊😊😊
