### ISSUE TITLE
[TRANSLATION] Please, make a russian version

### ISSUE THREAD

**Issue by FegerotiX** [gosimulate/gosimulator#92]
I tend your bot on a 4pda http://4pda.ru/forum/index.php?s=&showtopic=759623&view=findpost&p=52035197 (russian forum). Please make a russian version.

**Comment by gr33nd3v1l** [comment]
Possibly? @gosimulate

**Comment by gosimulate** [comment]
Going to extract all possible strigns from game tomorrow nad upload string.xml so ppl can translate.

**Comment by roofyoreppin** [comment]
@gosimulate I can help translate to perfect english if you'd like?

**Comment by FegerotiX** [comment]
So, Russian will be in simulator?

**Comment by gr33nd3v1l** [comment]
Soon, yes
