### ISSUE TITLE
[Suggestion]Bot catching transfering evolving info - statistics

### ISSUE THREAD

**Issue by spotifykeks** [gosimulate/gosimulator#94]
A Suggestion I hope u guys can do because i think everybody needs it
While running bot at night or day u dont really know or remember what happens while the bot is running
so i think you guys should add a thing that when u press stop (running the bot)
then a popup or a window or something will open or write down at the info thing under the map
While bot was running XX:XX:XX time
Caught XXX Pokemon {+ {in here there will be a plus for additional info} which will open down {
XXX bulbusars
XXX charmander
and so on}}
Transfered XXX Pokemon {here will be a plus which will get additional info} {\
Transfered XXX of XXX pokemon IN TOTAL TRANSFERED XXX POKEMON IN TOTAL GOT XXX OF THAT POKEMONS CANDY }
u guys figure out how to do that
Evolved XXX Pokemon {additional thing bluh bluh u guys got it i dont think i should elaborate more because u r not stupid
if i already got your attention i just want to say thank you for all the good and hard work you put in to this thing
Good luck !
I would like to get a confirmation or a declanation (idk the spell on that)
if u think you can do it or is it even a good idea

**Comment by spotifykeks** [comment]
Can you confirm this may happen????

**Comment by gr33nd3v1l** [comment]
Depends on the dev. I'm just tagging stuff I consider worth looking at :)

**Comment by spotifykeks** [comment]
Ok so 
Catch data
Evolve Data
Transfer Data
Items acquired and items that were Cleaned

**Comment by gr33nd3v1l** [comment]
#23

**Comment by djfaizp** [comment]
Mean Nicknamed poke will not transfer ever !! Amazing @gr33nd3v1l

**Comment by spotifykeks** [comment]
@djfaizp
I think you can just favorite it.
