### ISSUE TITLE
[ROUTE]Hampton_Beach_NH_US

### ISSUE THREAD

**Issue by Tattooedgod** [gosimulate/gosimulator#96]
[New Hampshire_Hampton Beach_USA.txt](https://github.com/gosimulate/gosimulator/files/417302/Newhampton_Hampton.Beach_USA.txt)

![capture](https://cloud.githubusercontent.com/assets/3631381/17652490/f9d59708-627d-11e6-849d-41221376d86a.PNG)

**Comment by gr33nd3v1l** [comment]
_edited_

**Comment by PoGoHelp** [comment]
Are you taking route requests? I have a good one

**Comment by gr33nd3v1l** [comment]
You can submit routes here. But no more routes will be implemented in the app itself most likely

**Comment by PoGoHelp** [comment]
The thing is that I can't do routes. I don't have access to a pc and I have no idea how to do it on mobile:(

**Comment by gr33nd3v1l** [comment]
I can make one for you. Let me know where you want it to go and what landmarks to include. Or streets
