### ISSUE TITLE
[1.9.0] [Bug] Something went wrong while catching pokemon

### ISSUE THREAD

**Issue by LiquidAtoR** [gosimulate/gosimulator#98]
When you run out of regular Pokeballs it will not switch up to the next better ones avaliable. 
It will simply say "something went wrong while catching pokémon" until the bot loots another pokestop and has regular Pokeballs again.
Then it will catch pokémon until the regular Pokeballs have finished and it starts over with the messages.

**Comment by gr33nd3v1l** [comment]
Found this out today too. Most of the something went wrong with catching pokemon messages are due to pokeballs running out

**Comment by nonamedeadpool** [comment]
this been happening since 1.6 v

**Comment by sgtkwol** [comment]
Can you add an option to use Great/Ultra balls, please?

**Comment by gr33nd3v1l** [comment]
#23 @sgtkwol
